### ISSUE TITLE
A ordem da apresentação das imagens na aba "media" de um artigo

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.portal#11]
A issue https://github.com/plonegovbr/portal.buildout/issues/3 deve ser resolvida a princípio nesse pacote, e depois incorporado no https://github.com/collective/collective.nitf .

----

A ordem das imagens na aba "media" no objeto Artigo, não é alterada. A funcionalidade de alteração de ordem somente é efetivada através da aba "conteúdo".

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by hvelarde** [comment]
fechado por falta de feedback.
