### ISSUE TITLE
Produto de Agenda não instalado em Ambientes já Existentes

### ISSUE THREAD

**Issue by Dadlo** [plonegovbr/brasil.gov.portal#154]
O produto de agenda é instalado automaticamente durante a criação de um novo ambiente.
O produto de agenda não pode ser instalado manualmente em um ambiente já existente, pois seu perfil está escondido da visualização do usuário final.

Sugestão: Instalação via upgrade step específico

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by idgserpro** [comment]
Esse relado ainda não pode ser fechado. É necessário criar um upgrade step para instalar o produto Agenda em sites que ele não estiver instado e criar um upgrade step para preencher o campo estilo da configuração do collective.cover. Ver os dois últimos comentários acima.

**Comment by idgserpro** [comment]
@hvelarde 

o problema não é no brasil.gov.agenda como cogitado em https://github.com/plonegovbr/brasil.gov.portal/pull/186#issuecomment-78708932, mas sim no brasil.gov.portal. Vou tentar explicar de forma mais detalhada:

- Até a versão 1.0.1 do brasil.gov.portal o brasil.gov.agenda não era instalado quando o plone site era criado.
- A partir da versão 1.0.2, o brasil.gov.agenda passou a ser instalado na criação do plone site com o commit https://github.com/plonegovbr/brasil.gov.portal/commit/378986a62338ab79ab7e636b13996578b37ec201 do @Dadlo 
- No entanto, na versão 1.0.2, não foi criado um upgrade step para instalar o brasil.gov.agenda em sites que foram criados em versões anteriores à versão 1.0.2, como foi feito recentemente com o brasil.gov.protlets em https://github.com/plonegovbr/brasil.gov.portal/commit/65462e9276b8991b7a319f104a0a6e9709936ccc
- Então, sites que foram criados orginalmente, por exemplo, com a versão 1.0.1 e que depois foram atualizados para a versão 1.0.2, sem instalar o brasil.gov.agenda 'na mão', vão continuar sem ter o brasil.gov.agenda instalado.
- Na versão 1.0.3 do brasil.gov.portal foi criado pelo @ericof o upgrade step v10300 com o passo [atualiza_pacotes_instalados](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/upgrades/v10300/handler.py#L61). Esse método 'Exibe pacotes de dependencias'. O método [_instala_pacote](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/setuphandlers.py#L150) utilizado por ele, não instala realmente os produtos. Somente 'marca o produto como instalado', não instala os profiles. Então, em sites criados na versão 1.0.1, que não tiveram o brasil.gov.agenda instalado 'na mão', e que foram atualizado para versão 1.0.3, o método _instala_pacote irá marcar o brasil.gov.agenda como instalado no portal_quickinstaller mas não aplica o profile dele. O brasil.gov.agenda fica como instalado no portal_quickinstaller mas ele não está realmente instaldo.

**Comment by hvelarde** [comment]
acho que vamos ter que resolver esse problema e não estou seguro qual é o melhor jeito.

uma coisa fica clara: o brasil.gov.agenda não pode estar oculto no painel de controle,

**Comment by idgserpro** [comment]
O brasil.gov.agenda não fica oculto no painel de controle. Isso já é assim hoje.

Acho que um jeito simples de resolver é criar um upgrade step que verifica se o tipo Agenda existe o portal_types e caso não exista, aplicar o profile do brasil.gov.agenda.

Também é necessário criar um outro upgrade step que preencha o campo estilo da configuração do collective.cover, devido a:

https://github.com/plonegovbr/brasil.gov.portal/issues/154#issuecomment-64793851
e
https://github.com/collective/collective.cover/issues/465

**Comment by hvelarde** [comment]
pode ser um workaround válido para essa situação; respeito do outro problema, não, o certo é corregir esse bug no collective.cover e atualizar a versão.

**Comment by idgserpro** [comment]
Mesmo corrigindo o erro no collective.cover, acho melhor ter um upgrade step que atualiza novamente o campo estilo da configuração. Isso porque mesmo que se coloque purge = "false" no campo estilo, ele ainda vai adicionar os valores defaults como dito pelo @fredvd em https://github.com/collective/collective.cover/issues/465#issuecomment-70632568. E em https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/profiles/default/registry.xml#L61 não tem os valores default.

**Comment by hvelarde** [comment]
o https://github.com/collective/collective.cover/issues/465 foi fechado.
