### ISSUE TITLE
Busca não encontra tags

### ISSUE THREAD

**Issue by GiuseppeRomagnoli** [plonegovbr/brasil.gov.portal#155]
A busca no portal não está retornando pesquisa por tags, porém se for clicado na tag a busca traz os itens que estão vinculados a mesma.

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by winstonf88** [comment]
O "problema" ainda persiste. 
A questão aqui é que para realizar uma busca por tags é preciso usar o índice "Subject (KeywordIndex), a busca pesquisa pelo índice "SearchableText (ZCTextIndex)". 
Como no catalog não é possível fazer buscas usando operador "or", isto não é possível sem instalação do [Products.AdvancedQuery](http://docs.plone.org/develop/plone/searching_and_indexing/query.html#boolean-queries-advancedquery).

**Comment by hvelarde** [comment]
então, acho que isso não é um problema do IDGB e podemos fechar esta issue; se quiserem colocar uma nota na documentação, fiquem a vontade.

**Comment by idgserpro** [comment]
A busca por tag funciona em um Plone sem o IDG. Talvez isso seja um efeito colateral do brasil.gov.vcge. Temos que verificar.

**Comment by winstonf88** [comment]
Realmente no Plone sem IDG funciona e os índices são os mesmos.
@hvelarde alguma ideia do pq? eu não sei nem onde procurar agora.

**Comment by hvelarde** [comment]
podem me contar como estão fazendo uma busca com várias tags? a busca padrão do Plone não suporta isso.

**Comment by winstonf88** [comment]
eu simplesmente entrei na aba de categorização e adicionei uma tag qualquer, depois pesquisei por esse nome na busca do site

**Comment by winstonf88** [comment]
Sim. Porém, no Plone (sem IDG) uma busca usando o índice SearchableText retorna termos das tags. Já no IDG, a mesma busca não encontra tags.

**Comment by hvelarde** [comment]
cria um teste que demostre isso, por favor.

**Comment by winstonf88** [comment]
@hvelarde teste criado no PR #254

**Comment by hvelarde** [comment]
te deixei um comentário lá.

**Comment by claytonc** [comment]
As versões  do plone.app.contenttypes 1.1 e 1.1.1 corrige o problema.

**Comment by idgserpro** [comment]
Ver https://github.com/plonegovbr/brasil.gov.portal/issues/349 e https://github.com/plonegovbr/brasil.gov.portal/issues/351 que devem ser tratados individualmente ao invés desse relato.

https://github.com/plonegovbr/brasil.gov.portal/issues/359 está em andamento para atualizar em definitivo plone.app.contenttypes para 1.1.1.

**Comment by monicakrs** [comment]
Prezados, estou tendo esse problema. Ao clicar em uma tag de qualquer notícia (link noticias/ultimas-noticias), o resultado da pesquisa vem vazio (url @@busca?subject:list=cgu). Mas, se pesquiso pela tag na caixa de pesquisa os resultados vem corretos. 

Versão
    Portal Padrão 2.1.1
    Plone 4.3.18 (4320)
    CMF 2.2.10
    Zope 2.13.28
    Python 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
    PIL 3.3.3 (Pillow)
    collective.nitf 2.1b4 
    sc.embedder: Install 1.5b2

**Comment by idgserpro** [comment]
@monicakrs esse relato era quando buscávamos a tags na caixa de pesquisa. E você falou que isso está funcionando. Então sugiro você criar uma nova issue com o seu problema.
