### ISSUE TITLE
botões "social like"  desaparecem

### ISSUE THREAD

**Issue by GiuseppeRomagnoli** [plonegovbr/brasil.gov.portal#156]
Quando é desmarcada a  opção de segurança "Permitir a qualquer um ver as informações sobre o conteúdo." onde autor da publicação não aparece mais abaixo do título do conteúdo (viewlet-below-content-title) os itens de redes sociais também desaparecem porque estão na mesma viewlet.

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by idgserpro** [comment]
Isso ainda ocorre para conteúdos diferentes de notícias. Mas isso parece mais um problema do sc.social.like.

**Comment by winstonf88** [comment]
Fiz os testes e este problema não persiste. Podemos fechar?

**Comment by idgserpro** [comment]
Isso ainda ocorre para conteúdos diferentes de notícias.

**Comment by winstonf88** [comment]
verdade, tinha testado com uma notícia.
