### ISSUE TITLE
Bug na exibição da data de criação de conteúdo na visão  "summary view"

### ISSUE THREAD

**Issue by GiuseppeRomagnoli** [plonegovbr/brasil.gov.portal#157]
Quando um item (ex. page)  é criado sem especificar a data, na visão "summary view' aparece sempre com a data: 31/12/1969 e hora: 00:00.
Em outras visões a data aparece de forma correta.

**Comment by winstonf88** [comment]
@GiuseppeRomagnoli poderia explicar melhorar como reproduzir este problema? não entendi muito bem.

**Comment by GiuseppeRomagnoli** [comment]
Oi @winstonf88, quando criava um documento (página por exemplo) e consultava o conteúdo na visão summary, aparecia a data de criação 31/12/1969 e hora: 00:00. Mas não sei se na nova versão já foi corrigido.

**Comment by idgserpro** [comment]
@winstonf88 na pasta notícias, adicione uma nova notícia, sem adicionar Data nem publicá-la.

Depois, na pasta, selecione como visão "Summary view". Você verá o comportamento descrito pelo @GiuseppeRomagnoli.

Vejo dois problemas aí: aparecer "Summary View" ao invés de "Visão Sumária" traduzido, e essa data 1969.

O 1969 é padrão Plone (na verdade vem de https://github.com/zopefoundation/Products.CMFDefault/blob/0bfdc6b3bd1d4c0abeba1db4eafb6aab8ac2cc4b/Products/CMFDefault/DublinCore.py#L272), esse dado é o *effective* presente no portal_catalog para algo que não foi publicado/não possui workflow. *expires* se não tiver setado também possui data "parecida", sendo composto por "2499/12/31 00:00:00" (ver https://github.com/zopefoundation/Products.CMFDefault/blob/0bfdc6b3bd1d4c0abeba1db4eafb6aab8ac2cc4b/Products/CMFDefault/DublinCore.py#L305). Sobre o motivo dessas constantes, 1969 deve ter relação com unix epoch, e o 2499 também deve ser relacionado de alguma forma já que para sistemas 64 bits, acho que se você fizer ```zdump -v /etc/localtime``` numa máquina Linux esse é o último ano. Portanto, é "arbitrário" mas segue uma lógica mínima.

Acredito que as datas são assim definidas para facilitar as comparações de datas em queries, códigos e etc já que também é um tipo Date e para permitir um índice mais eficiente como "DateIndex" no catalog.

Portanto, como customizamos essa view em https://github.com/plonegovbr/brasil.gov.portal/blob/ad5e3a732efe4e5960ca6e7f8f91c6934adb9185/src/brasil/gov/portal/browser/content/templates/custom_summary_view.pt e agora ela passa a mostrar o effective ao invés do modified (ver https://github.com/plonegovbr/brasil.gov.portal/commit/dcf629270ce6b95106d2e47b1b6df762921e3e91) eu pergunto @Dadlo e ao @rodfersou: qual foi a motivação para a customização dessa view? Queria entender para saber se esse é um comportamento previsto ou se realmente é necessário usar outro índice. Se for comportamento previsto, recomendo fechar esse relato.

Aos envolvidos nesse relato: alguém mais pode confirmar esse erro de tradução que mencionei na pasta notícias? Se for o caso, deve ser aberto outro relato para correção da internacionalização do nome dessa view.

**Comment by rodfersou** [comment]
Acredito que foi algum requisito solicitado para usar a data de publicação globalmente. Poderiamos seguir a regra de mostrar o effective date caso existir, e o modified caso não existir effective date.

**Comment by rodfersou** [comment]
@hvelarde não lembro o funcionamento do modified.. não tenho certeza agora qual seria o melhor caminho
