### ISSUE TITLE
Portal Padrão não lista tipo de conteúdo "pasta" nas visões de pasta

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#160]
O Portal Padrão configura o Plone para não buscar em conteúdos do tipo pasta, o que faz com que esse tipo de conteúdo deixe de aparecer nas listagens/visões (por exemplo, "visão sumária").
No entanto, alguns clientes estão precisando listar pastas.

Nossa sugestão é que o Portal Padrão busque também no tipo de conteúdo "pasta", pois dessa forma o problema relatado deixará de ocorrer.

**Comment by winstonf88** [comment]
Fiz os testes e este problema não persiste. Podemos fechar?

**Comment by idgserpro** [comment]
O problema ainda ocorre.

**Comment by winstonf88** [comment]
Onde fica essas configurações, qual produto/xml?

**Comment by idgserpro** [comment]
A configuração é "Configuração do Site -> Busca -> Define os tipos a serem exibidos no site e buscados". Não sei de cabeça qual é o xml.

**Comment by winstonf88** [comment]
O local das configurações no Plone eu sei onde fica. Não estou conseguindo
achar o produto/código.

Em seg, 14 de dez de 2015 às 17:21, idgserpro <notifications@github.com>
escreveu:

**Comment by winstonf88** [comment]
O local das configurações no Plone eu sei onde fica. Não estou conseguindo achar o produto/código.

**Comment by winstonf88** [comment]
Alguém poderia me dizer em qual produto ficam essas configurações?

**Comment by idgserpro** [comment]
@winstonf88 eu acho que é aqui:
https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/profiles/default/registry.xml#L46

**Comment by idgserpro** [comment]
@winstonf88 opa acho que ali é só do Cover. Tem que ver onde é o do portal.

**Comment by idgserpro** [comment]
@winstonf88 achei:
https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/profiles/default/propertiestool.xml#L21

**Comment by idgserpro** [comment]
@winstonf88 tem que ver o porquer desse commit https://github.com/plonegovbr/brasil.gov.portal/commit/5c98d61da3bb6bc4b14279ba0a1b565eed3f5076

@ericof ?

**Comment by ericof** [comment]
Pedido da Secom para não listar as pastas em resultados de busca (puxando pela memória)

**Comment by idgserpro** [comment]
@winstonf88 então temos que arrumar um jeito de listar as pastas nas visões sem alterar a propriedade ```types_not_searched```. Ou seja, temos que desvincular esses dois comportamentos.

**Comment by idgserpro** [comment]
Abrimos um relato no Plone. https://github.com/plone/Products.CMFPlone/issues/1985
