### ISSUE TITLE
Página de impressão com informações desnecessárias

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#161]
Ao abrir um página no Portal Padrão e clicar em 'Visualizar impressão' do browser, aparecem informações desnecessárias, como menus, links de redes sociais e links de acessibilidade.

![capturar1](https://cloud.githubusercontent.com/assets/8203476/3644133/20d1ec8e-10dd-11e4-89ee-2c610e917c01.PNG)

**Comment by idgserpro** [comment]
As demais informações desnecessárias serão corrigidas via pull request.

**Comment by hvelarde** [comment]
podemos fechar este?

**Comment by idgserpro** [comment]
Acho que esse relato deve ficar aberto até seja feito um merge do request https://github.com/plonegovbr/brasil.gov.portal/pull/183 e que seja gerado um release com essa correção.

**Comment by idgserpro** [comment]
Correção do problema foi completada em: https://github.com/plonegovbr/brasil.gov.portal/commit/93003c1e06ff4ca64dc3325510ccdbddfa0fc78e
