### ISSUE TITLE
Erro ao editar um Banner Tile do collective.cover.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#162]
Quando utilizamos o Plone 4.3.3, e tentamos editar um Banner Tile, através  da aba 'Compor' da página inicial, ocorre o erro:

...
Module zope.traversing.adapters, line 50, in traverse
- **traceback_info**: (<NamedImageWidget 'collective.cover.banner.image'>, 'file_icon', ())
  LocationError: (<NamedImageWidget 'collective.cover.banner.image'>, 'file_icon')

Esse é um erro conhecido e já foi corrigido no produto plone.formwidget.namedfile versão 1.0.10. Ver:

https://github.com/collective/collective.cover/issues/417

No entanto, o versions.cfg de vocês, utiliza o plone.formwidget.namedfile versão 1.0.9. O collective.cover recomenda utilizar o plone.formwidget.namedfile versão 1.0.10 como pode ser visto aqui:

https://github.com/collective/collective.cover#installation

Favor alterar o versions.cfg para utilizar a versão 1.0.10 do plone.formwidget.namedfile.

**Comment by taniaa** [comment]
Conforme linha 510, foi atualizado para a versão plone.formwidget.namedfile = 1.0.11:

https://github.com/plonegovbr/portalpadrao.release/blob/master/1.0.5/versions.cfg
