### ISSUE TITLE
Barra de destaques deixa de ser exibida se a visão é alterada

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#167]
Quando alteramos a visão do objeto 'Destaques do portal' (objeto de id destaques), para 'Visão Padrão', a barra de destaques deixa de ser exiba no portal. Isso ocorre porque o ajax que renderiza a barra pega o conteúdo do objeto 'destaques' e exibe o que estiver dentro de '#content > .row', como pode ser visto abaixo:

https://github.com/plonegovbr/brasil.gov.portal/blob/1.1.3/src/brasil/gov/portal/static/js/main.js#L176

No entanto, na visão 'Visão Padrão', a div com a classe 'row' não é filha imediata da div '#content'. Então o seletor '#content > .row' não seleciona nenhum conteúdo.

Minha sugestão é utilizar o seletor '#content .row', de modo que ele selecione qualquer classe 'row' dentro da div '#content', e não somente as que forem filhas imediatas.

**Comment by winstonf88** [comment]
Fiz o teste na home do portal e barra de destaques está sendo exibida mesmo na visão padrão. Podemos fechar?

**Comment by idgserpro** [comment]
O problema ainda ocorre. Tem que mudar a visão da pasta 'Destaques do portal'.

**Comment by winstonf88** [comment]
criei um PR pra correção do problema.
