### ISSUE TITLE
Validação para o campo Tamanho para imagens

### ISSUE THREAD

**Issue by tomfsa** [plonegovbr/brasil.gov.portal#168]
Prezados, o campo "tamanho para imagens" da <manipulação de imagens> necessita de validação quanto ao valor inserido, pois se o valor por diferente corrompe visão "capa" e não é mais possível a exibição de imagens no site.

**Comment by hvelarde** [comment]
eu não estou entendendo o problema; pode nos dar mais informação, por favor.

**Comment by idgserpro** [comment]
@hvelarde Adicione um tile básico na capa, com uma imagem qualquer. Adicione também um tipo imagem qualquer na raiz do site.

Vá em http://localhost:8080/Plone/@@imaging-controlpanel num portal IDG. Adicione um novo tamanho, por exemplo ```destaque 501x380``` - veja que estou usando 'x' e não ':' como separador do tamanho. Isso é feito pra adicionar um tamanho inválido.

Isso quebra a capa e a visualização da imagem criada fora da capa.

Testei no Plone 5.0 e o erro persiste. Nesses termos, fechei esse relato e abri um diretamente no Plone em https://github.com/plone/Products.CMFPlone/issues/1393.

@tomfsa favor acompanhar diretamente no Plone.

**Comment by hvelarde** [comment]
@idgserpro obrigado!

**Comment by idgserpro** [comment]
@hvelarde com as novas versões do plone.app.blocks em novas versões do collective.cover (que foi o ambiente que eu testei) já se evita a capa de quebrar, como previsto em https://github.com/plonegovbr/brasil.gov.tiles/issues/136#issuecomment-172981781. Não acho necessário abrir um relato no cover. Fica assim na última versão do cover:

![selecao_121](https://cloud.githubusercontent.com/assets/8203476/13113417/1fbb8ee0-d576-11e5-9932-6f8b42843f1d.png)

![selecao_122](https://cloud.githubusercontent.com/assets/8203476/13113421/2387266a-d576-11e5-8947-75cb28820783.png)

Portanto é mais questão do Plone mesmo, é importante evitar o que acontece em https://github.com/plone/Products.CMFPlone/issues/1393
