### ISSUE TITLE
Atualizar versão do collective.cover

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#170]
collective.cover já está na versão 1.0.a9, e precisamos de uma correção que foi disponibilizada na 1.0a7. Podemos alterar nós mesmos no versions.cfg esse pacote e essa versão em específico, mas gostaríamos de distanciarmos o mínimo possível das dependências previstas por exemplo em

https://github.com/plonegovbr/portalpadrao.release/blob/master/1.0.3/versions.cfg

ainda mais que esse componente em específico a partir da versão 1.0a7 dá erro na capa devido a registros que devem ser persistidos através do upgradeStep.

Existe alguma previsão de, no próximo release, haver uma atualização dessas dependências?

**Comment by idgserpro** [comment]
@ericof 
@hvelarde 

Depois do commit https://github.com/collective/collective.cover/commit/9eeb30b047e57e4e5ef278d6f6b1e1193810de62, o Site Administrator passou a poder alterar as configurações do collective.cover. Esse commit está presente na versão 1.0a9+ do collective.cover. No entanto, a versão utilizada pelo brasil.gov.portal é a 1.0a6. Ou seja, hoje, no brasil.gov.portal, o Site Administrator não pode configurar o collective.cover. Então pergunto. Há previsão de atualizar a versão do collective.cover utilizada pelo brasil.gov.portal?

**Comment by ericof** [comment]
Temos sido **muito** conservadores com o upgrade do collective.cover. Como o cover teve um volume considerável de atualizações no período teríamos que realizar muitos testes -- e portar os upgrade steps -- para que não tenhamos problemas com a atualização.
O que acha @hvelarde ?

**Comment by taniaa** [comment]
Atualizar o collective.cover seria bem legal! Até o Portal Padrão do Legislativo poderia se beneficiar do produto brasil.gov.tiles funcionar e talvez um dia juntar esforços de manutenção :)

**Comment by hvelarde** [comment]
não deve ser usada a versão 1.0a10 pois ela introduziu vários bugs que ainda não foram completamente consertados.

eu acho que atualizar à versão 1.0a9 deve ser trivial; não vi nenhuma coisa que possa quebrar os tiles. sugiro testar num ambiente de homologação e não esquecer rodar todos os upgrade steps listados.

**Comment by idgserpro** [comment]
Instalei brasil.gov.portal com o collective.cover 1.0a9 e não houve problema. Também rodei os teste do brasil.gov.portal com o collective.cover 1.0a9 e todos passaram. No entanto, em um portal que foi criado com o collective.cover 1.0a6 e depois atualizado para o collective.cover 1.0a9, ocorreu o erro:

	Traceback (innermost last):

	    Module ZPublisher.Publish, line 138, in publish
	    Module ZPublisher.mapply, line 77, in mapply
	    Module ZPublisher.Publish, line 48, in call_object
	    Module grokcore.view.components, line 150, in __call__
	    Module grokcore.view.components, line 154, in _render_template
	    Module five.grok.components, line 130, in render
	    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
	    Module five.pt.engine, line 93, in __call__
	    Module z3c.pt.pagetemplate, line 163, in render
	    Module chameleon.zpt.template, line 258, in render
	    Module chameleon.template, line 170, in render
	    Module c67793578388aa11f6c8718eb304fc43.py, line 145, in render
	    Module 7f0fdfc89e7534a9779ce013c93c546c.py, line 1392, in render_master
	    Module 7f0fdfc89e7534a9779ce013c93c546c.py, line 612, in render_content
	    Module c67793578388aa11f6c8718eb304fc43.py, line 108, in __fill_main
	    Module five.pt.expressions, line 161, in __call__
	    Module collective.cover.layout, line 126, in render_view
	    Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
	    Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
	    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
	    Module five.pt.engine, line 93, in __call__
	    Module z3c.pt.pagetemplate, line 163, in render
	    Module chameleon.zpt.template, line 258, in render
	    Module chameleon.template, line 188, in render
	    Module chameleon.template, line 170, in render
	    Module 1e6b541d4432fb89c9a1a77062a79eb8.py, line 101, in render
	    Module collective.cover.layout, line 42, in get_layout
	    Module plone.registry.registry, line 74, in forInterface

	KeyError: 'Interface `collective.cover.controlpanel.ICoverSettings` defines a field `grid_system`, for which there is no record.' - Expression: "layout/render_view" - Filename: ... 0a9-py2.7.egg/collective/cover/browser/templates/view.pt - Location: (line 13: col 32) - Source: tal:replace="structure layout/render_view" /> ^^^^^^^^^^^^^^^^^^ - Expression: "python:view.get_layout(mode)" - Filename: ... y2.7.egg/collective/cover/layout_templates/pagelayout.pt - Location: (line 11: col 37) - Source: ... on repeat="section python:view.get_layout(mode)"> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Arguments: repeat: {...} (0) context: <ImplicitAcquisitionWrapper home at 0xcc153ec> views: <ViewMapper - at 0xca00bac> modules: <TraversableModuleImporter - at 0xa15630c> args: <tuple - at 0xb74e502cL> loop: {...} (0) nothing: <NoneType - at 0x81aa514> target_language: <NoneType - at 0x81aa514> default: <object - at 0xb75047f0L> request: <instance - at 0xcf6708c> wrapped_repeat: {...} (0) mode: view template: <ViewPageTemplateFile - at 0xe29256c> translate: <function translate at 0xb54d4294L> options: {...} (1) view: <PageLayout layout at 0xd5a084c> 

No entanto, após os upgrade steps do collective.cover serem executados, o erro deixou de ocorrer e o portal funcionou normalmente. Quando o collective.cover for atualizado no versions.cfg, seria interessante colocar um nota no README.txt alertando para a necessidade de execução dos upgrade steps do collective.cover. @ericof @hvelarde o que vocês acham?

Também executei os testes do brasil.gov.tiles e ocorreu o erro abaixo em vários testes:

	Error in test test_tile_is_empty (brasil.gov.tiles.tests.test_mediacarousel_tile.MediaCarouselTileTestCase)
	Traceback (most recent call last):
	  File "/home/xxx/pythons/python273/lib/python2.7/unittest/case.py", line 318, in run
	    self.setUp()
	  File "/home/xxx/brasil.gov.tiles/src/brasil/gov/tiles/tests/test_mediacarousel_tile.py", line 27, in setUp
	    self.cover = self.portal['frontpage']
	  File "/home/xxx/brasil.gov.tiles/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 784, in __getitem__
	    raise KeyError, key
	KeyError: 'frontpage'

Acho que no collective.cover 1.0a9 não existe o objeto 'frontpage'. Os teste do brasil.gov.tiles teriam que ser arrumados. Mas apesar dos teste falharem, as tiles fucionaram corretamente.

**Comment by hvelarde** [comment]
ótimo! era o que eu imaginava.

eu acho que tem jeito de rodar os upgrade steps duma dependência criando um upgrade step do portal; nunca fiz mas deve ser simples.

isso deve ser tratado num issue diferente.

**Comment by idgserpro** [comment]
@hvelarde não seria melhor alterar o título e o label dessa issue, ao invés de criar uma outra, uma vez que já temos uma discurssão aqui que se refere somente à atualização do collective.cover?

**Comment by hvelarde** [comment]
@idgserpro sugestões?

**Comment by idgserpro** [comment]
@hvelarde 

Atualizei o titulo da issue. Sobre o upgrade step do brasil.gov.portal chamar o upgrade step do collective.cover, eu não concordo com isso. Acho que uma nota no README.txt seria suficiente. E o collective.cover aparece na "Configuração do Site -> Complementos". Então alguem que acessar a página de "Complementos" irá ver que existem upgrades steps a serem executados (sem ser necessário acessar a zmi).
