### ISSUE TITLE
Uso do Google Translate

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#172]
A recomendação hoje para portais multilíngue é a criação de um novo portal separado do original.

Uma solução alternativa para evitar a criação de um novo portal só pra isso seria o uso da ferramenta Google Translate, que fornece um widget javascript a ser inserido no portal. Apesar de não ser uma tradução perfeita, o processo é menos oneroso pois não necessita de uma equipe alocada para traduções do conteúdo original (sendo interessante para portais em que as equipes são menores).

Acredito que a inserção dessa funcionalidade hoje no portal (de forma opcional) seria interessante. Assim sendo, pergunto se:

- Vocês acham válida a inserção de uma forma, opcional, do uso do Google Translate no Portal Padrão hoje (por exemplo, mais um item no painel de controle pra colocar o código javascript e a tag meta fornecidas pelo google em https://translate.google.com/manager/website/);
- Sendo válida a inserção, qual seria a melhor seção pra inserir o widget de tradução do Google, refletindo obviamente nos arquivos de template `index.html` e `rules.xml`. Seria no mesmo local onde [hoje temos a div de línguas](https://github.com/plonegovbr/brasil.gov.temas/blob/master/src/brasil/gov/temas/themes/verde/index.html#L63)? Qual seria a melhor forma de adequação ao layout?

Deixo portanto o questionamento acima para discussão.

**Comment by idgserpro** [comment]
Há clientes questionando o andamento dessa discussão. Qual posicionamento pode ser dado a eles? Lembrando que a implementação dessa funcionalidade pode ser efetuado via pull request.

**Comment by hvelarde** [comment]
acho que seria melhor levar essa discussão para a lista da Comunidade Plone no Governo

**Comment by idgserpro** [comment]
Esse relato será fechado uma vez que após discussão na comunidade percebemos as seguintes desvantagens dessa abordagem:

1 - Problemas de acessibilidade;
2 - Riscos de performance em plataformas móveis;
3 - [Riscos do ciclo de vida do Google Translate](https://groups.google.com/forum/#!topic/google-translate-api/TAeCd2naU80).

O caminho deve ser o traçado no #188.
