### ISSUE TITLE
Alterar informações usuários cadastrados

### ISSUE THREAD

**Issue by tomfsa** [plonegovbr/brasil.gov.portal#179]
Prezados,
      Quando o admin tem a necessidade de gerenciar as abas "Informação Pessoal" e "Preferências Pessoais" aparece uma página em branco e os dados não são exibidos. 
     Se o próprio usuário loga no site e acessa estas abas, ele visualiza normalmente.

**Comment by idgserpro** [comment]
A linha problemática é a presente em

https://github.com/plonegovbr/brasil.gov.temas/blob/master/src/brasil/gov/temas/themes/verde/rules.xml#L40

Algum motivo para ao invés de `<replace content="//*[@id='portal-column-content']/div[2]" theme="//*[@id='portal-column-content']/div[1]" />` não ser apenas `<replace css:content="#portal-column-content" css:theme="#portal-column-content" />`, ou seja, sem especificar uma div por posicionamento dessa forma? Acho uma regra dessas por posicionamento mais frágil do que diretamente por id.

Ao @rodfersou, @felipeduardo, @agnogueira e @ericof que mexeram no tema, alguma motivação para essa regra ser dessa forma ou poderia ser alterado como o sugerido?

**Comment by agnogueira** [comment]
Ela foi adicionada neste comit do @felipeduardo: 
https://github.com/plonegovbr/brasil.gov.temas/commit/8137469495f5fbf6ef2955e054822b03ed920d8d
Não achei nenhuma indicação do motivo da alteração.

**Comment by rodfersou** [comment]
Provavelmente foi necessário mudar a posição da primeira div do tema para a segunda div do site dinâmico.. deve ser algo relacionado ao layout dos objetos e comportamento responsivo, para o HTML sair da forma desejada do layout.

Não me lembro agora o motivo exato.. somente debugando a página, e sabendo que elementos são essas divs para poder responder com certeza esta pergunta..

Concordo que isso poderia ser melhor explicado se as divs estivessem com alguma class ou id para identificar ao invés do índice.

**Comment by idgserpro** [comment]
Como isso é um problema de tema, abri o relato no brasil.gov.tema:

https://github.com/plonegovbr/brasil.gov.temas/issues/113
