### ISSUE TITLE
Atualização do Products.Doormat para 1.0

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#182]
@rodfersou, Algum motivo em específico para a pinagem de Products.Doormat em https://github.com/plonegovbr/brasil.gov.portal/commit/9000191ffc55572792642ce6c750c8fe96ffd3e3, além de fazer os testes passarem? Qual teste deu problema?

A versão 1.0 é importante pois leva em consideração o workflow dos itens a serem mostrados no rodapé: isso é útil para portais que utilizam o workflow de intranet para seus conteúdos. A versão 0.7 utilizada hoje em brasil.gov.portal não contempla essa correção pois ela foi efetuada em https://github.com/collective/Products.Doormat/commit/c9255c6297dc30824c2ef86005ce896c0f7f85ff disponível a partir da versão 0.8.

Obs: para essa atualização poder funcionar no IDG é necessário alterar a linha https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/browser/content/doormat.py#L38, assim ao invés `if not isinstance(link_url, str):` fica `if not isinstance(link_url, str) and not isinstance(link_url, unicode):`. Não sei de maiores impactos, daí a abertura do relato.

**Comment by idgserpro** [comment]
Essa demanda será corrigida via pull request.

**Comment by rodfersou** [comment]
@idgserpro Eu acredito que na época as versões mais novas do produto estavam entrando em conflito com algum outro pacote necessário, mas vale a pena fazer um novo teste com a versão mais atual.

**Comment by idgserpro** [comment]
@rodfersou vou verificar isso. Obrigado.

**Comment by rodfersou** [comment]
@idgserpro de nada :)
