### ISSUE TITLE
Funcionalidade baixar galeria de foto

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#187]
No portal do Planalto, há uma funcionalidade para baixar galeria de foto, que não existe no Portal Padrão. Gostaria de saber se esta customização foi feita por alguém aqui da comunidade e se existe uma previsão para essa funcionalidade ser incorporada ao Portal Padrão.

Um exemplo da funcionalidade:

http://www2.planalto.gov.br/centrais-de-conteudos/imagens/visita-ao-alojamento-das-vitimas-das-areas-alagadas

![captura de tela de 2015-03-03 10-32-45](https://cloud.githubusercontent.com/assets/8203476/6618088/4bf4b5c6-c89e-11e4-9bd0-3e2d1a23eb52.png)

**Comment by hvelarde** [comment]
Isso foi feito especificamente para a Secom, vou perguntar se podemos mover o repositório para aqui.

**Comment by ericof** [comment]
Como é algo no namespace da secom eu acho que a única forma seriam eles mesmos autorizarem. Minha sugestão é recriar a funcionalidade com código mais moderno.

**Comment by hvelarde** [comment]
@idgserpro a funcionalidade foi inclusa agora como parte do produto sc.photogallery:

https://github.com/simplesconsultoria/sc.photogallery/pull/16

ainda está precisando dum refactor para tirar código duplicado mas está em produção no novo site dos Jogos Olímpicos; pode ver um exemplo aqui:

http://www.brasil2016.gov.br/pt-br/galeria-de-fotos/vila-dos-atletas-julho-de-2015

**Comment by idgserpro** [comment]
Legal @hvelarde! Existe alguma previsão do sc.photogallery ser incorporado ao IDG, substituindo a galeria utilizada hoje no IDG?

**Comment by hvelarde** [comment]
@idgserpro ninguém pediu ainda isso; pode mandar mensagem na lista? teríamos que discutir como migrar o conteúdo atual.

**Comment by hvelarde** [comment]
o sc.photogallery foi incluso no IDG.
