### ISSUE TITLE
Css de tiles só funcionam para tile de Notícias

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#189]
O [css de tiles](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/profiles/default/registry.xml#L61) só funcionam para a tile de Notícias. Esses csss só são aplicados se o elemento tiver a classe '.tile-subtitle', como visto [aqui](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/static/css/main.css#L1645). E somente a tile de Notícias (do brasil.gov.titles) possui essa classe. No entanto, esses csss podem ser selecioandos em qualquer tile. E na tile de coleção, os [csss](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/static/css/main.css#L1671-L1676), são sobrescritos pelo seletor [#content .cover-collection-tile h2 a] (https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/static/css/main.css#L1386)

**Comment by idgserpro** [comment]
O commit https://github.com/plonegovbr/brasil.gov.portal/commit/6b3001d787fbf0e12c28f59a668986d012bf6fb6 corrigi o css para tile de coleção. Ainda é necessário revisar o css de outras tiles.

**Comment by winstonf88** [comment]
Testei algumas outras tile e me parecem OK

**Comment by winstonf88** [comment]
Podemos fechar?

**Comment by idgserpro** [comment]
Corrigido: https://github.com/plonegovbr/brasil.gov.portal/commit/499fbc3009c8afd418a470e3a3cdd787d4a08931
