### ISSUE TITLE
O upgrade step que ajusta a ordenação de pastas não funciona se a pasta for renomeada

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#190]
O upgrade step [v5000 que ajusta a ordenação de pastas 'assuntos', 'imagens' e 'sobre'](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/upgrades/v5000/handler.py#L17), não funciona se essas pastas forem renomeadas o id. É necessário criar um novo upgrade step que verifica se existem pastas na raiz com a ordenação 'unsorted' (independente do id) e trocar a ordenação desses pastas.

**Comment by idgserpro** [comment]
Isso será resolvido via pull request.

**Comment by hvelarde** [comment]
e testes, por favor...

**Comment by idgserpro** [comment]
Sim, sem dúvida! O teste será criar por exemplo 3 pastas: uma na situação não ordenada, e outras duas ordenadas, execução do upgrade, os 3 precisam estar ordenados.

Acha suficiente ou tem mais alguma idéia para complementar o teste ainda mais?

**Comment by hvelarde** [comment]
@idgserpro estava pensando mais bem em testes do upgrade step para tentar evitar problemas como este.
