### ISSUE TITLE
CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#191]
Quando adicionamos uma Coleção, selecionamos 'Tipo' no campo 'Termos de busca', deixamos o combo 'É' selecionando e marcamos 'Página' no terceiro combo, ocorre o erro abaixo na resposta do javascript:

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.app.querystring.querybuilder, line 58, in html_results
    Module plone.app.querystring.querybuilder, line 49, in __call__
    Module plone.app.querystring.querybuilder, line 116, in _makequery
    Module Products.CMFPlone.CatalogTool, line 393, in searchResults
    Module Products.ZCatalog.ZCatalog, line 604, in searchResults
    Module Products.ZCatalog.Catalog, line 916, in searchResults
    Module Products.ZCatalog.Catalog, line 894, in _getSortIndex

    CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.

**Comment by hvelarde** [comment]
eu acho que isso pode ser um erro do collective.nitf; por favor abrir no repo dele e criar um branch com um teste de RF demostrando o problema.

**Comment by idgserpro** [comment]
@hvelarde verifiquei melhor o problema e reportei aqui:

https://github.com/plone/plone.app.querystring/issues/37

De qualquer forma, o collective.nitf deveria ser corrigido também.

**Comment by winstonf88** [comment]
Alguma conclusão sobre este assunto?

**Comment by idgserpro** [comment]
Existem duas soluções para esse problema:

1. O plone.app.querystring não deve listar índices do tipo ZCTextIndex com campo 'Ordenar' da coleção. ver: https://github.com/plone/plone.app.querystring/issues/37

2. O collective.nitf deve definir o registro ```plone.app.querystring.field.byline``` com
```xml
<value key="sortable">False</value>
```
ver: https://github.com/collective/collective.nitf/issues/121

**Comment by winstonf88** [comment]
Eu acho a primeira opção a mais correta, se esse tipo de índice não pode ser usado nesse contexto então ele não deve ser listado.

**Comment by idgserpro** [comment]
@winstonf88 também acho que o correto é corrigir o plone.app.querystring. Eu não tenho contributor agreement então eu não posso corrigir isso lá. Você pode corrigir isso lá?

**Comment by winstonf88** [comment]
Posso sim, já estou trabalhando nisso.

**Comment by winstonf88** [comment]
@idgserpro depois de olhar melhor o problema, isso deve ser corrigido no collective.nitf mesmo.
Na realidade não tem nada que o plone.app.querystring pode fazer, ele apenas RECEBE valores via request e executa uma consulta no catalog com os parâmetros recebidos, que no caso é um `sort_on='byline'`. 
A minha opinião é que se existe um índice que não pode ser usado como sort_on, ele não deve nem ser listado, o problema é que isso vem do Collection.sortingField, o vocabulary que está sendo usado nesse campo deveria não trazer esta opção. Porém, olhando por outro lado, o registro do índice byline está dizendo que ele é sortable então isso tbm pode não ser entendido como um bug do vocabulary. Acho mais fácil/rápido alterar as configurações do índice.

**Comment by winstonf88** [comment]
@idgserpro @hvelarde 
Nesse caso o certo seria só desabilitar o sortable, ou alterar o tipo do índice para funcionar com sort_on?

**Comment by idgserpro** [comment]
@winstonf88 eu ainda acho que o plone.app.querystring deveria ser corrigido. O método [mapSortableIndexes](https://github.com/plone/plone.app.querystring/blob/010d0fa799413d375b864640d1e125f88deee7b5/plone/app/querystring/registryreader.py#L103) define quais índices serão listados no campo 'Ordenar'. Minha ideia é testar nesse método se o indicie é do tipo ZCTextIndex e não retornar esse indicie se for.

**Comment by hvelarde** [comment]
na minha ideia o tipo de índice está certo: `ZCTextIndex` se usa para buscas de texto completo, ou seja, eu poderia procurar por *Jorge* e a busca retornar artigos escritos tanto por *Jorge Bem*, quanto por *Seu Jorge*...

**Comment by idgserpro** [comment]
Sim @hvelarde, o tipo de índice está correto. O que não está correto é o plone.app.querystring listá-lo com campo 'Ordenar' da Coleção.

**Comment by winstonf88** [comment]
Já mandei a correção desse item no https://github.com/plone/plone.app.querystring/pull/43

**Comment by idgserpro** [comment]
Corrigido no plone.app.querystring:
https://github.com/plone/plone.app.querystring/issues/37

Agora falta esperar um novo release para que possamos incorporá-lo ao IDG, para fecharmos esse relato.
Obrigado @winstonf88 pela correção!

**Comment by idgserpro** [comment]
@hvelarde saiu um [release do branch 1.3.x](https://github.com/plone/plone.app.querystring/blob/master/CHANGES.rst#138-2015-09-21) do plone.app.querystring com as correções do @winstonf88 mas não saiu uma [release do branch 1.2.x](https://github.com/plone/plone.app.querystring/blob/1.2.x/CHANGES.rst#128-unreleased), que é a utlizada no Plone 4.3. Será que podemos utilizar a versão 1.3 ou teremos que esperar um release da 1.2?

**Comment by hvelarde** [comment]
não podemos, não; estou solicitando um release agora no #plone-framework

**Comment by hvelarde** [comment]
feito! https://pypi.python.org/pypi/plone.app.querystring/1.2.8

**Comment by idgserpro** [comment]
@hvelarde maravilha! Agora temos que adicionar esse versão em portalpadrao.release. Obrigado!

**Comment by winstonf88** [comment]
Podemos fechar?

**Comment by idgserpro** [comment]
@winstonf88 ainda temos que testar a [versão 1.2.8 do plone.app.querystring](https://pypi.python.org/pypi/plone.app.querystring/1.2.8) com o IDG e atualizar o https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg

**Comment by winstonf88** [comment]
@idgserpro o plone.app.querystring já está na versão 1.3.12, podemos usar esta versão?

**Comment by hvelarde** [comment]
@winstonf88 não pode, não; esse branch é para Plone 5.

**Comment by winstonf88** [comment]
@idgserpro @hvelarde fiz testes com o plone.app.querystring 1.2.9 e está OK.
Posso atualizar o https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg?

**Comment by hvelarde** [comment]
pode sim
