### ISSUE TITLE
Fix blind excepts

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#196]

**Comment by secomdigital** [comment]
Orientamos a respeito da necessidade de maior detalhamento da inclusão desta demanda na nova Release.

**Comment by hvelarde** [comment]
@secomdigital ninguém falou em incluir essa demanda no próximo release; simplesmente é um problema que deve ser resolvido em algum momento.

**Comment by secomdigital** [comment]
@hvelarde ainda não identificamos o problema. Poderia por favor descrever com mais detalhes?

**Comment by hvelarde** [comment]
[esse código aqui](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/transmogrifier/sections/source.py#L30:L34) é uma má prática:

```python
        try:
            path = '%s/%s' % (directory, data_file)
            data = json.loads(open(path, 'r').read())
        except Exception:
            data = {}
```

mais informação aqui:
* https://docs.python.org/2.7/howto/doanddont.html#except
* http://stackoverflow.com/questions/21553327/why-is-except-pass-a-bad-programming-practice
