### ISSUE TITLE
Desvincular exibição da data da exibição do autor

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#202]
Hoje, quando desmarcamos a opção 'Permitir a qualquer um ver as informações sobre o conteúdo.' em 'Configuração do site -> Segurança', tanto a data quanto o autor de um conteúdo deixam de ser exibido para anônimos. A ideia aqui é desvincular esse comportamento para que seja exibido somente a data ou somente o autor. O que vocês acham?

**Comment by hvelarde** [comment]
@idgserpro eu acho legal, mas isso deve ser implementado no Plone direitamente e não aqui

**Comment by idgserpro** [comment]
@hvelarde nós até abrimos o relato no Plone:

https://github.com/plone/Products.CMFPlone/issues/668

Mas há dois pontos aqui:

- Ainda estamos no processo para assinar o Contributor's Agreement. Então, não podemos implementar isso.
- Mesmo que isso seja implementado no Plone, provavelmente só sairia no Plone 5 e demoraria muito para o IDG usar isso.

Então, não podemos implementar aqui e remover quando a funcionalidade sair no Plone?

**Comment by hvelarde** [comment]
acho que podem implementar aqui e depois abrir issues nos branchs 4.3 e 5.0 do Plone; não vejo por que não possa ser incluído agora na versão 4.3.

**Comment by idgserpro** [comment]
@hvelarde como esse assunto não está indefinido no Plone, vou implementar isso aqui. Vou criar um novo item no control panel para configurações do brasil.gov.portal, e colocar a configuração de esconder o autor lá.

**Comment by idgserpro** [comment]
Estou implementando essa issue e me deparei com o problema de que muitos templates listam a data e o autor. Eu teria que customizar esses templates para implementar essa issue. Então estou me perguntando se não seria melhor implementar isso com o diazo no brasil.gov.temas. Regras de diazo são mais frágeis do que fazer nos templates e tem problema de performance. Mas eu não teria que customizar os templates. Qual seria a melhor solução? Opiniões?

**Comment by idgserpro** [comment]
Fazer no diazo também é conceitualmente errado, uma vez que estaria colocando regra de negócio em um produto de tema.

**Comment by caduvieira** [comment]
A perda na performance é grande se usado no diazo?

**Comment by idgserpro** [comment]
@caduvieira como o portal já está utilizando Diazo, creio que não perderá muita performance em relação a hoje. Mas serão mais regras para processar. Mas o que mais acho errado em fazer com diazo, é colocar regras de negócio em um produto de tema.

**Comment by winstonf88** [comment]
isto pode ser fechado?

**Comment by idgserpro** [comment]
@winstonf88 eu já corrigir isso no commit https://github.com/plonegovbr/brasil.gov.portal/commit/cfd6c7847021686b2ba07b3742c6a2f01f15a3e5. No entanto, ainda na abri um PR porque os testes estão falhando ver: https://github.com/plonegovbr/brasil.gov.portal/issues/241

**Comment by hvelarde** [comment]
eu ainda acho importante criar um PR no Plone 5 para isso.
