### ISSUE TITLE
Ícone de Redes Sociais cortados

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#203]
Em tipos de conteúdos diferente de Notícias (por exemplo em Páginas), os ícones de Redes Sociais ficam cortados.

![redes sociais](https://cloud.githubusercontent.com/assets/8203476/8704464/7ca17e8a-2af9-11e5-9954-f45917a49536.png)

**Comment by winstonf88** [comment]
Este problema não persiste mais.

**Comment by idgserpro** [comment]
Ainda não podemos fechar. O problema ainda ocorre.

![selecao_027](https://cloud.githubusercontent.com/assets/8203476/11779144/6cc38eb8-a240-11e5-938d-f17df22d0914.png)

**Comment by winstonf88** [comment]
Aqui está sendo exibido normal. ( conteúdo é uma página )

![image](https://cloud.githubusercontent.com/assets/1376143/11781939/b5c31502-a254-11e5-9605-c7e0e25f9eb8.png)

**Comment by idgserpro** [comment]
@winstonf88 veja que no meu caso está sendo mostrado a data da publicação e a data de modificação. No seu caso só está sendo mostrado a data de modificação. Você está com alguma configuração diferente.

**Comment by winstonf88** [comment]
Corrigido!
![image](https://cloud.githubusercontent.com/assets/1376143/11791477/6617f430-a288-11e5-96e3-c634349c8452.png)
