### ISSUE TITLE
Atualizar versão do collective.cover para 1.0a11

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#206]
Testar e atualizar a versão do collective.cover [1.0a11](https://pypi.python.org/pypi/collective.cover/1.0a11). Segundo o @hvelarde esse versão está estável.

**Comment by idgserpro** [comment]
Relacionado com https://github.com/plonegovbr/brasil.gov.portal/issues/216

**Comment by idgserpro** [comment]
@rodfersou @hvelarde podemos fechar esse relato?

**Comment by hvelarde** [comment]
acho que podemos sim:

https://travis-ci.org/plonegovbr/brasil.gov.portal/builds/79508359#L558
