### ISSUE TITLE
Há interesse de, no próximo release, atualizar o Products.TinyMCE em portalpadrao.release?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#208]
Hoje, a versão pinada desse pacote em portalpadrao.release é a 1.3.6.

A versão [1.3.10 de Products.TinyMCE](https://github.com/plone/Products.TinyMCE/blob/1.3.x/HISTORY.rst) conserta traduções faltantes em português. Ela corrige o problema por exemplo de propriedades de links no editor TinyMCE que estavam em branco:

![selecao_067](https://cloud.githubusercontent.com/assets/8203476/9062616/e77d365e-3a99-11e5-8759-757120802fdd.png)

No Plone 4.3.6, a versão pinada passa [a ser a 1.3.9](https://plone.org/products/plone/releases/4.3.5), que não contempla esse bug. 

Pergunto: a versão do TinyMCE no novo release do Portal Padrão 1.0.6 será 1.3.9 (para seguir o release do Plone) ou a 1.3.10 (para consertar esse erro já que ele atinge todo mundo que usa o Portal Padrão)?

**Comment by hvelarde** [comment]
@idgserpro acho que podemos ir além disso.

@rodfersou qual é a última versão que temos testado em produção no Plone 4.3?

**Comment by rodfersou** [comment]
@idgserpro @hvelarde versão 1.4.3 entrou minha correção das traduções https://pypi.python.org/pypi/Products.TinyMCE/1.4.3

**Comment by idgserpro** [comment]
@hvelarde @rodfersou Então há interesse de incorporar Products.TinyMCE>=1.3.10 no Portal Padrão, de qualquer forma? Se já estiver definido, esse relato pode ser fechado. Obrigado!

**Comment by hvelarde** [comment]
@idgserpro ha sim

**Comment by idgserpro** [comment]
@hvelarde Pra conhecimento.

**Comment by idgserpro** [comment]
@winstonf88 o relato sobre o TinyMCE que falamos por telefone é esse.
