### ISSUE TITLE
Erro página destaque do produto brasil.gov.portal

### ISSUE THREAD

**Issue by lucaslamounier** [plonegovbr/brasil.gov.portal#211]
Após realizar a instalação do portal padrão em uma nova instancia do plone o produto apresenta o seguinte erro :  

Module collective.cover.layout, line 99, in render_section
TypeError: cannot concatenate 'str' and 'dict' objects

 - Expression: "layout/render_view"
 - Filename:   ... a11-py2.7.egg/collective/cover/browser/templates/view.pt
 - Location:   (line 18: col 32)
 - Source:     tal:replace="structure layout/render_view" />
                                      ^^^^^^^^^^^^^^^^^^
 - Expression: "python:view.render_section(child, mode)"
 - Filename:   ... a11-py2.7.egg/collective/cover/layout_templates/group.pt
 - Location:   (line 34: col 56)
 - Source:     ... ce="structure python:view.render_section(child, mode)" />
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               context: <ImplicitAcquisitionWrapper destaques at 0xe0f3824>
               views: <ViewMapper - at 0xb3f2a3ccL>
               modules: <TraversableModuleImporter - at 0x9bcb24c>
               args: <tuple - at 0xb773002cL>
               child: {...} (4)
               nothing: <NoneType - at 0x4762c3cc>
               target_language: <NoneType - at 0x4762c3cc>
               loop: {...} (1)
               default: <object - at 0xb774f6e8L>
               section: {...} (5)
               request: <instance - at 0xe3a49ac>
               wrapped_repeat: {...} (1)
               mode: view
               template: <ViewPageTemplateFile - at 0xdfb810c>
               translate: <function translate at 0xb44cbed4L>
               options: {...} (2)
               view: <PageLayout layout at 0xb4117dccL>

Ja realizei diversas instalações, para tentar corrigir o problema porém o mesmo ainda ocorre, a instalação foi feita através do buildout em uma instalação standalone.

**Comment by hvelarde** [comment]
@lucaslamounier o collective.cover 1.0a11 não tem sido homologado para trabalhar com a versão atual do IDGB.

imagino que você seguiu as instruções de instalação do pacote e colocou as versões certas de dependências.

**Comment by winstonf88** [comment]
@hvelarde segundo o @lucaslamounier esse problema acontece somente ao instalar o brasil.gov.portal a partir de uma instalação padrão do Plone (unifiedinstaller). Este erro não acontece quando o produto é instalado a partir de uma instalação do Portal Padrão.

**Comment by hvelarde** [comment]
@winstonf88 @lucaslamounier o brasil.gov.portal tem dependências estritas que devem ser satisfeitas; para isso se usa o arquivo versions.cfg.

**Comment by idgserpro** [comment]
Cada versão do Portal Padrão tem o seu arquivo de versões para as dependências. O arquivo da atual versão (1.0.5) é esse:

https://raw.githubusercontent.com/plonegovbr/portalpadrao.release/master/1.0.5/versions.cfg

Você tem que estender o seu buildout com a url acima.

**Comment by idgserpro** [comment]
Corrigido em https://github.com/plonegovbr/brasil.gov.portal/commit/9dbcfaed531823ecea41d4dc06d782b04c1adcaf.
