### ISSUE TITLE
Corrigir conteúdo inicial: "TypeError: cannot concatenate 'str' and 'dict' objects" para tiles antigos que continham dicionário

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.portal#216]
Após atualização do `collective.cover`, um problema que estava escondido na estrutura do conteúdo inicial fez com que disparasse [algumas exceções](https://github.com/collective/collective.cover/issues/544).

Nesta issue será necessário:
- Atualizar a estrutura do conteúdo inicial do `brasil.gov.portal`.
- Criar um upgrade step para limpar os tiles antigos.

**Comment by hvelarde** [comment]
@winstonf88 FYI

**Comment by idgserpro** [comment]
Esse relato foi corrigido erroneamente.

No commit https://github.com/plonegovbr/brasil.gov.portal/commit/9dbcfaed531823ecea41d4dc06d782b04c1adcaf#diff-8fcde383ff1fa08c327c22ae1bd14efdR55, o teste verifica se a css_class é diferente de str ou se é --NOVALUE--, mas classes também vêm como unicode e são assim erroneamente removidas. O `if` ficaria melhor se perguntasse pelos valores realmente problemáticos (dict e --NOVALUE-- por exemplo) e só limpar nessas condições.

Assim, se eu atualizo um IDG versão 1.0.5 para 1.1.4, a capa fica assim:

![selecao_230](https://cloud.githubusercontent.com/assets/8203476/19982632/f552a144-a1ed-11e6-97e2-35051a727741.png)

Quando deveria ficar assim:

![selecao_229](https://cloud.githubusercontent.com/assets/8203476/19982500/7481fb00-a1ed-11e6-95a9-828dbdff0f9a.png)

Portanto, estou reabrindo esse relato.
