### ISSUE TITLE
Criar upgrade step para atualizar produtos de terceiros

### ISSUE THREAD

**Issue by winstonf88** [plonegovbr/brasil.gov.portal#218]
Como vários produtos foram atualizados é necessário executar todos os upgrade steps dos mesmos.
Para evitar rodar todos manualmente, deve criar um upgrade step que faça esta atualização.

**Comment by idgserpro** [comment]
É importante uma discussão ampla sobre uma demanda desse nível devido aos problemas/características no funcionamento dos upgradeSteps que, na nossa opinião, torna a necessidade da aplicação deles ainda ser manual:

1 - Da forma como os upgradeSteps hoje são implementados em Plone, não dá pra saber se um upgradeStep em específico foi executado ou não pelo portal_setup. Ex: se você tem um pacote com 6 upgradeSteps, e executa do 4o pro 6o por exemplo, não dá pra saber se o 1o, o 2o e o 3o foram executados porque o que vai aparecer como última versão no portal_setup é o 6o (mesmo sem executar o 1o o 2o e o 3o). A única forma de garantir se um upgradeStep foi executado ou não seria testando o *comportamento esperado* após a execução dele;
2 - A lógica de "source" e "destination" não são números sequenciais e sim qualquer string arbitrária que tiver sido definida por profile em metadata.xml. Se é um pacote onde você tem total controle e tenta seguir uma lógica sequencial (que é o nosso caso em brasil.gov.portal, veja que o nosso último upgrade é 10700, e mesmo assim ainda causa confusão), é até possível tentar ir pra esse caminho de automatização de upgrades, mas tratar via código toda e qualquer exceção e lógica de "source" e "destination" de todas as dependências é algo trabalhoso a ponto de não valer a pena. Um ex: [Products.TinyMCE](https://github.com/plone/Products.TinyMCE/blob/master/Products/TinyMCE/profiles.zcml) começou em 1.0 pra 1.1, depois pra 2,3,4,5,6,7. Quem não garante que agora vão fazer um 7.2? Ou 7a?
3 - Se algum upgradeStep estiver com erro, podem pensar que o erro é no brasil.gov.portal e teremos criações de relatos desnecessários;
4 - Tudo será feito numa transação apenas, e, se um upgradeStep em tese "indolor" (desregistrar um javascript por exemplo) der problema ele impedirá que upgradeSteps críticos (como correção do collective.cover que quebra uma capa) sejam executados. É até possível uma loǵica de savepoints mas a complexidade de manutenção disso não vale a pena.

Se, mesmo com essas deficiências, decidirmos ir por esse caminho, o que poderia ser feito é só aplicar o upgradeStep da dependência *apenas* se o último aplicado tiver sido a versão "x", que era o que estávamos esperando: qualquer outra versão que estiver no upgradeStep que não seja a "x", o upgradeStep não será executado. Podemos logar isso ou mesmo lançar uma exceção, indicando ao usuário que ele precisa atualizar os passos, pelo menos até o "x". Será necessária uma estrutura de dados mapeando dependências e quais versões finais de upgradeSteps estamos esperando (um dicionário, talvez?). Seriam necessários testes, no seu brasil.gov.portal, testando se **todos** upgradeSteps de **todas** as dependências foram executados com sucesso: se o brasil.gov.portal decidiu atualizar todas as dependências, ele passa a ter a responsabilidade de garantir a consistência de todas as instalações. É uma complexidade e tanto.

Acho que enquanto essa discussão não amadurecer (se é que vai amadurecer), podemos indicar, via README, os upgradeSteps críticos que devem ser executados após o lançamento de releases, como é o caso do collective.cover.

**Comment by hvelarde** [comment]
@idgserpro bom pontos, mas… o que estamos tentando fazer aqui é simplificar a vida dos usuários finais; o Plone mesmo já faz isso quando você atualiza de versao em versão.

acho muito mais saudável automatizar a execução dos upgrade steps das dependências básicas do IDGB que deixar isso nas mão de usuário poco experientes que as vezes esquecem de aplicar alguns deles.

escreve na lista e vamos ver o que a galera opina.

**Comment by idgserpro** [comment]
O mundo ideal é sim atualizar todas as dependências simplificando a vida dos usuários finais, a questão é a mão de obra, recursos e o overhead disso no código para poder garantir essa simplificação, que, ao menos na nossa análise, não achamos que valha a pena no nosso contexto devido à complexidade, tamanho de equipe e às desvantagens citadas. Se quiserem seguir por esse caminho mesmo com as desvantagens citadas, não vemos problema.

É importante lembrar que, se o brasil.gov.portal decidir ir por esse caminho, precisará revisar desde o release 1.0 de brasil.gov.portal e todas as suas dependências até o release atual analisando como automatizar e aplicar todos os upgradeSteps desenvolvidos nesse interim. Antes de lançar cada novo release, será necessário revisar todas as dependências, verificando quais tem upgradeSteps e quais ainda não foram automatizados para execução para entrar no mapeamento, e testes para esses novos upgradeSteps que forem automatizados: lembrando que uma dependência pode ter outras dependências. Se não for feito dessa forma caímos no problema 1.

**Comment by hvelarde** [comment]
@idgserpro vamos ver, acho que a situação não é assim como vocês comentam; na minha opinião o que acontece é o seguinte: se o usuário Fulano vai atualizar para a nova versão do portal e antes ele não rodou alguns upgrade steps de alguns pacotes, ao atualizar o código vai rodar todos os upgrade steps pendentes ate a versão indicada aqui.

se o usuário pulou algum upgrade step intermediário então nem ele nem nos temos jeito de saber e o portal vai finalizar quebrado, mas isso ia acontecer de qualquer jeito.

o que eu vou sugerir é o seguinte, vamos anunciar na lista de correios que isso está se fazendo para as pessoas testarem em ambientes de homologação antes de finalizar o release.

esse é o único jeito de saber se estamos ou não com algum problema, concordam?

o único que nós podemos fazer é pegar releases desde o 1.0 ate o 1.0.5 e testar que a atualização até a nova versão roda sem problemas. isso não é tão complicado e não vai demorar muito se vocês nos ajudam.

**Comment by winstonf88** [comment]
+1

**Comment by idgserpro** [comment]
Acredito que o ideal nesse cenário, já que a motivação pra facilitar pro usuário final, é:

- Varrer o portal_setup dos ambientes, verificar os pacotes que temos de dependência que possuem upgradeSteps não aplicados;
- Aplicar esses upgradeSteps automaticamente;
- Próximo release, aplicar os upgradeSteps de forma específica e explícita como foi feito inicialmente no https://github.com/plonegovbr/brasil.gov.portal/pull/219

**Comment by hvelarde** [comment]
concordo, mas só das dependências do projeto.

**Comment by idgserpro** [comment]
Eu também, complementei a mensagem deixando isso explícito pra não gerar dúvidas!

**Comment by idgserpro** [comment]
@hvelarde @winstonf88 como vamos tratar as dependências das dependências. Por exemplo, o ```collective.cover``` tem como dependência o ```collective.js.jqueryui``` e o ```collective.js.jqueryui``` pode ter upgrade para executar. Inclusive o collective.js.jqueryui tem um [upgrade errado](https://github.com/collective/collective.js.jqueryui/issues/28).

**Comment by hvelarde** [comment]
@idgserpro simplesmente: não vamos tratar :-)

**Comment by idgserpro** [comment]
O problema de não tratarmos é que faremos todo esse esforço no código, testes e etc mas o usuário ainda precisa ir no portal_setup: acabou que fugimos da motivação inicial que você comentou que era de não deixar na mão de usuários pouco experientes que às vezes esquecem de aplicar alguns deles, já que ele ainda precisa aplicar manualmente.

Por isso, pergunto: não tratará nesse release, ou simplesmente não será tratado?

**Comment by winstonf88** [comment]
@idgserpro Entendo a sua colocação e é válida. Porém é complicado resolver 100% do problema pq A tem dependência de B, que tem dependência de C, que tem dependência de D, e etc. E isso é inviável, acho melhor fazermos o mínimo do que não fazer nada, fazendo com que o brasil.gov.portal resolva as SUAS dependências, não a dos "outros".
