### ISSUE TITLE
Capa desformatada

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#221]
Ao criar um portal 'do zero', a capa fica desformatada:

![idg](https://cloud.githubusercontent.com/assets/8203476/9816778/734ec80c-5875-11e5-8e89-f897ff8c2beb.png)

Provavelmente isso foi depois de https://github.com/plonegovbr/brasil.gov.portal/commit/9dbcfaed531823ecea41d4dc06d782b04c1adcaf.

@rodfersou você pode verificar?

**Comment by rodfersou** [comment]
Precisa instalar os upgrade steps do `collective.cover`

**Comment by idgserpro** [comment]
@rodfersou mas isso ocorre ao instalar um Plone Site 'do zero'. Existem upgrade step  do collective.cover para serem instalados quando criamos um site 'do zero'?

**Comment by rodfersou** [comment]
@idgserpro esse é um dos motivos de re-fazer o conteúdo inicial :) #220

**Comment by winstonf88** [comment]
@rodfersou Eu alterei o json do "home/data.json" para resolver o problema. Não sei se é a solução correta, pode dar uma olhada?

Eu só alterei os dados de:
```python
[
  {
    "type": "row",
    "children": [
      {
        "type": "group", 
        "data": {"layout-type": "column", "column-size": 15}, 
        "children": [
          {"tile-type": "standaloneheader", "type": "tile", "id": "ca9b0f6d474f43c48750437e2df703d1"},
          {"tile-type": "nitf", "type": "tile", "id": "d7a49b957d224a859a523d27794239fd"}
        ], 
        "roles": ["Manager"]
      }
    ]
  }
]
```
para 
```python
[
  {
    "type": "row",
    "children": [
      {
        "type": "group", 
        "column-size": 15,
        "children": [
          {"tile-type": "standaloneheader", "type": "tile", "id": "ca9b0f6d474f43c48750437e2df703d1"},
          {"tile-type": "nitf", "type": "tile", "id": "d7a49b957d224a859a523d27794239fd"}
        ], 
        "roles": ["Manager"]
      }
    ]
  }
]
```

**Comment by rodfersou** [comment]
@winstonf88 desculpe a demora.. revisei o meu [upgrade step do cover](https://github.com/collective/collective.cover/blob/master/src/collective/cover/upgrades/v11/__init__.py#L144-L145), e sua alteração está correta. basicamente faltava mudar o column-size do atributo data para a posição acima
