### ISSUE TITLE
KeyError: 'Interface `collective.cover.controlpanel.ICoverSettings` defines a field `grid_system`, for which there is no record.' 

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#225]
Criei um Portal Padrão 1.0.5 com as versões indicadas em:
https://github.com/plonegovbr/portalpadrao.release/blob/master/1.0.5/versions.cfg

Depois atualizei para Portal Padrão 1.1.2, adicionando as versões de:
https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg

Ao executar o upgrade step do brasil.gov.portal, ocorreu o erro:

```bash
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.CMFCore.FSPythonScript, line 127, in __call__
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.PythonScripts.PythonScript, line 344, in _exec
    Module script, line 11, in prefs_reinstallProducts
    <FSPythonScript at /atualiza/portal_quickinstaller/prefs_reinstallProducts>
    Line 11
    Module Products.CMFPlone.QuickInstallerTool, line 101, in upgradeProduct
    Module Products.GenericSetup.upgrade, line 140, in doStep
    Module brasil.gov.portal.upgrades.v10700.handler, line 124, in corrige_conteudo_collectivecover
    Module plone.registry.registry, line 74, in forInterface

KeyError: 'Interface `collective.cover.controlpanel.ICoverSettings` defines a field `grid_system`, for which there is no record.' 
```

Para corrigir isso, no upgrade step do brasil.gov.portal, o passo que executa o upgrade do collective.cover, deve ser executado antes do passo que corrigi o conteúdo do collective.cover.

**Comment by winstonf88** [comment]
Pode estar relacionado com #226

**Comment by idgserpro** [comment]
@winstonf88 não está relacionado com #226. O problema aqui é a ordem dos passos do upgrade do brasil.gov.portal.

**Comment by winstonf88** [comment]
@idgserpro fiz alguns testes e o problema aqui na realidade é que o upgrade do collective.cover deve ser executado antes do [corrige_conteudo_collectivecover](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/bras@idgserpro fiz alguns testes e o problema aqui na realidade é que o upgrade do collective.cover deve ser executado antes do [corrige_conteudo_collectivecover](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/upgrades/v10700/handler.py#L117). Usando o [upgrade_profile](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/upgrades/v10700/handler.py#L117) no início dessa função resolve o problema.
