### ISSUE TITLE
Revisar customização do collective.nitf

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.portal#23]
Esta alteração deve ser feita somente quando sair um release do collective.nitf após remoção do Grok.

**Comment by idgserpro** [comment]
@hvelarde, esse relato diz respeito à customização em https://github.com/plonegovbr/brasil.gov.portal/commit/d3e09277a916a85e4bfc1105fcd6843db745a777, que hoje já está presente no collective.nitf (ver https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/browser/__init__.py#L98)? Se for o caso, devemos renomear o relato para "remover" ao invés de revisar.

**Comment by hvelarde** [comment]
@idgserpro você está olhando no master que é a versão 2.0 do pacote; por favor olha no branch 1.x.

**Comment by idgserpro** [comment]
Mas o ideal não seria já incorporar o 2.0 do nitf num próximo release do brasil.gov.portal?

**Comment by hvelarde** [comment]
@idgserpro estamos trabalhando nele mas ainda não temos data para o release; deve ser nas próximas semanas pois precisamos dele em vários projetos.

podem nos ajudar testando a migração e reportando problemas? sugestões são sempre bem-vindas.

**Comment by idgserpro** [comment]
@rodfersou saberia explicar melhor a motivação desse relato após termos [incorporado collective.nitf 2.x no IDG](https://github.com/plonegovbr/brasil.gov.portal/blob/d9e2fa591d2f57fe89fa5edde33511b5ea9d576a/setup.py#L62)?

**Comment by hvelarde** [comment]
acho que não é mais válido.
