### ISSUE TITLE
Erro no upgrade do collective.nitf

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#231]
Quando executamos o upgrade step 10700 do brasil.gov.portal, ocorre erro no upgrade step 1008 do collective.nitf.

```bash
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.CMFCore.FSPythonScript, line 127, in __call__
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.PythonScripts.PythonScript, line 344, in _exec
    Module script, line 11, in prefs_reinstallProducts
    <FSPythonScript at /Plone/portal_quickinstaller/prefs_reinstallProducts>
    Line 11
    Module Products.CMFPlone.QuickInstallerTool, line 101, in upgradeProduct
    Module Products.GenericSetup.upgrade, line 140, in doStep
    Module brasil.gov.portal.upgrades.v10700.handler, line 34, in atualiza_produtos_terceiros
    Module brasil.gov.portal.upgrades, line 18, in upgrade_profile
    Module Products.GenericSetup.upgrade, line 140, in doStep
    Module collective.nitf.upgrades.v1008, line 15, in fix_collections

AttributeError: getRawQuery 
```

Relacionado com: https://github.com/collective/collective.nitf/issues/139

**Comment by idgserpro** [comment]
@hvelarde o relato https://github.com/collective/collective.nitf/issues/139 foi fechado. Você pode gerar um novo release e atualizar  https://github.com/plonegovbr/portalpadrao.release para fecharmos esse relato?

**Comment by hvelarde** [comment]
posso sim, mas a internet está ruim hoje por aqui; vou tentar mais tarde.

**Comment by hvelarde** [comment]
feito! https://pypi.python.org/pypi/collective.nitf/1.0b6

**Comment by idgserpro** [comment]
@winstonf88 ainda temos que atualizar a versão 1.0b6 do collective.nitf em https://github.com/plonegovbr/portalpadrao.release

**Comment by hvelarde** [comment]
feito aqui: https://github.com/plonegovbr/portalpadrao.release/commit/9e443c1c295b8c12adbcadebeb376ea6c2fc2170

**Comment by idgserpro** [comment]
O upgrade step funcionou. No entanto, após o upgrade o collective.nitf aparece assim em Complementos:

![selecao_022](https://cloud.githubusercontent.com/assets/8203476/10203997/a91daa74-678f-11e5-84de-696d629feed8.png)

@hvelarde @rodfersou isso pode ser um problema?

**Comment by hvelarde** [comment]
isso foi que esquecimos de alguma coisa; @rodfersou pode olhar?

**Comment by winstonf88** [comment]
O que estou achando estranho é a versão estar no nome do complemento, não deveria estar só "collective.nitf" em vez de "collective.nitf:v10008" ?

**Comment by idgserpro** [comment]
@winstonf88 na verdade aparecem as duas coisas:

![selecao_023](https://cloud.githubusercontent.com/assets/8203476/10204367/b801d040-6791-11e5-8b1a-f013113db27e.png)

**Comment by idgserpro** [comment]
Eu acho que o padrão do Plone é assim mesmo (mostra o produto e o upgrade step) alguns produtos é que escondem os upgrade step.

**Comment by hvelarde** [comment]
temos que esconder esse upgrade step, sim; mas acho que podemos deixar pra lá por enquanto para não atrasar mais o release.

@idgserpro abre um issue no collective.nitf; alias, vou gerar já o release 2.0a1 para irmos testando.

**Comment by winstonf88** [comment]
Podemos fechar?
