### ISSUE TITLE
Incorporar hotfix 20150910 do Plone

### ISSUE THREAD

**Issue by taniaa** [plonegovbr/brasil.gov.portal#232]
Oi, pessoal.

Parabéns pelo trabalho da última release!

Notei hoje que a release foi lançada sem a atualização de segurança:
https://plone.org/products/plone/security/advisories/20150910-announcement

O mais breve possível, é importante gerar nova release com isso. Mesmo que boa parte dos sites governamentais não utilizem o registro anônimo, se usar corre riscos identificados :)

**Comment by hvelarde** [comment]
obrigado!
