### ISSUE TITLE
Upgrade step que instala upgrade step de dependências não instala todos os upgrade step de uma depência

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#236]
Ao atualizar o collective.nift de 1.0b3 para 1.0b6, dois upgrade steps precisam ser executados. O [v1007](https://github.com/collective/collective.nitf/tree/1.0b6/src/collective/nitf/upgrades/v1007) e o [v1008](https://github.com/collective/collective.nitf/tree/1.0b6/src/collective/nitf/upgrades/v1007). No entanto, ao executar o upgrade step do brasil.gov.portal que [instala upgrades de dependências](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/upgrades/v10700/handler.py#L20), somente o v1008 do collective.nitf foi instalado. O v1007 não foi instalado.

Isso pode ocorrer com outros pacotes também.

**Comment by hvelarde** [comment]
acho que está enganado, @idgserpro; o upgrade step 1007 não se mostra porque está explicitamente oculto no código:

https://github.com/collective/collective.nitf/blob/1.x/src/collective/nitf/setuphandlers.py#L22

na verdade a gente precisa consertar isso ai, porque foi mal feito; pode ver no master como deveria ser:

https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/setuphandlers.py#L11:L33

**Comment by idgserpro** [comment]
@hvelarde na verdade ele não esconde:

![secretaria de comunicacao social](https://cloud.githubusercontent.com/assets/8203476/10223389/215aaf2e-682f-11e5-9a66-5e38b7223ba5.png)

**Comment by hvelarde** [comment]
pois é, está mal feito como comentei acima; temos que copiar o código do master branch.

**Comment by winstonf88** [comment]
Já enviei a correção deste problema aqui [collective.nitf](https://github.com/collective/collective.nitf/pull/144)

**Comment by idgserpro** [comment]
@hvelarde @winstonf88 independente do upgrade step v1007 ser mostrado ou não, ele não é instalado e deveria ser instalado. Ver na imagem acima que ele aparece em 'Complementos disponíveis'. Ou seja, ele não foi executando quando rodei o upgrade do brasil.gov.portal.

**Comment by hvelarde** [comment]
@idgserpro um upgrade step nunca é "instalado"; ele simplesmente roda e atualiza a versão do profile. por isso os profiles listados nos upgrade steps sempre devem ser ocultos; não faz o menor sentido eles se mostrarem lá, é uma consequência das duas formas que tem o Plone de instalar add-ons.

**Comment by idgserpro** [comment]
@hvelarde você tem razão. Apesar dele aparecer como 'não instalado', ele é executado. De qualquer forma, é estranho o v1007 aparecer em 'Complementos disponíveis'.  O v1008 por exemplo, aparece em 'Complementos ativados'. Ou seja, não seguiu um padrão.

**Comment by winstonf88** [comment]
Podemos
