### ISSUE TITLE
BuscaAtiva (livesearch) não funciona

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#237]
Com a [customização da tela de busca](https://github.com/plonegovbr/brasil.gov.portal/blob/ad5e3a732efe4e5960ca6e7f8f91c6934adb9185/src/brasil/gov/portal/browser/busca/busca.py), o recurso de BuscaAtiva, presente em "Buscar" no painel de controle, simplesmente não funciona ao ser ativado.

Isso ocorre porque o arquivo [livesearch.js](https://github.com/plone/Products.CMFPlone/blob/55c5d6730fd9192593c1de3af7ed13a1b2c0568f/Products/CMFPlone/skins/plone_ecmascript/livesearch.js#L32) espera um action de nome `@@search` para poder efetuar a requisição corretamente mas no brasil.gov.portal temos [`@@busca`](https://github.com/plonegovbr/brasil.gov.portal/blob/1c3159029a67e7b56d82de1f41caaec6d2715330/src/brasil/gov/portal/browser/busca/templates/search.pt#L37): dessa forma, a requisição que deveria ser `livesearch_reply?q=query` acaba ficando como `@@buscalivesearch_reply?q=query`, dando erro.

A partir do Plone 4.3.4, há uma [tentativa de desvincular a necessidade da string do action ser obrigatoriamente `@@search`](https://github.com/plone/Products.CMFPlone/commit/ed3360670a542174d4e3b86880c0eebb82ae395c) para a funcionalidade de BuscaAtiva, mas essa modificação não foi testada. Portanto, vejo aqui duas atividades:
- Verificar se o commit https://github.com/plone/Products.CMFPlone/commit/ed3360670a542174d4e3b86880c0eebb82ae395c resolve a questão da requisição incorreta. No caso, já testar a última versão 4.3.x do Plone (no momento ela é a 4.3.7). Se for o caso, é necessário também corrigir o relato https://github.com/plonegovbr/brasil.gov.agenda/issues/32;
- Adaptar a template/css/customização de forma a funcionar o recurso de BuscaAtiva.
- Remover Products.PloneHotfix20150910 de dependência do [setup.py](https://github.com/plonegovbr/brasil.gov.portal/blob/768f733a5e30718bbe78dd5c1e054ec389e3f342/setup.py#L84) ao explicitarmos o Plone 4.3.7.

Hoje no brasil.gov.portal esse recurso vem [desativado por padrão](https://github.com/plonegovbr/brasil.gov.portal/blob/a31fa027fb350e703f721a7e9d23b1e3df313785/src/brasil/gov/portal/profiles/default/propertiestool.xml#L18) enquanto no Plone é [ativado por padrão](https://github.com/plone/Products.CMFPlone/blob/522e880a78dd93d12520d1871519696787c5c3e8/Products/CMFPlone/profiles/default/propertiestool.xml#L120), inclusive no novo Plone 5. Qual foi a motivação para essa diferenciação aqui no brasil.gov.portal?

**Comment by hvelarde** [comment]
não conheço os detalhes mas pode ter sido simplesmente mudar o nome da view.

**Comment by idgserpro** [comment]
@ericof @rodfersou Saberiam dizer a motivação para que o "BuscaAtiva" viesse desativado por padrão?

@hvelarde Fizemos a pergunta pois, após a correção do bug, achamos interessante seguir o padrão atual do Plone a menos que haja alguma ressalva.

**Comment by davilima6** [comment]
Acredito que seja puramente por motivos performance e economicidade dos recursos públicos. A partir da 3a, se não me engano, cada letra digitada faz um ajax request no servidor, aumentando absurdamente a taxa de MISS de um Varnish ou similar.

**Comment by winstonf88** [comment]
Ao invés de criar uma view nova "@@busca" pq não simplesmente sobrescrever a view "@@search"?

**Comment by ericof** [comment]
Recomendação do Min. planejamento

**Comment by agnogueira** [comment]
Como disse o Erico, foi por questao de acessibilidade, para deixar o
endereço em portugues e legivel, já que esse endereço não é traduzível.

[]s




Em 7 de dezembro de 2015 10:29, Érico Andrei <notifications@github.com>
escreveu:

> Recomendação do Min. planejamento

**Comment by winstonf88** [comment]
entendido.

**Comment by idgserpro** [comment]
Acho de deveria ter um comentário no código sobre isso.

**Comment by winstonf88** [comment]
Eu criei uma view "@@buscalivesearch_reply" pra corrigir o problema sem alterar nomes, porém, o css da caixa de resultados fica MUITO zuado e não estou conseguindo corrigir. Alguém pode me ajudar com o css?

**Comment by idgserpro** [comment]
Não sei se o ideal é a criação de mais uma view. Você testou a versão 4.3.7 pra ver se a tentativa de desvincular o nome da view funciona? Aí seria o caso de resolvermos o relato em https://github.com/plonegovbr/brasil.gov.agenda/issues/32 pra fecharmos esse aqui.

**Comment by winstonf88** [comment]
@idgserpro poderia me informar o que foi modificado com relação a busca na versão 4.3.7?

**Comment by winstonf88** [comment]
@idgserpro fiz alguns testes na versão 4.3.7 realmente removeu o problema do vínculo com o nome porém o erro de css ainda persiste.

**Comment by winstonf88** [comment]
@idgserpro @hvelarde criei a branch [issue_237](https://github.com/plonegovbr/brasil.gov.portal/tree/issue_237) para solução desse problema de acordo com as modificações feitas no Plone 4.3.7. 
Porém, preciso de ajuda para resolver o problema de CSS nos resultados da busca, se puderem ajudar ou indicar alguém.

**Comment by hvelarde** [comment]
@winstonf88 desculpa, mas não consigo te ajudar com isso.

**Comment by davilima6** [comment]
Olá, Winston.

Pode detalhar seu problema com CSS ou, melhor ainda, disponibilizar acesso
ao site para que possamos observar e tentar ajudar?

Abs,
Davi

2016-01-04 14:04 GMT-02:00 Winston Ferreira <notifications@github.com>:

**Comment by winstonf88** [comment]
@davilima6 Estou implementando no meu ambiente local. Pra replicar o erro é só fazer o checkout do branch [issue_237](https://github.com/plonegovbr/brasil.gov.portal/tree/issue_237), habilitar o recurso de busca ativa nas configurações do site e depois fazer uma busca qualquer usando o campo no header do portal.

**Comment by davilima6** [comment]
Oi, @winstonf88. Não trabalho diretamente com Portal Padrão e infelizmente não tenho como testar o branch no momento. Se puder disponibilizar um acesso público, posso tentar ajudar com o CSS. Pelo screenshot não parece ser difícil.

**Comment by winstonf88** [comment]
Vou tentar criar um ambiente pra vc acessar.

Em seg, 11 de jan de 2016 às 16:09, Davi Lima <notifications@github.com>
escreveu:

**Comment by idgserpro** [comment]
Acho que você consegue usar o https://c9.io/, além da IDE, ele fornece uma interface de linha de comando e uma url pública que ele poderia acessar com o ambiente já montado e o serviço na porta 8080.
