### ISSUE TITLE
Atualizar plone.app.contenttypes para 1.1.1

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#240]
IDGB usa a versão 1.0 e a mais recente para o Plone 4.3 é a [1.1.1](https://pypi.python.org/pypi/plone.app.contenttypes/1.1.1).

**Comment by idgserpro** [comment]
O brasil.gov.agenda teria que ser alterado:

https://github.com/plonegovbr/brasil.gov.agenda/blob/master/setup.py#L46

**Comment by winstonf88** [comment]
Qual o impedimento do agenda em usar a versão nova do contenttypes?

**Comment by idgserpro** [comment]
@winstonf88 ver https://github.com/plonegovbr/brasil.gov.agenda/commit/ec6e87fef0f3fd933bc2707ed45ee6cde531f0ee

@ericof porque isso?

**Comment by hvelarde** [comment]
tem que atualizar tanto o plone.app.contenttypes quanto o plone.app.event

**Comment by idgserpro** [comment]
Ver também o impacto em plone.app.collection, uma vez que usamos a branch 2.x [e aqui se afirma](https://github.com/plone/plone.app.collection/tree/2.x) que já foi incorporado em plone.app.contenttypes.

**Comment by idgserpro** [comment]
plone.app.contenttypes 1.0 incorporou a branch 2.0.x do plone.app.collection. Ver https://github.com/plone/plone.app.contenttypes/blob/1.0/CHANGES.rst e https://github.com/plone/plone.app.contenttypes/commit/fa3470175f834f15e1ba7425b3a82239d8ad8c9d onde foi feita a mescla entre os dois pacotes. Por isso que pudemos remover a pinagem de plone.app.collection 2.0b5 em  https://github.com/plonegovbr/portal.buildout/commit/0d4d384e8c4ace9c8d37d444a7f16764f5c36026, pois criamos uma lógica que remove a layer do plone.app.collection para portais antigos que tinham esse pacote instalado (ver https://github.com/plonegovbr/brasil.gov.portal/commit/ab55f0fdf09201bb26e6fe9b1815e178a94d5e2c).

**Comment by claytonc** [comment]
@idgserpro 
Atualizando o plone.app.contenttypes para a versão 1.1.1 resolve #155.

**Comment by idgserpro** [comment]
Ver também se com essa atualização o relato https://github.com/plonegovbr/brasil.gov.portal/issues/290 pode ser fechado.

**Comment by claytonc** [comment]
Mais um bug relacionado a versão do plone.app.contenttypes que o provedor de conteúdos encontrou no tinymce, achei também uma issue https://github.com/plone/Products.TinyMCE/issues/123

Mesmo atualizando o tinymce o erro ocorre as vezes.

Testei em um plone puro com o plone.app.contenttypes para 1.1.1 o problema não ocorreu.

**Comment by claytonc** [comment]
@idgserpro 

Estou efetuando testes usando o IDG  1.1.4

**1º Teste** - criando um site IDG com o plone.app.contenttypes = 1.0 e depois atualizar para 1.1.1 simulando uma migração:

1. após a criação do site removi as pinagens dos produtos (agenda e temas)  e no arquivo vesions.cfg; Obs.: Só não entendi porque a  
2. quando executei o upgrade ocorreu os erros:
    * AttributeError: 'NoneType' object has no attribute 'splitlines' - por causa do campo "Participantes" esta em branco;
    * AttributeError: timezone -  porque a timezone gravada esta "BRT" e não é valida.
    * Possível solução- no arquivo plone.app.contenttypes/plone/app/contenttypes/migration/dxmigration.py linha 73 fiz essa alteração abaixo:
```
if hasattr(self.old, 'attendees'):
    if self.old.attendees:
        self.new.attendees = tuple(self.old.attendees.splitlines())
    else:
        self.new.attendees = ''
        self.new.timezone = 'UTC'
 ```
3. Após as alterações acima rodei o upgrade e o tipo "Evento" funcionou corretamente;

4. Também testei superficial adicionando os conteúdos da agenda;

5. plone.app.contenttypes 1.1.1 tem um upgrade que altera os nomes das visões "Use new view names" se rodar ira perder as customizações do IDG:

```
    outdated_methods = [
        'folder_listing',
        'folder_full_view',
        'folder_summary_view',
        'folder_tabular_view',
        'folder_album_view',
        'atct_album_view',
        'standard_view',
        'collection_view',
        'all_content',
        'thumbnail_view',
    ]
    new_methods = [
        'listing_view',
        'summary_view',
        'tabular_view',
        'full_view',
        'album_view',
        'event_listing',
    ]
```

**2º Teste** - criando um site IDG já com o plone.app.contenttypes = 1.1.1:

1. A maioria dos itens criados que testei funcionam corretamente até agora não encontrei outros problemas; 
2. Os nomes das visões estão no novo padrão conforme o 1º teste item 5.

**Comment by idgserpro** [comment]
@clayton, devemos trabalhar nesse relato para um próximo release. Agradeço de antemão os testes efetuados, principalmente com relação a ambientes já criados - temos de ter um carinho especial nesse contexto.

**Comment by hvelarde** [comment]
eu acho que precisamos atualizar esta issues para usar plone.app.contenttypes 1.1.2 e plone.app.event 1.1.8.

@claytonc eu fiquei com algumas dúvidas:

* aparentemente o erro no campo `atendees` foi originado pela falta de um valor default na versão antiga do plone.app.event; acho que seria mais simples criar um upgrade step que atualize esse campo para uma tupla vazia como é definido atualmente no pacote; com essa medida evitaríamos ter que modificar o upgrade step do upstream 
* no caso do campo `timezone` fiquei confuso pois o valor `BRT` é completamente válido; acho que está faltando definir uma variável de ambiente no buildout.cfg segundo descrito aqui: https://stackoverflow.com/q/23349397
* respeito das configurações da agenda, você tem informação mais precisa do que temos que fazer ai? como poderíamos solucionar esse problema?

pelo que estou entendendo atualizar fica totalmente viável após resolver esse ponto.

**Comment by claytonc** [comment]
@hvelarde 

* o erro do campo `atendess` só ocorreu em objetos criados pelo script do `brasil.gov.portal`, pois quando adicionando manualmente o campo já é inserido com vazio;
* o `warning BRT` desapareceu quando adicionei em `environment-vars` no base.cfg o valor `TZ America/Sao_Paulo`;
* quais configurações da agenda você quer que eu teste ?

**Comment by hvelarde** [comment]
@claytonc ótimo, abre por favor uma issue diferente relatando esse problema da criação automática de conteúdo para poder solucionar.

respeito ao terceiro ponto, não ficou claro para mim também não; tu falou que ao rodar o upgrade step "ira perder as customizações do IDG"; quais customizações? tu ve algum jeito de corrigir isso diretamente upstream?

**Comment by claytonc** [comment]
@hvelarde 

Mudou os nomes das visões das pastas e coleções.

Hoje por exemplo é `folder_summary_view` mudou para `summary_view` conforme o item 5 -  https://github.com/plonegovbr/brasil.gov.portal/issues/240#issuecomment-300259611

Um exemplo é [1] tem que alterar para `summary_view`.

[1] https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/browser/plone/configure.zcml#L47

**Comment by hvelarde** [comment]
@claytonc entendi; seria possível para você criar uma nova issue definindo essas mudanças que devem ser consertadas?

**Comment by idgserpro** [comment]
Acho que não precisa ser uma nova issue @hvelarde, só compilar tudo que foi discutido aqui e ou adicionar um novo comment ou editar o inicial, informando que para atualizar, "x" mudanças são necessárias.

**Comment by idgserpro** [comment]
Resolvido em

https://github.com/plonegovbr/portalpadrao.release/releases/tag/1.2

https://github.com/plonegovbr/portal.buildout/releases/tag/1.2
