### ISSUE TITLE
Testes falhando após pinagens necessárias para o plone4.csrffixes

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#241]
Após as [pinagens](https://github.com/plonegovbr/portal.buildout/commit/f7af5a270c897e9ff66ff9c66e31e8b9e78a9faa) necessárias para o plone4.csrffixes, os teste estão falhando:

https://travis-ci.org/plonegovbr/brasil.gov.portal/builds/85750471

**Comment by hvelarde** [comment]
atualizei novamente as versões do patch: https://github.com/plonegovbr/portal.buildout/commit/337ae32cad4324ea9a0805abc04ae7e60f453319

**Comment by hvelarde** [comment]
acho que vamos precisar dar uma olhada nisso ai: http://devblog.4teamwork.ch/blog/2015/10/12/debugging-csrf-protection-false-positives-in-plone/

**Comment by idgserpro** [comment]
Relacionado com https://github.com/plone/Products.CMFPlone/issues/1203

**Comment by idgserpro** [comment]
@hvelarde quando utilizamos o plone.protect 3.0.16 e não utilizamos o plone4.csrffixes, ocorre um [erro na criação de um Plone Site](https://github.com/plone/plone.protect/issues/35). Não devemos então adicionar o plone4.csrffixes como dependência do brasil.gov.portal, uma vez que utilizamos o [plone.protect 3.0.16](https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.3.1/versions.cfg#L552)?

**Comment by hvelarde** [comment]
@idgserpro ele está adicionado no buildout

**Comment by idgserpro** [comment]
@hvelarde está no buildout do portal.buildout mas não está no [buildout do brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/blob/master/buildout.cfg). Assim ele não é adicionado nos testes. Assim, temos que adicioná-lo ao buildout do brasil.gov.portal ou temos que adicioná-lo como dependência no setup.py. Eu voto por adicioná-lo ao setup.py.

Ver também: https://github.com/plone/plone.protect/issues/35

**Comment by hvelarde** [comment]
concordo, fique a vontade...

**Comment by winstonf88** [comment]
@idgserpro adicionar os produtos no setup.py não resolveu problema, sugestões?

Veja: #262

**Comment by idgserpro** [comment]
O commit https://github.com/plonegovbr/brasil.gov.portal/commit/9f2b2b679fc0f6f92da0616f12970efcbd91efeb somente desabilita o plone4.csrffixes. Os teste deveriam funcionar com ele habilitado.

**Comment by hvelarde** [comment]
-1

**Comment by idgserpro** [comment]
Talvez vamos precisar carregar o zcml do plone4.csrffixes nos teste como feito aqui:

https://github.com/collective/collective.cover/pull/594/files#diff-9

Ou então temos que carrega-lo no [dependencies.zcml](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/dependencies.zcml).

@rodfersou?

**Comment by hvelarde** [comment]
acho que isso tem que ser feito numa outra issue; por enquanto podemos considerar esta como resolvida pois os testes não estão falhando.
