### ISSUE TITLE
Erro ao criar Capa

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#242]
Quando tento adicionar uma Capa ocorre o erro:

    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.z3cform.layout, line 66, in __call__
      Module plone.z3cform.layout, line 60, in update
      Module z3c.form.form, line 263, in render
      Module z3c.form.form, line 158, in render
      Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
      Module zope.pagetemplate.pagetemplate, line 132, in pt_render
      Module five.pt.engine, line 93, in __call__
      Module z3c.pt.pagetemplate, line 163, in render
      Module chameleon.zpt.template, line 258, in render
      Module chameleon.template, line 171, in render
      Module d4d6f516f8f43e8f4822f03ea7c83301.py, line 91, in render
      Module 75126a132e53e674f0f6308f302ff1dc.py, line 1808, in render_titlelessform
      Module 75126a132e53e674f0f6308f302ff1dc.py, line 451, in render_fields
      Module 75126a132e53e674f0f6308f302ff1dc.py, line 126, in render_widget_rendering
      Module 75126a132e53e674f0f6308f302ff1dc.py, line 1077, in render_field
      Module five.pt.expressions, line 161, in __call__
      Module Products.Five.browser.metaconfigure, line 479, in __call__
      Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
      Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
      Module zope.pagetemplate.pagetemplate, line 132, in pt_render
      Module five.pt.engine, line 93, in __call__
      Module z3c.pt.pagetemplate, line 163, in render
      Module chameleon.zpt.template, line 258, in render
      Module chameleon.template, line 171, in render
      Module 96516d9bc15860bb249191c12f32a8cc.py, line 590, in render
      Module 96516d9bc15860bb249191c12f32a8cc.py, line 465, in render_widget_wrapper
      Module five.pt.expressions, line 161, in __call__
      Module collective.cover.widgets.selectpreview, line 54, in render
      Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
      Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
      Module zope.pagetemplate.pagetemplate, line 132, in pt_render
      Module five.pt.engine, line 93, in __call__
      Module z3c.pt.pagetemplate, line 163, in render
      Module chameleon.zpt.template, line 258, in render
      Module chameleon.template, line 191, in render
      Module chameleon.template, line 171, in render
      Module 09659b6cf6b177303179e8047b3657b1.py, line 123, in render
      Module five.pt.expressions, line 161, in __call__
      Module collective.cover.widgets.selectpreview, line 45, in js
      Module collective.cover.widgets.selectpreview, line 73, in simplify_layout
      Module collective.cover.widgets.selectpreview, line 64, in simplify_layout
    KeyError: 'column-size'
    
     - Expression: "widget/@@ploneform-render-widget"
     - Filename:   ... rm-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
     - Location:   (line 97: col 81)
     - Source:     ... place="structure widget/@@ploneform-render-widget"/>
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     - Expression: "view/js"
     - Filename:   ... y2.7.egg/collective/cover/widgets/selectpreview_input.pt
     - Location:   (line 7: col 54)
     - Source:     ... cript" tal:content="structure view/js"></script>
                                                     ^^^^^^^
     - Arguments:  repeat: {...} (0)
                   context: <ImplicitAcquisitionWrapper criadoem113 at 0xd96902c>
                   views: <ViewMapper - at 0xb40a836cL>
                   modules: <TraversableModuleImporter - at 0x95f474c>
                   args: <tuple - at 0xb44ac38cL>
                   nothing: <NoneType - at 0x81aa514>
                   target_language: <NoneType - at 0x81aa514>
                   default: <object - at 0xb74f87f0L>
                   request: <instance - at 0xb4445e0cL>
                   wrapped_repeat: {...} (0)
                   loop: {...} (0)
                   template: <ViewPageTemplateFile - at 0xb40a8c8cL>
                   translate: <function translate at 0xb40ae224L>
                   options: {...} (0)
                   view: <SelectPreviewWidget template_layout at 0xb40c6fccL>

**Comment by winstonf88** [comment]
@hvelarde isso é um erro do cover, já foi resolvido?

**Comment by idgserpro** [comment]
@winstonf88 quando tenho somente o cover instalado em um portal esse errro não ocorre. Então não é um problema do cover e sim do IDG.

**Comment by winstonf88** [comment]
As configurações de layout da capa no [registry.xml#L18-L19](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/profiles/default/registry.xml#L18-L19) estão erradas. 
Acredito que seja preciso fazer um upgrade step para atualizar essas informações em portais já criados.

**Comment by idgserpro** [comment]
Ainda falta o upgrade step

**Comment by hvelarde** [comment]
desculpem, a pressa por fechar.

**Comment by idgserpro** [comment]
@winstonf88 favor não esquecer dos upgradeSteps e dos testes dos mesmos, simulando um portal já instanciado onde esse erro ocorreria. Precisamos disso antes da geração de um novo release uma vez que todos os portais atuais hoje do IDG terão problemas.

**Comment by winstonf88** [comment]
@idgserpro a correção e os testes estão no PR [253](https://github.com/plonegovbr/brasil.gov.portal/pull/253)

**Comment by jeferson-github** [comment]
Estou tendo este erro também ao criar uma capa para uma Página de Destaque.
Adicionar item... / Capa

Desculpe, mas parece haver um erro...

Aqui está a mensagem de erro completa:

Visualizar traceback como texto

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 60, in update
  Module z3c.form.form, line 263, in render
  Module z3c.form.form, line 158, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module 3d755338108199821385f7227bb3a55c, line 92, in render
  Module 0f1f9d86188c5d6b0ece7610113f329a, line 1809, in render_titlelessform
  Module 0f1f9d86188c5d6b0ece7610113f329a, line 452, in render_fields
  Module 0f1f9d86188c5d6b0ece7610113f329a, line 127, in render_widget_rendering
  Module 0f1f9d86188c5d6b0ece7610113f329a, line 1078, in render_field
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 479, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module 19f55fac88a6056b5d2f413de18c9b2c, line 591, in render
  Module 19f55fac88a6056b5d2f413de18c9b2c, line 466, in render_widget_wrapper
  Module five.pt.expressions, line 161, in __call__
  Module collective.cover.widgets.selectpreview, line 54, in render
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 3454d25ad8909e640889715b4c698af4, line 124, in render
  Module five.pt.expressions, line 161, in __call__
  Module collective.cover.widgets.selectpreview, line 45, in js
  Module collective.cover.widgets.selectpreview, line 73, in simplify_layout
  Module collective.cover.widgets.selectpreview, line 64, in simplify_layout
KeyError: 'column-size'

 - Expression: "widget/@@ploneform-render-widget"
 - Filename:   ... rm-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
 - Location:   (line 97: col 81)
 - Source:     ... place="structure widget/@@ploneform-render-widget"/>
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/js"
 - Filename:   ... y2.7.egg/collective/cover/widgets/selectpreview_input.pt
 - Location:   (line 7: col 54)
 - Source:     ... cript" tal:content="structure view/js"></script>
                                                 ^^^^^^^
 - Arguments:  repeat: {...} (0)
               context: <ImplicitAcquisitionWrapper campanha-do-festival-de-artes-2015 at 0xae7c6b44L>
               views: <ViewMapper - at 0xae83406cL>
               modules: <TraversableModuleImporter - at 0xb73b366cL>
               args: <tuple - at 0xae7eb80cL>
               nothing: <NoneType - at 0x83ac190>
               target_language: pt_BR
               default: <object - at 0xb75406f0L>
               request: <instance - at 0xaf52dfacL>
               wrapped_repeat: {...} (0)
               loop: {...} (0)
               template: <ViewPageTemplateFile - at 0xae8911acL>
               translate: <function translate at 0xae6d9c6cL>
               options: {...} (0)
               view: <SelectPreviewWidget template_layout at 0xae8d01ccL>
