### ISSUE TITLE
Deixar de esconder o profile do collective.oembed

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#243]
Uma vez que o collective.oembed [não é mais dependência do sc.embedder](https://github.com/simplesconsultoria/sc.embedder/commit/cdb900c731df61d8103225151c6a8d516ad6650f), não é mais necessário esconder o profile do collective.oembed.

**Comment by hvelarde** [comment]
+1

**Comment by hvelarde** [comment]
acho que isso aqui não aplica mais.
