### ISSUE TITLE
Remover issues antigas

### ISSUE THREAD

**Issue by winstonf88** [plonegovbr/brasil.gov.portal#244]
Temos algumas issues de 2014 e até 2013 ainda abertas, podemos fechar?

**Comment by idgserpro** [comment]
Acho que essas issues ainda são válidas e precisam ser corrigidas.

**Comment by hvelarde** [comment]
+1

**Comment by idgserpro** [comment]
@winstonf88 podemos fechar esse relato?

**Comment by winstonf88** [comment]
@idgserpro Sim
