### ISSUE TITLE
Criar ambiente Vagrant para avaliação do IDGB

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#245]
Precismos criar um ambiente [Vagrant](https://www.vagrantup.com/) que permita a avaliação simples do IDGB sem ter maiores conhecimentos de Linux, Buildout e as outras tecnologias envolvidas numa instalação de produção.

Precisamos que fique documentado como criar esse ambiente para poder atualizar ele cada vez que um novo release for gerado.

**Comment by idgserpro** [comment]
Se a motivação é a avaliação "simples" do IDGB, concordo mais com o download de uma VM como está presente em https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/vm/, e para cada novo release, se exporta essa máquina virtual do release.

Na documentação acima, se instala um Virtualbox (disponível facilmente em Windows e Linux) e segue-se um roteiro simples para avaliação.

**Comment by domarques** [comment]
Caros: Já atualizei em meu ambiente de testes o https://github.com/plonegovbr/portal.vagrant e ainda esta semana faço os pull requests no **portal.buildout** e **portal.vagrant** já com os releases. Estou apenas finalizando os testes.

**Comment by hvelarde** [comment]
tinha esquecido da existência de esse repo; vou dar uma olhada pois ontem fiz conseguir fazer o Vagrant funcionar na minha máquina.
