### ISSUE TITLE
Criar container Docker para avaliação do IDGB

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#246]
Precismos criar um container [Docker](https://www.docker.com/) que permita a avaliação simples do IDGB sem ter maiores conhecimentos de Linux, Buildout e as outras tecnologias envolvidas numa instalação de produção.

Precisamos que fique documentado como criar esse container para poder atualizar ele cada vez que um novo release for gerado.

**Comment by idgserpro** [comment]
Ver https://github.com/plonegovbr/brasil.gov.portal/issues/245#issuecomment-154170001

**Comment by caduvieira** [comment]
Um exemplo de Dockerfile que comecei a criar:

    FROM library/ubuntu
    RUN apt-get -y update && apt-get install -y git=1:1.9.1-1ubuntu0.1 python2.7=2.7.6-8ubuntu0.2 python-virtualenv=1.11.4-1 \
        ca-certificates=20141019ubuntu0.14.04.1
    RUN adduser --system --shell /bin/bash plone && addgroup plone && adduser plone plone
    WORKDIR "/opt"
    RUN git clone --single-branch https://github.com/plonegovbr/portal.buildout.git portal.buildout
    RUN chown -R plone:plone portal.buildout
    USER plone
    WORKDIR "/opt/portal.buildout"
    RUN virtualenv py27 && python py27/bin/activate_this.py
    COPY buildout.cfg buildout.cfg
    RUN python bootstrap.py -c buildout.cfg
    RUN ./bin/buildout -c buildout.cfg

Precisa ainda de várias coisas com esse Dockerfile e é só um início longe de funcionar corretamente e do jeito que mereceria funcionar.

Uma é das necessidades é um pin na versão do portal.buildout para que a criação pelo docker seja sempre a mesma.

E o buildout.cfg que ele copia é o do http://identidade-digital-de-governo-plone.readthedocs.org/en/latest/producao/

**Comment by caduvieira** [comment]
Não sei também se não devemos dar um fork do https://github.com/plone/plone.docker e partir daí

**Comment by caduvieira** [comment]
@idgserpro pode ser criado um container e subir como um container oficial da IDG https://hub.docker.com/explore/

Ou ainda partir de um container do plone e adicionar nossos pacotes necessários.
https://hub.docker.com/search/?q=plone&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0

**Comment by hvelarde** [comment]
@caduvieira eu acho que o container não deve rodar o bulldout; ele deve ter o portal já instalado e funcionando com todo descarregado e instalado.

**Comment by caduvieira** [comment]
A comunidade está criando para a versão 5 
https://github.com/plone/plone.docker/tree/master/5.0

**Comment by hvelarde** [comment]
mas isso não vai nos servir :-)

**Comment by caduvieira** [comment]
Prezados,

Seguindo os procedimentos do https://github.com/plone/plone.docker/blob/master/docs/usage.rst criei rapidamente uma imagem docker do brasil.gov.portal. Tive que fazer alguns pins mas no mais deu certo.

O problema foi ao executar que ocorreu um erro de memória conforme o http://pastebin.com/HXcFy2iE

Alguem teve problema similar ou será que é por causa do uso do docker? Sem utilizar o IDG roda sem problemas de memória.

Dockerfile: http://pastebin.com/MiybiLmG

site.cfg: http://pastebin.com/Mji1c1e2

Error: http://pastebin.com/HXcFy2iE

**Comment by idgserpro** [comment]
@caduvieira 

parece estar relacionando com isso: https://github.com/plone/plone.subrequest/commit/6f63915aa040156e2e9f69eb3751cc52018c5794

Qual versão do IDG vocês está utilizando? Na versão 1.1.4 o plone.subrequest já foi pinado:

https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.4/versions.cfg#L563

**Comment by caduvieira** [comment]
Obrigado @idgserpro foi esse problema mesmo. 

adicionando a linha 'plone.subrequest = 1.7.0' ao site.cfg ficou 100% e estou rodando plone idg no docker.

**Comment by idgserpro** [comment]
@caduvieira você não utilizou o https://github.com/plonegovbr/portal.buildout para montar a instalação?

**Comment by caduvieira** [comment]
Não. Utilizei o Dockerfile http://pastebin.com/MiybiLmG já aproveitando o plone.docker na versão 4.3.9

**Comment by caduvieira** [comment]
Quem quiser verificar o que já tem pode ver em 
https://github.com/caduvieira/portal.docker
