### ISSUE TITLE
Erro 'TransformError' ao fazer Import, Rename, Copy/Paste de site

### ISSUE THREAD

**Issue by jeferson-github** [plonegovbr/brasil.gov.portal#248]
Olá pessoal.
Na Interface de Administração do Zope ao tentar fazer um Import ou Rename ou Copy/Paste de um site está dando o erro abaixo:

Site Error

An error was encountered while publishing this resource.

Error Type: TransformError
Error Value: Cannot find portal_transforms tool

________________________________

Troubleshooting Suggestions

* The URL may be incorrect.
* The parameters passed to this resource may be incorrect.
* A resource that this resource relies on may be encountering an error.

For more detailed information about the error, please refer to the error log.

If the error persists please contact the site maintainer. Thank you for your patience.

**Comment by hvelarde** [comment]
@davilima6 lembra de onde vem esse erro?

**Comment by davilima6** [comment]
@hvelarde, acho q vc se refere a plone/Products.CMFPlone#839, mas não acredito que seja o caso.

Aparentemente apagaram o objeto portal_transforms do site. Vejam: 
https://github.com/plone/plone.app.textfield/blob/master/plone/app/textfield/transform.py#L33-L35

**Comment by jeferson-github** [comment]
Realmente o primeiro erro que ocorre é referente a plone/Products.CMFPlone#839: 

('Could not adapt', <Image at /jatai2/assuntos/editoria-a/ultimas-noticias-da-editoria-a/copy_of_titulo-da-noticia-entre-35-e-90-caracteres-com-espaco/imagem-noticia_664.jpg>, <InterfaceClass plone.rfc822.interfaces.IPrimaryFieldInfo>)

Ao deletar a imagem "imagem-noticia_664.jpg", dá erro novamente para outra imagem:

('Could not adapt', <Image at /dti2/assuntos/editoria-a/ultimas-noticias-da-editoria-a/copy_of_titulo-da-noticia-entre-35-e-90-caracteres-com-espaco/cid_apo_beneficio-idoso_550.jpg>, <InterfaceClass plone.rfc822.interfaces.IPrimaryFieldInfo>)

Ao deletar a imagem "cid_apo_beneficio-idoso_550.jpg", o erro muda para "Cannot find portal_transforms tool".

https://colab.interlegis.leg.br/archives/thread/plonegov-br/erro-could-not-adapt-ao-fazer-import-rename-copypaste-de-site#msg-153772

Site Error

An error was encountered while publishing this resource.

Error Type: TransformError
Error Value: Cannot find portal_transforms tool

________________________________

Troubleshooting Suggestions

* The URL may be incorrect.
* The parameters passed to this resource may be incorrect.
* A resource that this resource relies on may be encountering an error.

For more detailed information about the error, please refer to the error log.

If the error persists please contact the site maintainer. Thank you for your patience.

**Comment by davilima6** [comment]
@jeferson-github, Olá. Você poderia verificar se possui na ZMI o objeto portal_transforms? Caso negativo, busque copiá-lo de outro portal com as mesmas configurações. Aparentemente foi apagado.

**Comment by jeferson-github** [comment]
Não tem esse objeto em http://10.254.2.26:8081/manage_main, aba Contents. De onde copio e onde colo?
Estou usando a instalção padrão, será que apagaram de lá?

**Comment by hvelarde** [comment]
parece que sim; tente novamente num site novo, por favor.

**Comment by jeferson-github** [comment]
Entrando no manage_main de qualquer site (http://10.254.2.26:8081/Plone/manage_main) consta o objeto portal_transforms (Handles data conversion between MIME types)

**Comment by hvelarde** [comment]
o problema não tem a ver com o IDGB então.

**Comment by jeferson-github** [comment]
Vocês conseguem realizar estas operações (Import, Rename, Copy/Paste) normalmente? Qual a versão que estão usando (Plone, Zope, Portal Padrão, etc.)?

**Comment by hvelarde** [comment]
@jeferson-github eu pessoalmente não uso o IDGB mas esse problema que você reporta é provocado por terem apagado um componente do portal; então pouco podemos fazer aqui.
