### ISSUE TITLE
Texto sobrescrito na exibição "Visão Sumária"

### ISSUE THREAD

**Issue by winstonf88** [plonegovbr/brasil.gov.portal#256]
Ao selecionar a "Visão Sumária" na home do portal o texto fica sobrescrito.

![image](https://cloud.githubusercontent.com/assets/1376143/11751027/03eb3888-a01e-11e5-84eb-f339353bba0d.png)

**Comment by winstonf88** [comment]
Alguém pode me dizer a exibição abaixo está correta?

![image](https://cloud.githubusercontent.com/assets/1376143/11751126/ab64ae78-a01e-11e5-948f-f2254262faf4.png)

**Comment by idgserpro** [comment]
@winstonf88 essa não é a visão sumária. A visão sumária é essa:

![selecao_025](https://cloud.githubusercontent.com/assets/8203476/11755005/836d489a-a036-11e5-9a05-0f72bc568d76.png)

**Comment by idgserpro** [comment]
@winstonf88 desculpe. A visão sumária que eu mostrei no comentário anterior é para pasta e não para o Plone Site. Só não sei se a visão que você mostrou está com a formatação correta. 

@rodfersou pode ajudar aqui?

**Comment by rodfersou** [comment]
@idgserpro se me lembro bem, temos definido a visão sumária de pastas e coleções (e o resultado da busca também é bem parecido)

@winstonf88 acredito que podemos seguir os mesmos estilos dessas visões
