### ISSUE TITLE
Atualizar collective.polls para 1.9b1

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#267]
a versão 1.9b1 do collective.polls foi liberada e inclui algumas melhorias interessantes:

https://pypi.python.org/pypi/collective.polls/1.9b1#b1-2016-09-29

sugiro atualizar o IDGB para utilizar esta nova versão.

tem alguns riscos envolvidos pois esta versão inclui já o tile de enquete e seria necessário criar um upgrade step para atualizar e remover esse tile do IDGB.

**Comment by winstonf88** [comment]
pq esse tile não pode ser usado no IDG?

**Comment by idgserpro** [comment]
Poder ele pode, mas antes precisamos remover a [implementação do tile atual de enquete em brasil.gov.tiles](https://github.com/plonegovbr/brasil.gov.tiles/blob/5430d930a3e6ed8fb739eb9562c488d50ea452ca/src/brasil/gov/tiles/tiles/configure.zcml#L21) mas com os devidos upgradeSteps para que não dê erro nos portais que já estão no ar.

**Comment by hvelarde** [comment]
isso!

**Comment by idgserpro** [comment]
Se for atualizar para 1.9b2, precisa ficar atento que collective.z3cform.widgets deixou de ser dependência, pode ser necessário colocar como dependência explícita (parecido com https://github.com/plonegovbr/brasil.gov.portal/issues/348#issuecomment-309847978)

**Comment by hvelarde** [comment]
superseded by https://github.com/plonegovbr/brasil.gov.portal/issues/377
