### ISSUE TITLE
Privilégios Insuficientes para revisor

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#286]
Quando um usuário com perfil de Revisor clica na aba Conteúdo de uma pasta (publicada ou não) ocorre um erro de Privilégios Insuficientes.

**Comment by hvelarde** [comment]
o revisor pode fazer isso num Plone zerado?

**Comment by idgserpro** [comment]
@hvelarde sim, pode.

**Comment by claytonc** [comment]
@idgserpro @hvelarde  com o perfil de Contributor (pode adicionar) também ocorre o erro de Privilégios Insuficientes.

Efetuei testes com um Plone zerado com Archetypes e depois com Dexterity e ao clicar na aba conteúdo não ocorre o problema, funciona corretamente.

As únicas permissões que não permite acessar aba conteúdo, tendo como base um Plone zerado são Member e Reader (pode ver)

**Comment by claytonc** [comment]
@idgserpro @hvelarde  

Pessoal descobri o que esta causando o erro de permissão.

O produto **collective.upload** sobrescreveu a template  "folder_contents" do produto plone.app.content e alterou a permissão de "cmf.ListFolderContents" para "cmf.ModifyPortalContent".

Conforme os trechos abaixo:

1 - plone.app.content/browser/configure.zcml:
```
<browser:page
        for="*"
        class=".foldercontents.FolderContentsView"
        name="folder_contents"
        template="folder_contents.pt"
        permission="cmf.ListFolderContents" />
```
2 - collective.upload/browser.py
```
class Folder_Contents(grok.View, FolderContentsView):
    grok.context(Interface)
    grok.layer(IUploadBrowserLayer)
    grok.require('cmf.ModifyPortalContent')
```

**Comment by idgserpro** [comment]
Excelente achado @claytonc! Há [um relato em collective.upload](https://github.com/collective/collective.upload/issues/65) estudando a possibilidade de remover essa customização do folder_contents, acho que se ele for atendido seguindo por esse caminho, podemos mudar a versão utilizada do collective.upload em https://github.com/plonegovbr/portalpadrao.release e fecharmos esse relato.

@hvelarde p/c

**Comment by hvelarde** [comment]
obrigado! a gente não tem recursos para trabalhar nisso agora; se algum de vocês pode ajudar vou agradecer.

**Comment by claytonc** [comment]
@idgserpro @hvelarde  
por hora vou ter que fazer uma solução temporária que altera a permissão para "cmf.ListFolderContents" para atender uma demanda.

tenho que da olhada com calma o porque o collective.upload optou alterar a permissão.

**Comment by idgserpro** [comment]
@claytonc será que, no momento que customizaram o folder_contents, no Plone, a permissão utilizada era essa? Depois dê uma olhada no histórico do arquivo, ver quando foi customizado, e quais versões do Plone geralmente eram utilizadas nessa época pra ter uma idéia: se a permissão era essa e não é mais, não vejo grandes problemas na modificação.

**Comment by idgserpro** [comment]
Mas como falamos, se mudar pra viewlet removendo a customização, nem precisa ver porque o collective.upload alterou a permissão. Com relação a isso, a discussão pode ser feita em collective.upload.

**Comment by claytonc** [comment]
@idgserpro 
Olhei todas as versões do plone.app.content, em todas sempre a permissão foi cmf.ListFolderContents.

Mas se decidirem manter o viewlet é só sobrescrever a classe do collective.upload no produto brasil.gov.portal, que já sobrescreve  outras classes do upload.

brasil.gov.portal/browser/upload/browser.py:
```
class Folder_Contents(browser.Folder_Contents):
    grok.context(Interface)
    grok.layer(IUploadBrowserLayer)
    grok.require('cmf.ListFolderContents')
```

**Comment by idgserpro** [comment]
@claytonc na verdade sugerimos remover a custumização do folder contents e passar para viewlet. Hoje não é viewlet. Ver:

https://github.com/collective/collective.upload/issues/65

**Comment by claytonc** [comment]
@idgserpro entendi ficaria melhor mesmo.

**Comment by claytonc** [comment]
@idgserpro

Só para  ficar documentado uma solução de contorno, pois não posso esperar a nova versão do idg ou do collective.upload com a correção.

 No production.cfg adicionei o "collective.recipe.patch"

```
[collective-upload-patch]
    recipe = collective.recipe.patch
    egg = collective.upload==1.0rc1
    patches = ${buildout:directory}/patches/collective-upload.patch
```


Conteúdo do arquivo "collective-upload.patch"
```
--- collective/upload/browser.py
+++ collective/upload/browser.py
@@ -42,7 +42,7 @@
 class Folder_Contents(grok.View, FolderContentsView):
     grok.context(Interface)
     grok.layer(IUploadBrowserLayer)
-    grok.require('cmf.ModifyPortalContent')
+    grok.require('cmf.ListFolderContents')


 # TODO: convert into a folder action: Upload files and images

```

**Comment by hvelarde** [comment]
@claytonc bem interessante essa sua solução, não conhecia (CC @rodfersou).

temos um problema adicional para corrigir: o widget de carga não deve ser mostrado para usuários sem permissão "cmf.AddPortalContent"; era por isso era que tínhamos trocado isso ai (mesmo com a permissão errada); acho interessante consertar isso no template até migrar para um viewlet.
