### ISSUE TITLE
Inclusão do collective.captcha (ou outro pacote) por padrão nos portais IDG

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#292]
Por motivos de segurança sugerimos que o produto collective.captcha (ou outro pacote) já venha instalado por padrão nos portais IDG.

https://community.plone.org/t/whats-the-current-captcha-plugin-state-in-plone-world-specially-4-3-which-are-you-using-and-why/4991 poderia ser usado para averiguar as opções disponíveis hoje no mundo Plone.

**Comment by claytonc** [comment]
Sugiro utilizar o collective.recaptcha

**Comment by idgserpro** [comment]
> Sugiro utilizar o collective.recaptcha

O recaptcha realmente é muito bom. O problema é que ele depende de um serviço externo do google e do registro de uma conta, ou seja, não funciona automaticamente só de instalar o IDG. A idéia é evitar isso.

**Comment by claytonc** [comment]
@idgserpro 

Não vejo problemas em usar serviços externos.

Muitos portais que usam o IDG utiliza o google analytics, então o problema da conta já é resolvido.

O que pode ser feito é sugerir os dois produtos e explicar como funciona cada e deixar a cargo do administrador do portal escolher qual é a melhor solução para o seu portal.

Já utilizei por um bom tempo o collective.captcha que foi substituído pelo novo recaptcha, tínhamos muitas reclamações de usuários, principalmente do pessoal de acessibilidade.

Também não é só instalar é necessário efetuar configurações adicionais no front-end e nas instancias com zeo para manter a sessão e os cokies do captcha.

**Comment by idgserpro** [comment]
Só pra constar: considero o collective.recaptcha *melhor* do que o collective.captcha, mas considero temerário colocar, no "core" do IDG, um plugin que precise de uma conta num serviço externo proprietário para ele poder começar a funcionar. Talvez o @hvelarde compartilhe da mesma opinião.

> Muitos portais que usam o IDG utiliza o google analytics, então o problema da conta já é resolvido.

Não se pode partir da premissa que todos tem uma conta do google, mesmo porque para se usar o analytics do google tem de se concordar com os seus termos de uso. Muita gente prefere usar o piwik por exemplo.

> O que pode ser feito é sugerir os dois produtos e explicar como funciona cada e deixar a cargo do administrador do portal escolher qual é a melhor solução para o seu portal.

Hoje o administrador já tem isso: basta no buildout adicionar o collective.recaptcha. A idéia de adicionar o collective.captcha é de ter um plugin que, só de instalar, possa funcionar.

> Já utilizei por um bom tempo o collective.captcha que foi substituído pelo novo recaptcha, tínhamos muitas reclamações de usuários, principalmente do pessoal de acessibilidade.

Você está certo. Pelo que eu me lembre inclusive, não tem nem a versão áudio em português do captcha: a idéia é de, com o collective.captcha incorporado, ele também ir sendo melhorado. Ou será então que deveríamos criar um relato no collective.captcha pra resolver esses defeitos, e só depois de corrigidos propor incorporar aqui?

Essa é uma discussão mais ampla, acho que poderíamos envolver mais gente. Sugestões, @agnogueira ?

**Comment by hvelarde** [comment]
vocês podem abrir uma discussão sobre este quesito na lista, por favor?

**Comment by idgserpro** [comment]
Andamos pensando muito sobre esse assunto e chegamos à conclusão que o ideal mesmo é o que o @claytonc recomendou, usar o recaptcha, mesmo sendo um serviço externo. Como é um pacote que só seria usado inicialmente no Products.PloneFormGen, usuários que não utilizam formulários nem teriam noção da existência do pacote.

O collective.captcha não é atualizado [desde 2012](https://github.com/mjpieters/collective.captcha/commit/cf90d8964d9e1a227a51088722e3e1f2890588bc): já o recaptcha, temos [commit de dezembro de 2017](https://github.com/collective/collective.recaptcha/commit/4bee5170218a516e9e6c5eb1f4cbdbd2f87397a1), ou seja, a tendência da comunidade é essa. Mexer com captcha é um "trabalho de gato e rato", o fato de ser um serviço externo que alimenta sua base de dados por inteligência artificial e *machine learning* é um diferencial.

Entretanto, por questões de usabilidade, recomendo dois relatos serem tratados antes de se adicionar o collective.recaptcha aqui no IDG: https://github.com/collective/collective.recaptcha/issues/16 e https://github.com/smcmahon/Products.PloneFormGen/issues/209.

Para ver mais opções de captchas na comunidade, ver https://community.plone.org/t/whats-the-current-captcha-plugin-state-in-plone-world-specially-4-3-which-are-you-using-and-why/4991.
