### ISSUE TITLE
Esconder mais profiles em config.py

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#296]
Ao tentar criar um novo Plone Site versão 1.1.4, precisamos esconder

![selecao_182](https://cloud.githubusercontent.com/assets/8203476/16533151/1c544b38-3fad-11e6-98a1-b1e84e09225d.png)

Se o interesse for de continuar escondendo pra todo novo release, compensa analisar a possibilidade/viabilidade de fazer um teste na customização de **@@plone-addsite** que verifica isso.

**Comment by claytonc** [comment]
@idgserpro não tinha visto essa issue mas já escondi referente ao  brasil.gov.portlets

**Comment by idgserpro** [comment]
@hvelarde vamos continuar escondendo os profiles? Se for seguir por esse caminho, temos de esconder mais alguns.

**Comment by idgserpro** [comment]
Dependendo do que decidirmos aqui, podemos inclusive fechar https://github.com/plonegovbr/brasil.gov.portal/issues/325 e https://github.com/plonegovbr/brasil.gov.portal/issues/239.

**Comment by hvelarde** [comment]
podemos esconder os profiles dos pacotes que não são extensões do IDG e esconder alguns outros do painle de controle; mas acho que por enquanto a maioria tem que ficar visível.

sugiro ocultar todos os que estão marcados, mas precisamos esperar pela atualização do Plone pois alguns não vão aparecer mais.

![screenshot-2017-10-27 criar um site plone](https://user-images.githubusercontent.com/341393/32118502-ad958b0c-bb30-11e7-954a-02f9818c6c0a.png)
