### ISSUE TITLE
Atualizar release de collective.upload para 1.3b1

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#300]
Ver https://github.com/plonegovbr/brasil.gov.portal/issues/286

Quando o release for lançado, testar para ver se não contém erros quando rodado no IDG e atualizar a versão.

**Comment by hvelarde** [comment]
@idgserpro você testaram já as mudanças? posso fazer o release?

**Comment by idgserpro** [comment]
Ainda não. O relato foi aberto pra não esquecer que isso tem de ser feito já que o #286 foi fechado, mas falado que com atualização do collective.upload [fica ok](https://github.com/plonegovbr/brasil.gov.portal/issues/286#issuecomment-223394237).

**Comment by hvelarde** [comment]
o novo release foi liberado: https://pypi.python.org/pypi/collective.upload/1.2b1

**Comment by hvelarde** [comment]
um novo release foi disponibilizado em agosto: https://pypi.python.org/pypi/collective.upload/1.3b1

**Comment by claytonc** [comment]
Adicionei também como bug, pois o #286 não foi solucionado no IDG.

Uma solução imediata é adicionar o código abaixo no "brasil.gov.portal/browser/upload/browser.py" que foi sugerido em Junho/2016, para entrar no próximo release.

```
class Folder_Contents(browser.Folder_Contents):
    grok.context(Interface)
    grok.layer(IUploadBrowserLayer)
    grok.require('cmf.ListFolderContents') 
```

Ou aguardar um bom tempo e esperar a nova versão  do collective.upload testar bastante para sair quem sabe em um futuro release.

A minha sugestão é corrigir o IDG, pois esse problema atrapalha pessoas que desejam utilizar workflows personalizados.

**Comment by hvelarde** [comment]
substituída pela #350
