### ISSUE TITLE
Corrigir erro na visualização de notícias

### ISSUE THREAD

**Issue by finnicius** [plonegovbr/brasil.gov.portal#303]
Ao visualizar uma notícia em resolução inferior a 768 pixels, o layout se quebra, formando um espaço em branco à direita do header, e à esquerda da área da notícia (vide anexo).

![image](https://cloud.githubusercontent.com/assets/5914549/17449524/8ac0ec4e-5b31-11e6-8f28-5bbb94f83114.png)

**Comment by finnicius** [comment]
Duplicado (enviado pull request #304 )

**Comment by idgserpro** [comment]
@finnicius vou deixar a issue aberta até que o seu PR seja analisado.

**Comment by idgserpro** [comment]
@finnicius Exatamente em qual versão você encontrou esse erro? Em qual browser?

Pode nos informar o que estiver no seu painel de controle, tanto no canto inferior esquerdo do painel quanto o que estiver na opção "Complementos".

**Comment by finnicius** [comment]
@idgserpro , reduza a largura da sua tela [neste link ](http://www.portalpadrao.gov.br/conteudos-de-marcacao/texto-1-titulo-da-noticia-entre-35-e-90-caracteres) para menos de 768 pixels e vc verá.

Notei também que praticamente todos os sites do Governo que usam a IDG e o Plone apresentam o mesmo erro. O pull request que enviei corrige o problema. Identifiquei o erro pois estou criando uma versão Wordpress do tema.

**Comment by finnicius** [comment]
O erro acontece em todos browsers.

**Comment by idgserpro** [comment]
@finnicius mas você instalou o Portal Padrão ou viu somente nos portais da internet?

**Comment by finnicius** [comment]
@idgserpro Somente nos portais. Mas o CSS do projeto aqui no Github apresenta o mesmo erro.

**Comment by finnicius** [comment]
Veja o pull request #304 , lá demonstro em qual linha está o problema e proponho a correção.

**Comment by finnicius** [comment]
@idgserpro , o segundo print tirei depois de corrigir o problema no próprio navegador, usando a função "inspecionar código" e alterando o referido CSS como fiz no pull request. Mas também corrigi essa questão na minha versão da IDG para Wordpress, que usa o CSS do projeto e gera exatamente o mesmo HTML que a IDG para Plone.

**Comment by idgserpro** [comment]
@finnicius parece que esse problema foi corrigido de uma outro forma em versões mais novas do IDG. Veja como ficou para mim com a versão nova:

![idg](https://cloud.githubusercontent.com/assets/8203476/17479965/f56c0314-5d4b-11e6-987b-4403de9bc71a.png)

Você ainda vê algum problema? Fiz o teste correto?

**Comment by finnicius** [comment]
Isso mesmo; cheguei ao mesmo resultado com aquele fix que enviei (vide abaixo). 

![image](https://cloud.githubusercontent.com/assets/5914549/17480460/5e28b6f2-5d4e-11e6-8871-b69d69f1df9f.png)

Vc sabe me dizer um site que esteja com a versão atualizada, pra eu tomar como base no desenvolvimento para WP? Preferi evitar instalar o Plone por enquanto, pra não ter que estudar a configuração da IDG neste momento.

**Comment by idgserpro** [comment]
@finnicius fiz mais uns testes aqui e o problema acontece na verão mais nova. É que ele só ocorre quando há algum portlet na coluna da direita:

![idg2](https://cloud.githubusercontent.com/assets/8203476/17481175/07f43da2-5d52-11e6-856e-beb8a5013db8.png)

Se não existe a coluna da direita o problema não ocorre.

Não tenho conhecimento de portais que utilizam a versão mais nova. Os que eu trabalho utilizam uma versão antiga. @hvelarde você tem conhecimento de algum portal que utiliza a versão mais nova?

**Comment by finnicius** [comment]
@idgserpro , realmente, também na minha versão o problema ocorre apenas quando há a área de porlets (confirmei agora). Então mantenho a sugestão de aprovar o pull request.

**Comment by finnicius** [comment]
(O problema está restrito às DIVs com classe width-1:2, que não existem quando não há portlets. )

**Comment by idgserpro** [comment]
Corrigido: https://github.com/plonegovbr/brasil.gov.portal/commit/84217d451ee79331e42318c27fa7cce0c2e7c667
