### ISSUE TITLE
Erro na aparência do portal após o login

### ISSUE THREAD

**Issue by luizgsbraz** [plonegovbr/brasil.gov.portal#318]
Logo após o login, a tela "Você agora está autenticado" fica prejudicada, conforme mostra a figura.

![login_bug](https://cloud.githubusercontent.com/assets/7255936/18968663/48eced2c-8660-11e6-9ecb-9eeb5377da80.png)

Quando clico sobre o nome do Portal a aparência do site volta ao normal.

**Comment by idgserpro** [comment]
@luizgsbraz esse é um problema de tema. Favor abrir o relato em:

https://github.com/plonegovbr/brasil.gov.temas/issues

**Comment by hvelarde** [comment]
esse é um velho problema; tal vez o @agnogueira lembra como consertar.

**Comment by hvelarde** [comment]
@idgserpro por que isso foi fechado? o @claytonc está me falando que o problema ainda acontece.

**Comment by idgserpro** [comment]
Acho que é porque acabou sendo feito em https://github.com/plonegovbr/brasil.gov.temas/issues/131. Realmente ficou faltando uma referência aqui.

**Comment by agnogueira** [comment]
O problema ainda persiste.
Pelo que entendi o @luizgsbraz corrigiu num fork apenas. O código não veio para o repositório principal.
https://github.com/luizgsbraz/brasil.gov.temas/commit/8d1666fa8229aa7682c727ba660b037f3142b041

**Comment by idgserpro** [comment]
Quando eu disse "sendo feito" é porque a discussão foi pra lá. :)

Recomendo fechar um dos dois relatos, pois eles tratam da mesma coisa.

**Comment by agnogueira** [comment]
Agora já foi feito de vez, lá na issue https://github.com/plonegovbr/brasil.gov.temas/issues/131 . 
Fechando essa aqui.
