### ISSUE TITLE
Configuração de desenvolvimento não inclui o brasil.gov.portal

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#324]
Estamos testando migração da versão 1.1.4 para versão 1.1.5.1 e o pacote policy po portal não é incluso.

o workaround é :

```
-eggs +=
+eggs +=
+    ${:package-name}
+
```

**Comment by idgserpro** [comment]
Sim. Estamos tratando na branch https://github.com/plonegovbr/portal.buildout/tree/plone_not_available desde de manhã. Criamos um teste no .travis.yml para esse tipo de erro não ocorrer novamente.

**Comment by idgserpro** [comment]
@hvelarde  Achamos que com esse fix, um release 1.1.5.2 deve ser gerado imediatamente. Com a build https://travis-ci.org/plonegovbr/portal.buildout/jobs/178660461 passando, devemos já gerar as tags nesses repositórios e um diretório 1.1.5.2 no portalpadrao.release.

**Comment by idgserpro** [comment]
@hvelarde Fizemos um PR em https://github.com/plonegovbr/portal.buildout/pull/61

Favor testar e se estiver tudo ok fazer o merge. Assim lançaremos um release 1.1.5.2 gerando uma tag em portal.buildout e portalpadrao.release imediatamente porque esse erro é completamente impeditivo.

**Comment by idgserpro** [comment]
Corrigido em: https://github.com/plonegovbr/portal.buildout/pull/61

**Comment by idgserpro** [comment]
@hvelarde https://github.com/plonegovbr/portal.buildout/releases/tag/1.1.5.2 e https://github.com/plonegovbr/portalpadrao.release/releases/tag/1.1.5.2
