### ISSUE TITLE
Atualizar sc.social.like para 2.8b1

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#329]
a versão 2.6a1 do sc.social.like foi liberada e inclui algumas melhorias interessantes:

https://pypi.python.org/pypi/sc.social.like/2.6a1#a1-2016-09-23

sugiro atualizar o IDGB para utilizar esta nova versão.

**Comment by idgserpro** [comment]
Recomendamos usar a 2.6a1 por causa dos ícones de Telegram e Whatsapp, muitos clientes estão cobrando.

**Comment by hvelarde** [comment]
substituída pela #352
