### ISSUE TITLE
Atualizar Products.CMFPlone para 4.3.15.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#331]
Hoje estamos na [4.3.9](https://github.com/plonegovbr/portal.buildout/blob/b541b83176d836327d4af603da258aa7fabb5e66/buildout.d/versions.cfg#L28).

Ao atualizar a versão do Plone, o relato https://github.com/plonegovbr/brasil.gov.portal/issues/310 e https://github.com/plonegovbr/brasil.gov.portal/issues/290 podem ser fechados.

Também seria interessante que os jobs de integração contínua que apontem para o `master` também passassem a quebrar a build quando falharem.

Além disso, com a atualização, podemos remover as pinagens da infra de testes presente em https://github.com/plonegovbr/portal.buildout/blob/9d9e21910c622c529c5d735dec037e11489da390/buildout.d/versions.cfg#L181,L187 pois praticamente todos estarão atualizados. Recomendamos deixar apenas `robotframework-wavelibrary` que não está pinado pelo Plone. Uma revisão no arquivo todo será interessante.

A pinagem em https://github.com/plonegovbr/brasil.gov.tiles/blob/2cd2026d8752dc4d7118788b348c25e1974c2e07/buildout.cfg e https://github.com/plonegovbr/brasil.gov.tiles/blob/2cd2026d8752dc4d7118788b348c25e1974c2e07/.travis.yml (foi necessária para passar o teste https://github.com/plonegovbr/brasil.gov.tiles/blob/2cd2026d8752dc4d7118788b348c25e1974c2e07/src/brasil/gov/tiles/tests/test_bannerrotativo_tile.robot#L59) também poderá ser removida, pois essa versão do selenium está disponível desde a 4.3.10 de Products.CMFPlone.

Ver também quais hotfixes podem ser removidos (também de portal.buildout) após essa atualização (ver https://plone.org/security/hotfixes).

Ver o impacto nas customizações feitas em https://github.com/plonegovbr/brasil.gov.portal/pull/270/files e que evoluiram para https://github.com/plonegovbr/brasil.gov.portal/commit/ae2054a2d84026378819ea8490dd024481fe1480 após a atualização do plone.app.contenttypes. Acredito que não será necessário pois o impacto maior foi com o plone.app.contenttypes.

**Comment by hvelarde** [comment]
só uma dúvida: o plone.subrequest está atualizado agora? lembrem que a versão pinada no Plone 4.3.9 estava com um memory leak.

**Comment by idgserpro** [comment]
@hvelarde foi na versão 1.7.0 que corrigiram isso, não foi? Tomamos o cuidado de no release 1.1.5.2 já ter essa preocupação. Ver https://github.com/plonegovbr/portalpadrao.release/blob/9584fcdf5dee7793936328919bc0fbb71530ff2d/1.1.5.2/versions.cfg#L88

Ao atualizar o Plone, essa pinagem da gente inclusive pode ser removida.

**Comment by claytonc** [comment]
@idgserpro eu achei um bug na versão 4.3.11 é melhor aguardar a correção.

https://github.com/plone/Products.CMFPlone/issues/1959

**Comment by idgserpro** [comment]
@claytonc 4.3.13 parece resolver o problema. https://community.plone.org/t/plone-4-3-13-soft-released/3873. (Sendo mais específico, foi o pacote Products.CMFPlacefulWorkflow: 1.5.14 → 1.5.15). Depois se puder dar uma olhada, já vou alterar o título dessa issue.

**Comment by claytonc** [comment]
@idgserpro além do problema da reinstalação do CMFPlacefulWorkflow também estava com problemas em adicionar os itens no portal_controlpanel [1].

Eu já estou utilizando a versão 4.3.12 em um novo projeto, apliquei o patch e atualizei o CMFPlacefulWorkflow, irei utilizar mas por causa do "Status check" [2].

Estava tendo problemas com o httpok aonde estava reiniciando as instâncias sem necessidade, ainda não consegui efetuar testes para comprovar se houve melhora ou não.

[1]1 https://github.com/plone/Products.CMFPlone/commit/a86de300159b97d3984af01b50d0eedb69bf8c94

[2] https://docs.plone.org/manage/deploying/production/status_check.html

**Comment by claytonc** [comment]
@idgserpro nesta versão vocês pretendem usar a plone.app.contenttypes 1.1.1 [1], que contém várias correções de bugs ?

Pergunto isso, pois no portalpadrao.release 1.1.5.2 esta pinado na versão 1.0 [2], sendo que o Plone 4.3.9 padrão é utilizar versão 1.1 [3].

Gostaria de sabe mais detalhes de erros sobre **brasil.gov.agenda** e **brasil.gov.temas**, pois em ambos produtos contém a pinagem **plone.app.contenttypes<1.1a1'**. Pergunto isso porque removi as pinagens de downgrade utilizadas em ambos estão e o portal esta funcionando corretamente, o único passo a mais que tive que executar foi um upgrade no plone.app.contenttypes em portal_setup.


[1] http://dist.plone.org/release/4.3.14/versions.cfg
[2] https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.5.2/versions.cfg#L78
[3] http://dist.plone.org/release/4.3.9/versions.cfg

**Comment by idgserpro** [comment]
São issues diferentes, não precisa ser ao mesmo tempo. Sim, nos dois pacotes existem essas pinagens mas não temos o histórico da motivação. Em tese é como você falou, ao despinar não há muitos problemas, mas achamos que seria importante um teste exploratório após a atualização e por isso não foi feito ainda. De qualquer forma, bom saber que você já tem isso pinado e não há problemas aparentes.

**Comment by claytonc** [comment]
@idgserpro na verdade estou tendo que fazer isso, por causa de vários bugs que os usuários provedores de conteúdos estão encontrando no IDG por causa do plone.app.contenttypes 1.0.

**Comment by idgserpro** [comment]
@claytonc você pode fazer um PR despinando aqui:

https://github.com/plonegovbr/brasil.gov.agenda/blob/master/setup.py#L47
e aqui:
https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg#L110

**Comment by claytonc** [comment]
@idgserpro testando aqui encontrei alguns probleminhas até agora nenhum grave todos são fáceis de resolver 

Irei colocar os testes que fiz no https://github.com/plonegovbr/brasil.gov.portal/issues/240

**Comment by idgserpro** [comment]
Ver o impacto da atualização devido às customizações presentes em https://github.com/plonegovbr/brasil.gov.portal/pull/270/files
