### ISSUE TITLE
Criar documentação sobre como atualizar entre diferentes releases do IDG

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#332]
Independentemente de https://github.com/plonegovbr/brasil.gov.portal/issues/325 ser atendido ou não e do processo tradicional do Plone ser utilizar a aba portal_setup para atualizar upgradeSteps, achamos que deveria ter uma documentação mais intuitiva sobre todo esse processo. Hoje, a documentação informa apenas sobre alteração no buildout para pegar um novo release e não sobre upgradeSteps (ver https://github.com/plonegovbr/portal.buildout/blob/d93cf24354ff71970f111d1e8c90e3a195a1f072/docs/atualizacao.rst).

**Comment by idgserpro** [comment]
Curiosidade @hvelarde sabe como funciona o processo de atualização no https://identidade-digital-de-governo-plone.readthedocs.io/en/latest/ quando o https://github.com/plonegovbr/portal.buildout/tree/master/docs é alterado?

**Comment by hvelarde** [comment]
acho que roda a cada 5 ou 10 minutos, mas não sei onde isso acontece; tal vez o @Dadlo ou o @winstonf88 lembrem.

**Comment by idgserpro** [comment]
Mas "roda" onde? Quando você cadastra um projeto no readthedocs, você especifica um repositório git e de tempos em tempos ele faz esse procedimento?

**Comment by idgserpro** [comment]
Feito em https://github.com/plonegovbr/portal.buildout/pull/65

**Comment by idgserpro** [comment]
Bem, de qualquer forma adicionei como um serviço no repositório, vamos ver como se comporta.

![selecao_001](https://cloud.githubusercontent.com/assets/8203476/21900505/34512810-d8db-11e6-8f7c-0168bec12d39.png)

**Comment by hvelarde** [comment]
boa! não conhecia esse hook; podemos começar usar ele em outros lugares :-)

**Comment by idgserpro** [comment]
Não sei como fizeram o cadastro anteriormente no readthedocs, mas só de adicionar o hook e efetuar um novo commit atualizou por lá.
