### ISSUE TITLE
Destaque do portal não carrega banner

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#333]
Após o commit https://github.com/plonegovbr/brasil.gov.portal/commit/9398317a11dad9424df2615f61a368c01659d2b0, que corrigiu o relato https://github.com/plonegovbr/brasil.gov.portal/issues/167, o portal deixou de carregar um banner como destaque.

Isso ocorre porque, após a correção, o portal passou a carregar como destaque, somente o que está dentro da ```div#em-destaque```, como pode ser visto [aqui](https://github.com/plonegovbr/brasil.gov.portal/commit/9398317a11dad9424df2615f61a368c01659d2b0#diff-4821267cdb39ee72beae41564fdfcfd9R176). A ```div#em-destaque``` é mostrada pela [tile de destaque](https://github.com/plonegovbr/brasil.gov.tiles/blob/34bf82cdc6034d39f65612cb4c2e19979e93337e/src/brasil/gov/tiles/tiles/templates/em_destaque.pt#L13).

No entanto, isso não é coerente com o [Manual de Gestão de Conteúdo](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/gestao-manual-portal-modelo-governo-federal-dez2014.pdf/view), que em sua página 222 diz que é possível inserir como destaque um banner, com a tile de Texto Rico. É necessário que o js carregue não somente o que está dentro da ```div#em-destaque```, mas também tudo que for mostrado pela tile de Texto Rico.

**Comment by hvelarde** [comment]
a solução seria trazer o conteúdo da `div#content` na chamada AJAX; parece algo simples mas pode provocar algum problema em sites existentes.

fiquem a vontade de incluir um novo PR com a correção.

**Comment by idgserpro** [comment]
Esse issue é duplicado de https://github.com/plonegovbr/brasil.gov.portal/issues/479 (inclusive eles referenciam o mesmo commit https://github.com/plonegovbr/brasil.gov.portal/commit/9398317a11dad9424df2615f61a368c01659d2b0 problemático, que já foi resolvido e mesclado em https://github.com/plonegovbr/brasil.gov.portal/pull/481.
