### ISSUE TITLE
Bug na exibição da data de criação nas coleções com a visão "summary view"

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.portal#335]
É o mesmo bug da issue #157. 

Template: brasil.gov.portal/src/brasil/gov/portal/browser/content/templates/custom_summary_view.pt

**Comment by idgserpro** [comment]
Com o fechamento de https://github.com/plonegovbr/brasil.gov.portal/issues/240, esse relato será fechado pois a visão de coleção e folder passa a ser unificada.

**Comment by hvelarde** [comment]
têm que apagar o stale branch, então.

**Comment by idgserpro** [comment]
Por isso ainda está aberto, quando tudo for fechado faz esse processo. Existem mais issues nessa situação.

**Comment by idgserpro** [comment]
Resolvido em

https://github.com/plonegovbr/portalpadrao.release/releases/tag/1.2

https://github.com/plonegovbr/portal.buildout/releases/tag/1.2

Com a atualização para plone.app.contenttypes 1.1.1, a visão de coleção passa a usar a mesma dos diretórios, que já possui essa correção, portanto o relato pode ser fechado.
