### ISSUE TITLE
Problema update  release : de 1.0.5 para 1.1.5.2.

### ISSUE THREAD

**Issue by makelli** [plonegovbr/brasil.gov.portal#336]
Atualizei a release de 1.0.5 para 1.1.5.2. Ao tentar fazer upgrade do brasil.gov.br   (vi em algum lugar que este deve ser o primeiro a ser feito up)

 .gov.br: Portal Padrão 1.1.5.1
Portal Padrão de sites para o Governo Federal
 Este produto foi atualizado. Versão anterior do profile era 10500 Nova versão do profile é 10801 Atualizar:brasil.gov.portal
    

Aqui está a mensagem de erro completa:
Visualizar traceback como texto
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFCore.FSPythonScript, line 127, in __call__
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.PythonScripts.PythonScript, line 344, in _exec
Module script, line 11, in prefs_reinstallProducts
<FSPythonScript at /ifce/portal_quickinstaller/prefs_reinstallProducts>
Line 11
Module Products.CMFPlone.QuickInstallerTool, line 101, in upgradeProduct
Module Products.GenericSetup.upgrade, line 166, in doStep
Module brasil.gov.portal.upgrades.v10700.handler, line 153, in corrige_conteudo_collectivecover
Module brasil.gov.portal.upgrades, line 16, in upgrade_profile
Module Products.GenericSetup.upgrade, line 166, in doStep
Module collective.cover.upgrades.v13, line 49, in update_references
Module collective.cover.events, line 48, in update_link_integrity
Module collective.cover.content, line 146, in get_referenced_objects
Module collective.cover.content, line 122, in get_tile
[Module collective.cover.content, line 109, in get_tile_type](https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/content.py#L109)
AssertionError

**Comment by idgserpro** [comment]
Obrigado por reportar o erro.

Você possui algum outro plugin instalado na sua instalação? Você está usando as versões de dependências como definido em https://github.com/plonegovbr/portalpadrao.release?

**Comment by makelli** [comment]
Não possuo plugin. Sim, estou usando usando as versões de dependências como definido em https://github.com/plonegovbr/portalpadrao.release

**Comment by idgserpro** [comment]
Você poderia editar os arquivos fonte da aplicação temporariamente? Lembre-se de fazer um backup antes do arquivo!!!

Poderia editar o arquivo

`collective.cover-1.1b1-py2.7.egg/collective/cover/content.py`

Adicionando, [antes da linha que dá erro](https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/content.py#L109), o seguinte trecho de código:

```python
for t in self.get_tiles():
    print t
```

Rodar novamente a atualização e postar o que foi impresso no terminal?

**Comment by hvelarde** [comment]
o problema é provocado por algum tile com `id` duplicado e isso foi corrigido já.

sugiro identificar os tiles envolvidos, remover e adicionar novamente; depois tentar a atualização novamente.

**Comment by makelli** [comment]
Obrigada! Funcionou

**Comment by idgserpro** [comment]
Seria o caso de comentar esse `assert` indicando esse tipo de situação, velarde?

@makelli como você já resolveu o problema, fecharemos o relato.

**Comment by hvelarde** [comment]
@idgserpro sinceramente não sei se vale o esforço; a ideia do `assert` e essa mesma: falhar par mostrar um problema.

**Comment by idgserpro** [comment]
Sim, mas eu por exemplo lendo o código não consegui inferir essa análise que você fez, por isso a sugestão do comentário. Bem, pelo menos com o cadastro dessa issue, se mais pessoas tiverem o problema será indexado pelos buscadores o traceback encontrado.
