### ISSUE TITLE
Tamanho da fonte pequena no popup da busca de conteúdos no editor TinyMCE

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.portal#344]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?

Portal Padrão 1.1.6.dev0

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? Se sim, forneça o nome e as versões utilizadas.

- [ ] Sim
Nome e versões dos plugins:

- [x] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [x] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?

Editar um conteúdo que tenha texto rico e fazer um link ou adicionar um imagem no texto.

![01](https://cloud.githubusercontent.com/assets/1719539/23488272/540865e6-feca-11e6-9935-7519b5cc32c4.png)

**Comment by hvelarde** [comment]
migrado para o issue tracker do brasil.gov.temas.

**Comment by hvelarde** [comment]
reabrindo aqui, acho que o que não faz sentido é a outra issue;
