### ISSUE TITLE
Problemas ao copiar página que contém links internos

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.portal#345]
1. Todos os testes foram efetuados utilizando o portal.buildout com IDG puro sem plugins extras; 
2. Foi testado nas versões 1.1.3.1, 1.1.4, 1.1.5.2 - ERRO;
3. Foi testado no Plone puro com Dexterity e com Archetypes - OK;
4. Foi testado em portais sem o IDG - OK;

Pessoal um provedor de conteúdos achou um erro no provimento de conteúdos no IDG, aonde gera a quebra de links nas páginas.

Fiz o teste em outros portais **que não utilizam o IDG** e não ocorre quebra de links. 

### Quais são os passos para reproduzir o problema?

Considerado a estrutura do IDG:

1º nível - Assuntos    
1º nível - Notícias
2º nível - Editoria B
3º nível - Pagina Teste
3º nível - Arquivo Teste

1 - Na página "Página Teste" foi criado um link interno para o "Arquivo Teste", utilizando o editor TinyMCE:

![1](https://cloud.githubusercontent.com/assets/1719539/25721914/8879ea02-30e8-11e7-9d55-b172eaaca578.png)

2 - Na pagina de visão o link é selecionado e copiado (Ctrl + C):

![2](https://cloud.githubusercontent.com/assets/1719539/25721999/ddd74e9a-30e8-11e7-8a79-1e1e4716b501.png)

3 - Na página "Pagina Teste" clique em editar e cole o texto  abaixo do outro:

![3](https://cloud.githubusercontent.com/assets/1719539/25722107/4d9cf4fa-30e9-11e7-94d7-d51af2f73023.png)
 
4 - Se selecionar o link e clicar no ícone do "inserir/editar hyperlink" verá que ele esta apontando para o arquivo "Arquivo Teste", feche o popup sem clicar no botão OK, mas salve as alterações da página:

![4](https://cloud.githubusercontent.com/assets/1719539/25722212/b7768c9c-30e9-11e7-900a-9292bd4da084.png)

5 - Após salvar, o link colado perderá o path:

* Link correto -  http://localhost:8383/Plone/assuntos/editoria-b/arquivo-teste.pdf
* Link colado - http://localhost:8383/Plone/arquivo-teste.pdf

* Link correto - http://localhost:8383/Plone/noticias
* Link colado - http://localhost:8383/noticias

![5](https://cloud.githubusercontent.com/assets/1719539/25723000/9c980b46-30ec-11e7-8858-a168d8e28dc7.png)

6 - O path também perderá se eu copia e colar os links em uma outra página " Página Inicial > Acesso à Informação > Licitações e contratos ":

* http://localhost:8383/assuntos/editoria-b/arquivo-teste.pdf
* http://localhost:8383/noticias

![6](https://cloud.githubusercontent.com/assets/1719539/25723094/0347e816-30ed-11e7-9230-b16e6b626a98.png)

7 - Uma solução de contorno para corrigir os links é:

1. após o provedor colar o link ele tem que selecionar o texto;
2. clicar no ícone de "inserir/editar hyperlink" 
3. depois clicar no botão "Ok". 

As vezes esse procedimento não funciona e tem que refazer o link.

![7](https://cloud.githubusercontent.com/assets/1719539/25723256/affb5be2-30ed-11e7-9987-60e0623e3477.png)

8 - Os testes que efetuei em outras instalações sem o IDG ao copiar e colar o href fica ../../, mas o link não quebra, o teste abaixo foi efetuado em um plone puro os links não quebraram:

![8](https://cloud.githubusercontent.com/assets/1719539/25724080/ec91e640-30f0-11e7-86f7-9af95e9c9f23.png)

**Comment by idgserpro** [comment]
Resolvido em

https://github.com/plonegovbr/portalpadrao.release/releases/tag/1.2

https://github.com/plonegovbr/portal.buildout/releases/tag/1.2

Com a atualização para plone.app.contenttypes 1.1.1 (atualizado no release 1.2 do IDG). Testei apenas no Chrome, já que não foi indicado aqui qual navegador foi usado. Favor testar novamente no novo release 1.2 e, caso o problema ocorra novamente, reabra o relato.
