### ISSUE TITLE
Atualizar collective.upload para 9.18.0rc2

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#350]
O novo release é uma revisão maior do pacote com várias melhorias e correções de bugs:

https://pypi.python.org/pypi/collective.upload/9.18.0rc2

**Comment by claytonc** [comment]
A atualização resolve o #286 e #300 que foram fechados e resolvidos no collective.upload, mas não foram resolvidos no IDG que continua com a versão do collective.upload = 1.0rc1 desde da 1.0.5 do brasil.gov.portal.

**Comment by claytonc** [comment]
Sem essa correção os usuários não conseguirão utilizar o workflow corretamente utilizando as permissões do Plone ou criando novos workflows.

**Comment by hvelarde** [comment]
@claytonc temos ainda umas customizações do template do collective.upload aqui:

https://github.com/plonegovbr/brasil.gov.portal/tree/master/src/brasil/gov/portal/browser/upload

eu não estou lembrando o motivo disso, mas acho que se atualizar para 9.18.0rc2 resolvemos, sempre que seja possível para o usuário adicionar os direitos diretamente.

opiniões? @rodfersou @idgserpro

**Comment by idgserpro** [comment]
Nós não fizemos essas customizações portanto não sabemos as motivações e o risco de sua remoção... Pelo que aprendemos nesse processo, existem customizações que corrigem problemas por não poder esperar o *upstream*, mas existem outras que foram demandadas pela SECOM por algum motivo. Por isso, o mais correto seria comparar essas customizações com o que tem hoje e tentar deduzir isso. Por isso é importante que toda customização feita tenha o histórico da motivação.

De qualquer forma, é interessante também testar uma instância IDG (hoje na versão 1.3), com o portal já criado, e atualizar só o collective.upload, para ver o tipo de problema que pode dar com o jsregistry.xml (pois muitos javascripts foram alterados) para ver se não é necessária a adição de mais um passo nos upgradeSteps.

**Comment by hvelarde** [comment]
não da para testar com o novo collective.upload pois da erro; teria que ser uma versão anterior.

pelo que vi o @rodfersou esteve envolvido nisso, ele vai ter que lembrar.

**Comment by rodfersou** [comment]
Foi para [adicionar os direitos no upload do arquivo](https://github.com/plonegovbr/brasil.gov.portal/commit/f7de6c8310c31593ac775cd41873674e1d291e21).

Isso ja está incorporado na última versão do c.upload, a customização pode ser removida

**Comment by hvelarde** [comment]
acabei de revisar o histórico e as customizações foram feitas por 2 motivos:

* adicionar campo Creators no formulário (implementado upstrem em https://github.com/collective/collective.upload/issues/34)
* corrigir problema de permissão no template folder_contents (implementado upstream em https://github.com/collective/collective.upload/issues/65)

essas duas mudanças foram inclusas na versão 1.2b1 do collective.upload; após isso tivemos vários releases que corrigiram outros problemas e modernizaram o plugin com a nova versão do JS.

se tudo mundo concordar sugiro também remover as customizações e atualizar até a versão 9.18.0rc2 como proposto aqui.

**Comment by idgserpro** [comment]
Minha preocupação é se com a atualização dos javascripts nesse plugin não teríamos problemas de conflito com todas as nossas dependências no IDG, por isso comentei do teste de uma versão 1.3 com o collectve.upload e depois atualizando para a 9.18.0rc2, rodando upgradeSteps, pra ver se não escapou algo que pode dar dor de cabeça no futuro.

Numa visão mais "reativa", poderia atualizar para o 1.2b1 e na 2.0 do IDG atualizar para a 9.18.0rc2, mas como são vocês atuando, testando bem acho que pode sim ir pra 9.18.0rc2.

**Comment by hvelarde** [comment]
a preocupação é válida mas não acho nada que indique que isso possa acontecer; a nvoa versão do collective.upload está sendo usada em produção faz tempo em outros sites e não tivemos nenhum problema relatado que não tenha sido resolvido ainda.

mas vamos testar sim manualmente após mesclar as mudanças.

**Comment by hvelarde** [comment]
@claytonc o PR ainda não foi mesclado.
