### ISSUE TITLE
Data de publicação inválida gera erro de exibição de arquivos

### ISSUE THREAD

**Issue by luizgsbraz** [plonegovbr/brasil.gov.portal#353]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?
```
    Portal Padrão 1.1.5.1

    Plone 4.3.9 (4313)

    CMF 2.2.9

    Zope 2.13.24

    Python 2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]

    PIL 2.7.0 (Pillow)
```
![biblioteca_produtos](https://user-images.githubusercontent.com/7255936/27404850-f05b0e66-56a5-11e7-850e-2eee1d4640dd.png)

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? Se sim, forneça o nome e as versões utilizadas.

- [X] Sim
Nome e versões dos plugins:
https://gitlab.com/gpwebcgti/pf.bibpf.tema/tags/1.1.3
https://gitlab.com/gpwebcgti/pf.internet.tiles/tags/1.0.5

- [ ] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [ ] Sim
- [x] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [x] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
1) Criar um arquivo com data de publicação inválida e salvar

![erro-data-publicao](https://user-images.githubusercontent.com/7255936/27405836-79a41552-56a9-11e7-8756-471df5af50af.png)

### Qual é o retorno esperado? O que você vê ao contrário do esperado?
Esperado:
Visualização normal do arquivo 
Visualização normal da pasta no modo "Summary View" 

Obtido:
1) A página que exibe o arquivo apresentará a mensagem: error while rendering plone.belowcontenttitle.documentbyline 
![erro-exibicao-arquivo](https://user-images.githubusercontent.com/7255936/27405903-b250d9e4-56a9-11e7-8546-cdbbc270b385.png)

2) A visualização default da pasta onde se encontra o arquivo apresenta erro.
![erro-exibicao-pasta](https://user-images.githubusercontent.com/7255936/27405949-dcb53108-56a9-11e7-8bf2-5d998157f0c3.png)

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.
Na visualização do arquivo apareceu apenas a mensagem abaixo logo abaixo do Título do Arquivo:
"error while rendering plone.belowcontenttitle.documentbyline "
```
Na visualização da pasta apareceu o seguinte trace:
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 3193dc68d15a0c16924a2296f4a26e3f, line 1782, in render
  Module d3e3159c789f82e2cace2d0299650813, line 1393, in render_master
  Module d3e3159c789f82e2cace2d0299650813, line 560, in render_content
  Module 3193dc68d15a0c16924a2296f4a26e3f, line 1762, in __fill_content_core
  Module 3193dc68d15a0c16924a2296f4a26e3f, line 1666, in render_listing
  Module 6e7265d06a16006a437faf0e1770b5e8, line 120, in render_content_core
  Module 6e7265d06a16006a437faf0e1770b5e8, line 959, in render_listing
  Module 3193dc68d15a0c16924a2296f4a26e3f, line 1649, in __fill_entries
  Module 6e7265d06a16006a437faf0e1770b5e8, line 474, in render_entries
  Module 3193dc68d15a0c16924a2296f4a26e3f, line 1435, in __fill_entry
  Module Products.CMFPlone.browser.ploneview, line 41, in toLocalizedTime
  Module Products.CMFPlone.TranslationServiceTool, line 89, in ulocalized_time
  Module Products.CMFPlone.i18nl10n, line 205, in ulocalized_time
  Module DateTime.DateTime, line 1551, in strftime
ValueError: 'getField'

 - Expression: "python:toLocalizedTime(itemDate)"
 - Filename:   ... ov/portal/browser/plone/templates/folder_summary_view.pt
 - Location:   (line 125: col 67)
 - Source:     ... tal:replace="python:toLocalizedTime(itemDate)">16/08/2001</s ...
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "nocall:context/aq_explicit/text/output"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f34b6463d90>
               views: <ViewMapper - at 0x7f34ae624610>
               modules: <instance - at 0x7f34c2f0cd40>
               args: <tuple - at 0x7f34ca812050>
               here: <ImplicitAcquisitionWrapper bugado at 0x7f34b86ffb40>
               user: <ImplicitAcquisitionWrapper - at 0x7f34b49effa0>
               nothing: <NoneType - at 0x937be0>
               container: <ImplicitAcquisitionWrapper bugado at 0x7f34b86ffb40>
               request: <instance - at 0x7f34b4a00d40>
               wrapped_repeat: <SafeMapping - at 0x7f34adafa4c8>
               traverse_subpath: <list - at 0x7f34ac132290>
               default: <object - at 0x7f34ca72e520>
               loop: {...} (2)
               context: <ImplicitAcquisitionWrapper bugado at 0x7f34b86ffb40>
               view: <SimpleViewClass from /opt/zope/portal.buildout/eggs/brasil.gov.portal-1.1.5.1-py2.7.egg/brasil/gov/portal/browser/plone/templates/folder_summary_view.pt folder_summary_view at 0x7f34ada95410>
               translate: <function translate at 0x7f34b5191ed8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f34adba10f0>
               options: {...} (0)
               target_language: pt_BR
```

**Comment by idgserpro** [comment]
Com a atualização para plone.app.contenttypes 1.1.1 em

https://github.com/plonegovbr/portalpadrao.release/releases/tag/1.2

https://github.com/plonegovbr/portal.buildout/releases/tag/1.2

O widget utilizado passa a ser do tipo select e não texto livre evitando esse erro, podendo o relato ser fechado.

Caso já possua um item cadastrado erroneamente e persistido, será necessário zerar a data: pode-se  editar o item, e salvar selecionando a opção '--' como data, tentar editar de novo e depois selecionar uma data correta.
