### ISSUE TITLE
Existe um roadmap de migração para o Plone 5?

### ISSUE THREAD

**Issue by tcurvelo** [plonegovbr/brasil.gov.portal#361]
Olá,
Gostaria de saber se já foram levantadas as pendências que precisam ser sanadas para uma eventual migração para o Plone 5.

**Comment by hvelarde** [comment]
o primeiro é resolver a situação do resource registry no Plone; após isso precisamos trabalhar na compatibilidade dos add-ons e um mecanismo de migração.

é muito importante ir organizando essas tarefas, tu topa ajudar?

**Comment by tcurvelo** [comment]
Tenho interessse em ajudar, mas não tenho experiência com Plone 5 ainda.
Algum link para essa situação do resource registry que vc se refere?

**Comment by hvelarde** [comment]
tem discussões intermináveis no https://community.plone.org/ e aqui; alguns exemplos

* https://community.plone.org/t/the-incredible-and-sad-tale-of-innocent-plone-5-and-its-heartless-add-ons/1437
* https://github.com/plone/Products.CMFPlone/issues/1896
* https://github.com/plone/Products.CMFPlone/issues/1955

é realmente complicado e atualmente não está funcionando bem se tu não é um guru de JS.

**Comment by idgserpro** [comment]
Algumas referências de dependências, como o collective.cover: https://github.com/collective/collective.cover/issues/642

**Comment by hvelarde** [comment]
@tcurvelo eu gostaria de ir pensando em um roadmap para atualziação ao Plone 6; ele tem que incluir compatibilidade dos complementos, analise da situação atual de gerenciamento de recursos estáticos e compatibilidade com o Python 3.

tu quer liderar essa iniciativa?

**Comment by tcurvelo** [comment]
Opa @hvelarde , desculpa a demora em responder.
Eu estou meio alheio ao desenvolvimento atual do Plone...  não creio ser a pessoa mais indicada.
Mas eu tenho interesse em ajudar. Que links vc me indica para eu ir me atualizando sobre o assunto?

**Comment by hvelarde** [comment]
olha, estamos agora trabalhando na portabilidade do código para o Python 3; cada pacote tem um PR para atender esse requerimento.

um pouco mais na frente vamos fazer uma lista de coisas necessárias para fazer acontecer.

**Comment by hvelarde** [comment]
@tcurvelo olha, temos que avaliar estas coisas em todos os plugins usados:

mudanças no Plone 5.0
* bundles JS/CSS
* proteção CSRF
* plone.app.stagingbehavior
* ícones de tipos de conteúdo

mais informação: https://docs.plone.org/develop/addons/upgrade_to_50.html

mudanças no Plone 5.1

* código de instalação/desinstalação
* escalas de imagens HiDPI
* integração do collective.indexing
* remoção do CMFDefault

mais informação: https://docs.plone.org/develop/addons/upgrade_to_51.html 

vou abrir depois issues aqui mesmo.
