### ISSUE TITLE
Problema Upgrade step (Browserlayer Remove the browserlayer, which is not needed anymore. 	(10800 → 10801))

### ISSUE THREAD

**Issue by makelli** [plonegovbr/brasil.gov.portal#363]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?
Portal Padrão 1.1.5.1
### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? Se sim, forneça o nome e as versões utilizadas.

- [ ] Sim
Nome e versões dos plugins:

- [X ] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [X ] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [ ] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
Realizar o seguinte passo de upgrade 

Remove Browserlayer
      Remove the browserlayer, which is not needed anymore. | (10800 → 10801)
-- | --

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 1034, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module brasil.gov.portal.upgrades.v10801.handler, line 71, in remove_browserlayer

**Comment by idgserpro** [comment]
@makelli favor informar o erro que ocorreu. A traceback não está completo.

**Comment by makelli** [comment]
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 1034, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module brasil.gov.portal.upgrades.v10801.handler, line 71, in remove_browserlayer
AttributeError: type object 'IBrowserLayer' has no attribute 'getName'

**Comment by idgserpro** [comment]
@makelli você está utilizando o versions.cfg da versão 1.1.5.1?

https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.5.1/versions.cfg

Você instalou/reinstalou algum produto manualmente no portal_quickinstaller?

**Comment by makelli** [comment]
Sim utilizo a versão 1.1.5.1. Não reinstalei nenhum produto

**Comment by idgserpro** [comment]
@makelli por favor adicione

`print Ilayer`

antes da linha `if Ilayer.getName() == 'OEmbedLayer':` em https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/upgrades/v10801/handler.py#L69 no pacote em seu disco e execute novamente o upgradeStep para que possamos descobrir qual layer está dando problema.

**Comment by makelli** [comment]
<InterfaceClass brasil.gov.portal.interfaces.IBrasilGov>
<class 'brasil.gov.facetada.interfaces.IBrowserLayer'>

**Comment by makelli** [comment]
2017-07-14 11:18:31 INFO PloneFormGen Patching plone.app.portlets ColumnPortletManagerRenderer to not catch Retry exceptions
2017-07-14 11:18:31 INFO Zope Ready to handle requests
2017-07-14 11:18:31 WARNING OFS.Uninstalled Could not import class 'IBrowserLayer' from module 'brasil.gov.facetada.interfaces'
<InterfaceClass plone.app.z3cform.interfaces.IPloneFormLayer>
<InterfaceClass zope.interface.Interface>
<InterfaceClass plone.app.discussion.interfaces.IDiscussionLayer>
<InterfaceClass collective.js.jqueryui.interfaces.IJqueryUILayer>
<InterfaceClass plone.app.contenttypes.interfaces.IPloneAppContenttypesLayer>
<InterfaceClass plone.app.theming.interfaces.IThemingLayer>
<InterfaceClass plone.app.blocks.interfaces.IBlocksLayer>
<InterfaceClass collective.cover.interfaces.ICoverLayer>
<InterfaceClass collective.portlet.calendar.browser.interfaces.ICalendarExLayer>
<InterfaceClass brasil.gov.agenda.interfaces.IBrowserLayer>
<InterfaceClass brasil.gov.barra.interfaces.IBarraInstalada>
<InterfaceClass brasil.gov.vcge.interfaces.IVCGEInstalado>
<InterfaceClass Products.Doormat.browser.interfaces.IDoormatLayer>
<InterfaceClass sc.embedder.interfaces.IEmbedderLayer>
<InterfaceClass sc.social.like.interfaces.socialikes.ISocialLikeLayer>
<InterfaceClass collective.z3cform.widgets.interfaces.ILayer>
<InterfaceClass collective.nitf.interfaces.INITFLayer>
<InterfaceClass brasil.gov.tiles.interfaces.IBrasilGovTiles>
<InterfaceClass collective.upload.interfaces.IUploadBrowserLayer>
<InterfaceClass brasil.gov.portal.interfaces.IBrasilGov>
<class 'brasil.gov.facetada.interfaces.IBrowserLayer'>
Parou na  <class 'brasil.gov.facetada.interfaces.IBrowserLayer'>

**Comment by makelli** [comment]
A lista completa de registered_layers é esta:

<InterfaceClass plone.app.z3cform.interfaces.IPloneFormLayer>
<InterfaceClass zope.interface.Interface>
<InterfaceClass plone.app.discussion.interfaces.IDiscussionLayer>
<InterfaceClass collective.js.jqueryui.interfaces.IJqueryUILayer>
<InterfaceClass plone.app.contenttypes.interfaces.IPloneAppContenttypesLayer>
<InterfaceClass plone.app.theming.interfaces.IThemingLayer>
<InterfaceClass plone.app.blocks.interfaces.IBlocksLayer>
<InterfaceClass collective.cover.interfaces.ICoverLayer>
<InterfaceClass collective.portlet.calendar.browser.interfaces.ICalendarExLayer>
<InterfaceClass brasil.gov.agenda.interfaces.IBrowserLayer>
<InterfaceClass brasil.gov.barra.interfaces.IBarraInstalada>
<InterfaceClass brasil.gov.vcge.interfaces.IVCGEInstalado>
<InterfaceClass Products.Doormat.browser.interfaces.IDoormatLayer>
<InterfaceClass sc.embedder.interfaces.IEmbedderLayer>
<InterfaceClass sc.social.like.interfaces.socialikes.ISocialLikeLayer>
<InterfaceClass collective.z3cform.widgets.interfaces.ILayer>
<InterfaceClass collective.nitf.interfaces.INITFLayer>
<InterfaceClass brasil.gov.tiles.interfaces.IBrasilGovTiles>
<InterfaceClass collective.upload.interfaces.IUploadBrowserLayer>
<InterfaceClass brasil.gov.portal.interfaces.IBrasilGov>
<class 'brasil.gov.facetada.interfaces.IBrowserLayer'>
<InterfaceClass brasil.gov.portlets.interfaces.IBrowserLayer>
<InterfaceClass brasil.gov.paginadestaque.interfaces.IBrowserLayer>
<InterfaceClass collective.carousel.interfaces.ICollectiveCarouselLayer>
<InterfaceClass Products.PloneSurvey.browser.interfaces.IPloneSurveySpecific>

**Comment by idgserpro** [comment]
@makelli o pacote brasil.gov.facetada não é instalado por padrão. Esse erro parece que você tinha uma instância que tinha o brasil.gov.facetada instalado em algum momento, mas agora não está mais presente na seção `eggs +=` de seu buildout: ou seja, tem uma browserlayer persistida no ZODB, mas o código python equivalente não está disponível, por isso recebe `None` ao executar `getName()`. 

Você precisa adicionar o brasil.gov.facetada na seção `eggs` de seu buildout. Adicione, rode o buildout e nos informe se o erro permanece.

**Comment by makelli** [comment]
Coloquei o pacote brasil.gov.facetada no egg e o upgradeStep funcionou corretamente. Muito obrigada
