### ISSUE TITLE
Caixa textual de busca não funcionando 

### ISSUE THREAD

**Issue by makelli** [plonegovbr/brasil.gov.portal#364]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?
brasil.gov.portal-1.1.5.1
### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? (IMPORTANTE: Pacotes apresentados [no manual de funcionalidades avançadas](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/manual-de-funcionalidades-avancadas-para-portais-plone_dez2014.pdf), mesmo que estejam no prefixo brasil.gov.\*, são considerados plugins adicionais). Caso sua resposta seja sim, forneça o nome e as versões utilizadas.

- [ ] Sim
Nome e versões dos plugins:

- [X ] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [X ] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [ ] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
Não é possível digitar nenhuma informação na caixa de texto da busca (<input name="SearchableText" type="text" size="18" title="Buscar no portal" placeholder="Buscar no portal" class="searchField" id="searchGadget" autocomplete="off">)
### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.
grokcore.view-2.9-py2.7.egg/grokcore/view/templatereg.py:265: UserWarning: Found the following unassociated template after configuration: /home/makelli/portal.buildout/eggs/brasil.gov.portal-1.1.5.1-py2.7.egg/brasil/gov/portal/browser/viewlets/templates/searchbox.pt
  warnings.warn(msg, UserWarning, 1)

**Comment by idgserpro** [comment]
Qual navegador você está usando? Aparece algum erro de javascript no browser? Acabei de montar uma instância 1.1.5.3 e o erro não ocorre, nem no Firefox nem no Chrome.

Só um adendo: o **pacote** brasil.gov.portal está na versão 1.1.5.1, mas o **release** do IDG com todas as suas dependências está na versão 1.1.5.3. Leia https://github.com/plonegovbr/portalpadrao.release/#user-content-como-escolher-corretamente-o-arquivo-de-versões-de-um-release para maiores informações sobre esse processo.

**Comment by makelli** [comment]
O erro ocorre neste trecho:

<div id="portal-searchbox">
<form id="livesearch0" action="http://ifce.edu.br/@@busca">
<fieldset class="LSBox">
<legend class="hiddenStructure">Buscar no portal</legend>
<label class="hiddenStructure" for="searchGadget">Buscar no portal</label>
<input id="searchGadget" class="searchField" name="SearchableText"
size="18" title="Buscar no portal" placeholder="Buscar no portal"
autocomplete="off" type="text">
<input class="searchButton" value="Buscar no portal" type="submit">
</fieldset>
<input name="_authenticator"
value="fd8a2ab67cf7f4b8547f6a53b1b444cec2a77042" type="hidden">
</form>
</div>

2017-07-28 11:34 GMT-03:00 idgserpro <notifications@github.com>:

**Comment by idgserpro** [comment]
Graças ao apoio do [Alexandre Chagas na lista plonegovbr](colab.interlegis.leg.br/archives/thread/plonegov-br/ajuda-portal-searchbox#msg-160452), entendemos que o problema descrito aqui é duplicado da issue https://github.com/plonegovbr/brasil.gov.portal/issues/237 e portanto esse relato será fechado. Na issue relacionada tem o motivo do problema.
