### ISSUE TITLE
Erro ao visualizar indice de data de evento

### ISSUE THREAD

**Issue by shogunbr** [plonegovbr/brasil.gov.portal#365]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?
Portal Padrão 1.1.5.1
Plone 4.3.9 (4313)
CMF 2.2.9
Zope 2.13.24
Python 2.7.3 (default, Apr 10 2013, 05:46:21) [GCC 4.6.3]
PIL 2.7.0 (Pillow)

Ubuntu 12.04 ou Debian 8

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? (IMPORTANTE: Pacotes apresentados [no manual de funcionalidades avançadas](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/manual-de-funcionalidades-avancadas-para-portais-plone_dez2014.pdf), mesmo que estejam no prefixo brasil.gov.\*, são considerados plugins adicionais). Caso sua resposta seja sim, forneça o nome e as versões utilizadas.

- [ ] Sim
Nome e versões dos plugins:

- [x] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [x] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [ ] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
1 - Seu sistema operacional deve estar com timezone GMT-3.
2 - Crie um evento com a data inicial ou final 31/01/2018 00:00
4 - Vá até a ZMI e navegue no portal_catalog no índice start ou end respectivo e clique em browse

### Qual é o retorno esperado? O que você vê ao contrário do esperado?
Não sei se o problema é ao indexar ou ao visualizar a data, mas aparentemente ao converter a data de GMT-3 para UTC, ao invés de ir do dia 31/01 para o dia 01/02, ele tá indo para o dia 0/02:
DateError: Invalid date: (2018, 2, 0, 3, 0, 0, 'UTC')

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.
2017-07-28 18:46:42 ERROR Zope.SiteErrorLog 1501256802.620.642759691191 http://10.10.12.165:8080/Plone/portal_catalog/Indexes/end/manage_browse
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module App.special_dtml, line 185, in _exec
  Module DocumentTemplate.DT_Let, line 77, in render
  Module DocumentTemplate.DT_In, line 606, in renderwb
  Module DocumentTemplate.DT_Util, line 210, in eval
   - __traceback_info__: DateTime
  Module <string>, line 1, in <module>
  Module DateTime.DateTime, line 440, in __init__
  Module DateTime.DateTime, line 812, in _parse_args
DateError: Invalid date: (2018, 2, 0, 3, 0, 0, 'UTC')

### Por favor forneça informações adicionais que possam complementar o seu relato.
Se o sistema tiver em uma timezone GMT positiva, por exemplo, Europeu, o erro se dá ao colocar a data em 01/01 00:00 e ele subtrai da data para o dia 0.
Não cheguei a testar no Plone sem o IDG.

**Comment by shogunbr** [comment]
Coloquei a timezone do sistema para UTC para testar e continua dando erro.

**Comment by idgserpro** [comment]
Saberia nos informar se, com a utilização do release 1.3, esse problema persiste? Atualizamos o plone.app.contenttypes para 1.1.1 e ele atualizou todos os tipos de conteúdo.

**Comment by shogunbr** [comment]
Fiz um breve teste com um site quase vazio e parece que resolveu, tanto nos eventos criados na 1.3, quanto nos eventos migrados da versao antiga pelo upgrade step.

**Comment by hvelarde** [comment]
obrigado!
