### ISSUE TITLE
É possível que os pacotes instalados não apareçam em "vermelho" no portal_quickinstaller se já estiverem instalados?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#368]
Alguém tem idéia se o único jeito de não ficar em vermelho é usando o reinstall? Criando um site 1.1.5.1 do zero:

![selecao_056](https://user-images.githubusercontent.com/8203476/30666738-ad73e064-9e2b-11e7-8a30-6ed003f5a083.png)

Atualizando uma versão 1.0.5 para `master` (no caso, 1.2b2.dev0):

![selecao_058](https://user-images.githubusercontent.com/8203476/30666766-c8e038f2-9e2b-11e7-9cad-34f25d1436bf.png)

E atualizando uma versão 1.1.5.1 criado do zero para `master` (no caso, 1.2b2.dev0):

![selecao_059](https://user-images.githubusercontent.com/8203476/30667045-9f15f790-9e2c-11e7-89b7-64b67161f3bf.png)

[Já sabemos que não é uma boa prática usar o reinstall](https://community.plone.org/t/when-was-using-reinstall-in-portal-quickinstaller-considered-harmful/4789/4) mas queria ver se existe uma forma de deixar isso mais explícito pro usuário final, mas não lembro se deixa de ficar vermelho apenas se clicar em reinstall.

**Comment by hvelarde** [comment]
ask @mauritsvanrees

**Comment by idgserpro** [comment]
@mauritsvanrees we know `portal_quickinstaller` is going to be removed in Plone 5, but we're still using Plone 4 and we have the situation you're seeing above: a package was updated, an upgradeStep was run but in this screen it stills shows and if the last version wasn't installed. What exactly "trigger" this number update here? Just a reinstall?

**Comment by mauritsvanrees** [comment]
Yes, a reinstall would update the version. But you do not want that: upgrade steps are better, more fine grained. But upgrade steps do not touch this version. So you can see here that for example '.gov.br Portal Padrão' was installed with version 1.1.5.1, and the file system is at version 1.2b2.dev0. From this screen you cannot see if there are any upgrade steps and if they have been applied.

You should normally ignore the `portal_quickinstaller` tool screen in the ZMI, and only look at the Add-ons control panel in the Plone UI.

I don't know what causes some of these products to show up in the installed list, yet have no 'version at install time'.

In Plone 5.1, the portal_quickinstaller tool is still there, even in new sites, but the Add-ons control panel in the Plone UI will not use any info from it. The plan is to remove the tool in Plone 6.

**Comment by idgserpro** [comment]
> You should normally ignore the portal_quickinstaller tool screen in the ZMI, and only look at the Add-ons control panel in the Plone UI.

This what we've been doing in our documentation and for integrators, but from time to time someone questions this situation, that's why we're crying for help: actually we look mainly into 'portal_setup` after your great PR. :)

Thanks anyway. I'm going to close this since I don't see too much future in this discussion.
