### ISSUE TITLE
Em algumas builds, temos o erro "AssertionError: Page should have contained text 'Add Cover' but did not", mas ao reiniciar a build ele some.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#370]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?

https://github.com/plonegovbr/brasil.gov.portal/tree/e4f44f7a57e618977b46f2d8216dfd4b876e1780 e https://github.com/plonegovbr/portal.buildout/tree/335bfce2665155333190fde4b414a36c2d50e1c6 durante o processo de geração do release 1.2.

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? (IMPORTANTE: Pacotes apresentados [no manual de funcionalidades avançadas](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/manual-de-funcionalidades-avancadas-para-portais-plone_dez2014.pdf), mesmo que estejam no prefixo brasil.gov.\*, são considerados plugins adicionais). Caso sua resposta seja sim, forneça o nome e as versões utilizadas.

- [ ] Sim
Nome e versões dos plugins:

- [X] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [X] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [X] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?

Ao rodar o teste integrado, algumas vezes ocorre errp apenas nesse teste: ao reiniciar a build, ele passa novamente.

### Qual é o retorno esperado? O que você vê ao contrário do esperado?

Todos os testes passarem.

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.

```
Failure in test Criar nova capa (test_capa.robot)
Traceback (most recent call last):
  File "/home/travis/build/plonegovbr/portal.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/travis/build/plonegovbr/portal.buildout/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Page should have contained text 'Add Cover' but did not
```

### Por favor forneça informações adicionais que possam complementar o seu relato.

Segue um job onde aconteceu o problema: https://travis-ci.org/plonegovbr/portal.buildout/jobs/279605986

**Comment by idgserpro** [comment]
```
 Set up plone.testing.z2.ZServer in 0.502 seconds.
  Set up brasil.gov.portal.testing.brasil.gov.portal:Acceptance in 0.000 seconds.
  Running:
    1/10 (10.0%)
==============================================================================
Test Capa                                                                     
==============================================================================
Criar nova capa                                                       
2017-10-18 20:54:50,504 - Zope.SiteErrorLog - ERROR - 1508360090.50.3894187145 http://localhost:55001/plone/++add++collective.cover.content
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 118, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module z3c.form.group, line 48, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module collective.z3cform.widgets.multicontent_search_widget, line 133, in update
AttributeError: can't set attribute
| FAIL |
Page should have contained text 'Add Cover' but did not
------------------------------------------------------------------------------
Test Capa                                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/travis/build/plonegovbr/portal.buildout/parts/test/test_capa/Criar_nova_capa/output.xml
```

**Comment by idgserpro** [comment]
Precisa resolver https://github.com/collective/collective.cover/pull/700 para corrigir o problema. Quando se atualiza para Plone 4.3.15 (em andamento em https://github.com/plonegovbr/portal.buildout/pull/77) e se roda o teste localmente, o erro ainda permanece, ou seja, precisa ser corrigido.

**Comment by idgserpro** [comment]
@hvelarde você pode corrigir esse erro no ```collective.cove```? Acho que é so substiuir:

```
Page Should Contain  Add Cover
```
por
```
Wait Until Page Contains Add Cover
```

aqui: https://github.com/collective/collective.cover/blob/3c4204b3b8d1e2387b4ddabfb06915960e6f0699/src/collective/cover/tests/cover.robot#L47

**Comment by hvelarde** [comment]
vocês também podem: não tem Contributor's Agreement ai ;)

**Comment by idgserpro** [comment]
Foi feito o commit https://github.com/collective/collective.cover/commit/1aa8680b235d5d723a1499afe82c83ec8697ab98

Assim que utilizarmos um release do cover > 1.6b4, podemos fechar esse relato.

**Comment by idgserpro** [comment]
@hvelarde Seria uma boa um release do collective.cover para colocarmos no release 1.5 do IDG e resolvermos esse erro que ocorre ocasionalmente em algumas builds.

**Comment by hvelarde** [comment]
eu queria corrigir outros problemas antes de fazer release.

**Comment by idgserpro** [comment]
Acho válido. Foi só pra lembrar mesmo.

**Comment by hvelarde** [comment]
tem um bem chato que isolamos ontem: https://github.com/collective/collective.cover/issues/765

só estou esperando o @rodfersou se desocupar para pegar essa tarefa.

**Comment by hvelarde** [comment]
corrigido em: https://github.com/plonegovbr/portal.buildout/pull/97
