### ISSUE TITLE
Precisamos realmente de um setup de CI tão complexo?

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#378]
Estou trabalhando em atualizar a versão do Plone para 4.3.15 e estou encontrando muitos problemas na hora de testar; eu não estou lembrando a motivação de tanta complexidade e gostaria retomar o ponto.

* o Travis gera 3 builds para o buildout (MASTER, VERSIONS_SEM_EXTENDS e LAST_RELEASE)
* o Travis gera 2 builds para as dependências (MASTER e PENDING_RELEASE)

mas as substituições parecem estar erradas pois passamos de trabalhar com um arquivo que inclui pinagens tanto para Plone quanto para produtos de terceiros, para um arquivo que só inclui pinagens do Plone; isso está provocando falhas no build MASTER, como pode ser visto aqui:

https://travis-ci.org/plonegovbr/portal.buildout/builds/289527076

por outro lado, eu não acho muito interessante essa opção de pending release nas dependências; acho que só complica e que pode ser resolvida simplesmente testando a nova versão; adicionei para isso o script `bin/test-dependencies` no portal.buildout com essa finalidade.

**Comment by hvelarde** [comment]
@idgserpro gostaria ter uma conferência com vocês sobre este quesito amanhã de manhã se for possível.

**Comment by idgserpro** [comment]
O erro foi resolvido em https://github.com/plonegovbr/portal.buildout/pull/82. 

Com relação a toda essa estrutura de CI, ela foi toda criada baseada na experiência dos releases e dos problemas encontrados nos mesmos. As principais motivações/histórico estão em https://github.com/plonegovbr/portalpadrao.release/issues/11 e https://github.com/plonegovbr/portal.buildout/pull/53 e, em resumo, a CI atual serve para:

1. testar todos os pacotes no release que está para ser lançado;
2. testar as últimas versões de todas as dependências;
3. testar a situação de uso do arquivo unificado `versions-sem-extends.cfg`.

No passado, ficava no buildout pinagens de releases fixos (exemplo: https://github.com/plonegovbr/brasil.gov.portal/blob/1.0.5/buildout.cfg#L5) e isso era ruim porque você desenvolvia no pacote mas referenciando dependências de um release antigo: ou seja, aí na hora que se ia lançar um release e se alterava essa url, dava erro em vários pacotes (em suma, não estava sendo feita a integração contínua do jeito correto). Pra piorar, cada pacote do plonegovbr tinha um buildout.cfg com extends completamente diferentes.

Dessa forma, formalizou-se o que já havia sido previsto em https://github.com/plonegovbr/portal.buildout/commit/b5ecff6d40b24163fccc6409f353f1c483952559, ou seja, o uso de https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg para novos releases e como última url do extends de todo pacote plonegovbr, assim a integração contínua sempre irá testar com todas as dependências previstas para aquele novo release. Todos os buildout.cfg foram padronizados (e com todo o esforço de fazer todas as builds passarem com essas alterações).

Uma coisa é o release que iremos lançar, outra coisa é o que está no master (últimas versões) de todos os pacotes e dependências que usamos. Pode ser que no futuro as diferenças entre o PENDING_RELEASE e MASTER fiquem mínimas? Sim, principalmente após a atualização do Plone para 4.3.15. Mas, conceitualmente, são contextos diferentes e necessários, porque agora temos mãos que podem ajudar no upgrade do Plone mas isso nem sempre é o caso (veja que hoje é 17/10/2016 e estamos na 4.3.9, lançada em 2016-04-05), por isso precisamos de dois jobs.

Em resumo: não é "complicado" simplesmente pelo fato de ser e sim porque nasceu de várias necessidades. :)

**Comment by hvelarde** [comment]
acho que o que temos que fazer é testar todos os pacotes do projeto no portal.buildout e tal vez remover o build PENDING_RELEASE nas dependências.

**Comment by idgserpro** [comment]
> acho que o que temos que fazer é testar todos os pacotes do projeto no portal.buildout e tal vez remover o build PENDING_RELEASE nas dependências.

Mas aí volta o problema que falamos de correr o risco de ver algum problema apenas quando for lançar o release. Como falamos, *nesse momento* que estamos atualizando o Plone para 4.3.15 teremos o PENDING_RELEASE igual ao MASTER, mas isso nem sempre é o caso e não temos como garantir porque nem sempre o release do Plone é atualizado num release do IDG.

Acredite, eu realmente gostaria que o CI de todos os pacotes fossem mais simples, com menos sed e etc, mas não quero simplificar e perder essa garantia de ver os erros quando eles acontecem, pois nunca se sabe se uma dependência pode impactar ou não um pacote.
