### ISSUE TITLE
Precisamos realmente da customização do viewlet de itens relacionados?

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#385]
Na implementação de #384 notei que temos um viewlet de itens relacionados que possivelmente já não é mais necessário após a atualização do Dexterity:

https://github.com/plonegovbr/brasil.gov.portal/blob/1.3/src/brasil/gov/portal/browser/viewlets/related.py

Podemos remover simplesmente a customização?

**Comment by hvelarde** [comment]
acabei de remover o viewlet em 9440f1d6272367dcf5841f1bd9bed87dd336ff56; precisamos testar na sequência.

**Comment by idgserpro** [comment]
Esse relato é duplicado, ver https://github.com/plonegovbr/brasil.gov.portal/issues/355. Mas como é você que está atuando, você pode decidir melhor qual fechar primeiro.

**Comment by hvelarde** [comment]
obrigado pelo esclarecimento; vamos remover então.
