### ISSUE TITLE
Testes falham com o collective.cover 1.6b3

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#388]
Ao rodar os testes de aceptação usando o collective.cover 1.6b3 acontecem erros em 2 testes na criação dos destaques:

https://travis-ci.org/plonegovbr/brasil.gov.portal/jobs/293883731

esses erros não acontecem na versão 1.6b2; o problema parece estar relacionado uma mudança feita para conseguir rodar os testes usando a versão mais recente do Plone:

* https://github.com/collective/collective.cover/issues/759
* https://github.com/collective/collective.cover/pull/700/files

eu considero esta issue um blocker para o release 1.4.

**Comment by hvelarde** [comment]
FYI @idgserpro @claytonc

**Comment by idgserpro** [comment]
Tentando adicionar manualmente funciona? O erro só ocorre na infra de testes?

**Comment by rodfersou** [comment]
O problema ocorre por que o campo `cover_layout` passou a ser readonly, e o pacote `transmogrify.dexterity` [ignora campos readonly](https://github.com/collective/transmogrify.dexterity/blob/1.6.1/transmogrify/dexterity/schemaupdater.py#L92-L93), o que fez com esse campo fique com o valor None

**Comment by rodfersou** [comment]
Comentei essas linhas do `transmogrify.dexterity` e ocorreu outra excessão:

```python
2017-10-30 17:07:59 ERROR Zope.SiteErrorLog 1509390479.00.80298053679 http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module brasil.gov.portal.browser.plone.admin, line 75, in __call__
  Module Products.CMFPlone.factory, line 105, in addPloneSite
  Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
   - __traceback_info__: profile-brasil.gov.portal:initcontent
  Module Products.GenericSetup.tool, line 1414, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1226, in _doRunImportStep
   - __traceback_info__: base-content
  Module brasil.gov.portal.setuphandlers, line 224, in importContent
  Module brasil.gov.portal.setuphandlers, line 22, in setupPortalContent
  Module collective.transmogrifier.transmogrifier, line 63, in __call__
  Module collective.transmogrifier.sections.savepoint, line 16, in __iter__
  Module collective.transmogrifier.sections.logger, line 39, in __iter__
  Module plone.app.transmogrifier.reindexobject, line 30, in __iter__
  Module plone.app.transmogrifier.browserdefault, line 24, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.refactor, line 87, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.refactor, line 50, in __iter__
  Module collective.jsonmigrator.mimetype, line 40, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.datafields, line 52, in __iter__
  Module plone.app.transmogrifier.uidupdater, line 34, in __iter__
  Module transmogrify.dexterity.schemaupdater, line 114, in __iter__
  Module zope.schema._bootstrapfields, line 226, in set
TypeError: Can't set values on read-only fields (name=cover_layout, class=collective.cover.content.Cover)
```

**Comment by rodfersou** [comment]
Se localmente eu deixar o campo sem ser readonly o processo de importação ocorre sem problemas

**Comment by rodfersou** [comment]
Acho que precisamos de 2 novas pipelines no transmogrify, uma para desmarcar esse campo do cover como readonly logo depois do constructor, e outra para marcar de volta como readonly quando a importação terminar.
https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/transmogrifier/conteudo.cfg

**Comment by idgserpro** [comment]
@hvelarde @rodfersou será que se colocamos o campo ```cover_layout``` como required False ao invés de readonly, os teste irão passar?

**Comment by rodfersou** [comment]
@idgserpro funcionaria, mas aparentemente a alteração para readonly é necessária por outros motivos, o @hvelarde pode entrar em mais detalhes.

**Comment by hvelarde** [comment]
@rodfersou readonly e required são coisas diferentes; acho que vamos precisar fazer mais um release do collective.cover corrigindo isso mas precisamos testar antes.

**Comment by idgserpro** [comment]
@rodfersou o readonly foi por causa disso:

https://github.com/collective/collective.cover/issues/759
e mais especificamente por causa disso:
https://github.com/plone/plone.app.testing/issues/39

**Comment by hvelarde** [comment]
se reverter o commit não vamos conseguir testar com a nova versão de Plone e todo o trabalho para atualizar vai ficar travado; sinceramente não sei o que fazer.

@idgserpro vocẽs tem ideia de como consertar o problema no `plone.app.testing`?

**Comment by idgserpro** [comment]
Já comentamos o que poderia ser feito em https://github.com/plone/plone.app.testing/issues/39#issuecomment-337960347 no plone.app.testing, pedimos um comentário do maurits mas ele nesse caso em específico acabou não respondendo.

**Comment by hvelarde** [comment]
não é mais simples vocês criarem um patch e eu criar um PR lá com isso? eu sei que vocês não fizeram por conta do Contributor Agreement, mas eu posso fazer.

mas temos que testar primeiro localemente contro o colver 1.6b2 e com as modificações no plone.app.testing.

**Comment by idgserpro** [comment]
Existe mais de uma proposta, por isso envolvemos o Maurits, a última envolve simplesmente adicionar o plone.autoform antes do TinyMCE em https://github.com/plone/plone.app.testing/blob/62b236e7ede8a0b5a4b6c75f17379a2ac342bd49/plone/app/testing/layers.py#L72.

**Comment by hvelarde** [comment]
com certeza ele não respondeu por falta de um PR; é bem mais simples analisar as mudanças desse jeito.
