### ISSUE TITLE
Documentar atualização a 1.4rc1

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#391]
Precisamos criar um documento listando as melhorias inclusas no release e os passos para atualizar com segurança.

**Comment by hvelarde** [comment]
isso se faz donde ou quando? na hora de fazer release? podemos falar as 17:00?

**Comment by idgserpro** [comment]
https://github.com/plonegovbr/portalpadrao.release#ações-para-um-novo-release
