### ISSUE TITLE
Conteúdo inicial com links quebrados 

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.portal#398]
O conteúdo inicial esta criando alguns links quebrados:

Topo:
- Perguntas frequentes
- Área de imprensa

Rodapé:
- Editoria A
- Editoria B
- Perguntas frequentes
- Área de imprensa

**Comment by hvelarde** [comment]
pelo que analisei aqui isso está quebrado faz tempo e não está relacionado com as últimas mudanças; vou mover para o release 1.5.

**Comment by agnogueira** [comment]
O conteúdo inicial será refeito no 2.0, não precisamos corrigir isso nessa versão
