### ISSUE TITLE
Seção de destaques "some" na versão 1.4rc1

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#401]
Versão 1.3:

![selecao_075](https://user-images.githubusercontent.com/8203476/32505239-de0c53b0-c3c8-11e7-8989-6e82c2c3d3fa.png)

Versão 1.4rc1:

![selecao_076](https://user-images.githubusercontent.com/8203476/32505245-e14f905a-c3c8-11e7-8e44-9d5203264d4a.png)

**Comment by hvelarde** [comment]
os destaques estão ai:

![screenshot-2017-11-7 destaques do portal](https://user-images.githubusercontent.com/341393/32511260-5e603c96-c3da-11e7-8c68-3778f2189d4a.png)

o problema é que esse conteúdo se carrega utilizando a opção `ajax_load=1` e isso, por alguma razão que desconheço, não está retornando o conteúdo esperado:

```javascript
$('#featured-content').load(portal_url + '/destaques?ajax_load=1 #content #em-destaque');
```

https://github.com/plonegovbr/brasil.gov.portal/blob/1.4rc1/src/brasil/gov/portal/static/js/main.js#L170-L179

![screen shot 2017-11-07 at 16 42 19](https://user-images.githubusercontent.com/341393/32511407-d173a51a-c3da-11e7-9fa8-4713e2dfc081.png)

a opção é trocar isso ai pelo seguinte:

```javascript
$('#featured-content').load(portal_url + '/destaques #em-destaque');
```

ai volta a funcionar:

![screenshot-2017-11-7 home](https://user-images.githubusercontent.com/341393/32511680-a259ae7c-c3db-11e7-9ffe-a97d44dff3e2.png)

**Comment by idgserpro** [comment]
@hvelade isso não vai carregar a página toda por js? Não seria melhor ter um view que retornasse somente os links e os títulos dos objetos?

**Comment by hvelarde** [comment]
isso vai carregar só o conteúdo da tag com id `#em-destaque` como indicado no JS; possivelmente não seja o ideal mas é o que da para fazer agora, fiquem a vontade de abrir uma nova issue para rever isso na frente.

eu preciso fazer o release 1.4 final, ainda hoje se possível.
