### ISSUE TITLE
Adicionar tipo de conteúdo Liveblog ao IDG

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#407]
[collective.liveblog](https://pypi.python.org/pypi/collective.liveblog) adiciona um tipo de conteúdo liveblog (uma ferramenta para cobertura ampla de um evento em curso) ao Plone; esse tipo de conteúdo será usado no IDG 2.0.

**Comment by idgserpro** [comment]
Não tenho opinião formada sobre a necessidade de adicionar esse pacote: se esse foi uma requisição da SECOM, então não há muito o que fazer, rs.
