### ISSUE TITLE
Adicionar tipo de conteúdo Galeria de fotos ao IDG

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#409]
[sc.photogallery](https://github.com/collective/sc.photogallery) adiciona um tipo de conteúdo Galeria de fotos com uma visão slideshow e descarga ao Plone; esse tipo de conteúdo será usado no IDG 2.0.

na migração a 2.0 será necessário migrar o conteúdo das pastas com a visão `galeria_de_fotos` aplicada, para este novo tipo de conteúdo e remover as customizações.

vamos precisar uma analise posterior mas a fundo.

**Comment by idgserpro** [comment]
Hoje não causa conflito sua instalação?

**Comment by hvelarde** [comment]
não tem por que causar conflito, é um tipo de conteúdo diferente.
