### ISSUE TITLE
Atualização de collective.portlet.calendar gera problemas

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#412]
após atualizar collective.portlet.calendar para 1.0b3 notei que um teste do brasil.gov.agenda está falhando:

```
Failure in test Test Navegacao Portlet Calendario (test_portlet_calendario_extendido.robot)
Traceback (most recent call last):
  File "/home/travis/build/plonegovbr/portal.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/travis/build/plonegovbr/portal.buildout/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in runTest
    assert last_status == 'PASS', last_message
AssertionError: ValueError: Element locator 'css=input[value="/agenda-do-presidente"]' did not match any elements.
```

refs. https://travis-ci.org/plonegovbr/portal.buildout/jobs/299396041

adicionalmente a visualização do portlet quebra:

![selection_023](https://user-images.githubusercontent.com/341393/32608838-bd4439fe-c544-11e7-88a0-849240d3bf3a.png)

Após atualizar a versão, ver também a necessidade de manter https://github.com/plonegovbr/brasil.gov.portal/blob/f793615579bcdd7093afaf00d9d60a7e5f431876/src/brasil/gov/portal/static/css/main.css#L1333 uma vez que esse mesmo código agora está upstream em https://github.com/collective/collective.portlet.calendar/blob/5124c819a9491a5de3f973672d22bb1ab263bcb0/collective/portlet/calendar/browser/calendar_styles/calendar.css#L17.

**Comment by hvelarde** [comment]
@claytonc pelo que vi aqui a atualização quebra outras coisas então não vou recomendar fazer isso em esta nova versão e fica pendente.

**Comment by claytonc** [comment]
@hvelarde
 
Fiz teste em em plone puro 4.3.15 o erro de leiaute não esta ocorrendo, pode ser algum css ou js do idg.

Mas esta ocorrendo o erro abaixo ao clicar nos links próximo ou mês anterior, mesmo na versão 1.0b2.

`KeyError: u'Cannot find object at path front-page'`

**Comment by claytonc** [comment]
@hvelarde 

O problema da quebra da visualização do portlet é porque esta pegando o tooltip do collective.js.bootstrap.

O plone.app.event 1.1.8 adiciona o tooltip [1], na versão anterior não tinha isso. 

https://github.com/plone/plone.app.event/blob/1.1.x/plone/app/event/portlets/portlet_calendar.js#L31-L34

**Comment by hvelarde** [comment]
tu quer consertar isso para uma versão nova?

**Comment by idgserpro** [comment]
Relacionado: https://github.com/plonegovbr/brasil.gov.agenda/issues/50

**Comment by claytonc** [comment]
@hvelarde @idgserpro 

Acho que encontrei um bug no portlet calendário comigo esta ocorrendo também em um plone puro. (Plone 4.3.15)

Favor gostaria que fizessem o mesmo teste para verificar se só esta ocorrendo comigo.

1 - Adicionem um portlet calendário (Calendário ou  Extended Calendar portlet) por exemplo no path assuntos/editoria-a/, pois na raiz o portlet funciona.
2 - Clique nos links "Mês anterior" e "Próximo mês" veja se não ocorreu o erro "KeyError: u'Cannot find object at path assuntos/editoria-a' "

**Comment by claytonc** [comment]
Após testes em outras instalações vi que é um bug.

https://github.com/plone/Products.CMFPlone/issues/2215

**Comment by idgserpro** [comment]
De qualquer forma, temos um erro no IDG também.

**Comment by claytonc** [comment]
@hvelarde 

Com relação aos testes, eles falham porque na versão 1.0b3 ouve a mudança abaixo:

https://github.com/collective/collective.portlet.calendar/blob/master/collective/portlet/calendar/calendar.py#L137-L140

**Comment by hvelarde** [comment]
entendi, isso está completamente errado e vai ter que ser consertado lá.

**Comment by claytonc** [comment]
@hvelarde @idgserpro 
Com relação a aparência que também afeta ao calendário padrão, por causa na nova versão do plone.app.event e também porque o IDG usa o collective.js.bootstrap.

Eu consegui ver duas soluções para a aparência:
1. customizar o portlet_calendar.js e remover o trecho [1], os tooltips do calendário fica como antes;
2. pega o trecho do css do bootstrap referente ao tooltip e tentar deixar com a mesma aparência do padrão d Plone que usa o "jquery.ui.tooltip.css".

[1] https://github.com/plone/plone.app.event/blob/1.1.x/plone/app/event/portlets/portlet_calendar.js#L31-L34

**Comment by hvelarde** [comment]
eu gostaria ouvir a opinião do @agnogueira sobre esse quesito; na verdade não queremos colocar mais customizações no projeto, mas bem queremos tirar todas no 2.0.

**Comment by idgserpro** [comment]
@claytonc não acho que customizar o portlet_calendar.js seja uma boa ideia. Não é possível corrigir somente com css?

**Comment by claytonc** [comment]
@idgserpro 
Sim, opção 2.

**Comment by caduvieira** [comment]
+1 para opção 2

**Comment by claytonc** [comment]
@idgserpro 

Correção a aparência seria adicionar o trecho CSS abaixo do bootstrap, alterando para a aparência do IDG.

E também é necessário efetuar uma correção para funcionar com DX, que foi mencionando nos comentários acima.

`
.tooltip {
  position: absolute;
  z-index: 1070;
  display: block;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-style: normal;
  font-weight: normal;
  letter-spacing: normal;
  line-break: auto;
  line-height: 1.42857143;
  text-align: left;
  text-align: start;
  text-decoration: none;
  text-shadow: none;
  text-transform: none;
  white-space: normal;
  word-break: normal;
  word-spacing: normal;
  word-wrap: normal;
  font-size: 12px;
  opacity: 0;
  filter: alpha(opacity=0);
}
.tooltip.in {
  opacity: 0.9;
  filter: alpha(opacity=90);
}
.tooltip.top {
  margin-top: -3px;
  padding: 5px 0;
}
.tooltip.right {
  margin-left: 3px;
  padding: 0 5px;
}
.tooltip.bottom {
  margin-top: 3px;
  padding: 5px 0;
}
.tooltip.left {
  margin-left: -3px;
  padding: 0 5px;
}
.tooltip-inner {
  max-width: 200px;
  padding: 3px 8px;
  color: #ffffff;
  text-align: center;
  background-color: #000000;
  border-radius: 4px;
}
.tooltip-arrow {
  position: absolute;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
}
.tooltip.top .tooltip-arrow {
  bottom: 0;
  left: 50%;
  margin-left: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000000;
}
.tooltip.top-left .tooltip-arrow {
  bottom: 0;
  right: 5px;
  margin-bottom: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000000;
}
.tooltip.top-right .tooltip-arrow {
  bottom: 0;
  left: 5px;
  margin-bottom: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000000;
}
.tooltip.right .tooltip-arrow {
  top: 50%;
  left: 0;
  margin-top: -5px;
  border-width: 5px 5px 5px 0;
  border-right-color: #000000;
}
.tooltip.left .tooltip-arrow {
  top: 50%;
  right: 0;
  margin-top: -5px;
  border-width: 5px 0 5px 5px;
  border-left-color: #000000;
}
.tooltip.bottom .tooltip-arrow {
  top: 0;
  left: 50%;
  margin-left: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000000;
}
.tooltip.bottom-left .tooltip-arrow {
  top: 0;
  right: 5px;
  margin-top: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000000;
}
.tooltip.bottom-right .tooltip-arrow {
  top: 0;
  left: 5px;
  margin-top: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000000;
}
`

**Comment by idgserpro** [comment]
> Correção a aparência seria adicionar o trecho CSS abaixo do bootstrap, alterando para a aparência do IDG.

Ou seja, registrar um css novo com essa correção que você comentou no brasil.gov.portal, registrando ele depois do css do bootstrap?

> E também é necessário efetuar uma correção para funcionar com DX, que foi mencionando nos comentários acima.

Não entendi... está falando do https://github.com/plone/Products.CMFPlone/issues/2215?

**Comment by idgserpro** [comment]
Como o 2.x ainda está em andamento e o 1.5.x está em modo de correção de bugs, mudei de opinião e cheguei à conclusão que, com relação ao problema de layout, o ideal é customizar o javascript no 1.5.x via jbot e o 2.x ao longo do desenvolvimento ver a melhor forma de atuar nessa questão.

Customizando o javascript apenas na branch 1.5.x não impactará na 2.x evitando assim retrabalho e, como 1.5.x está em modo manutenção o risco da customização dar alguma problema é mínima - digo isso porque o portlet_calendar.js foi [removido apenas na versão 3.0.2 de plone.app.event](https://github.com/plone/plone.app.event/commit/9edf746) na 2.0a6 [movido para uma pasta bbb](https://github.com/plone/plone.app.event/commit/f425187e6f47961a37bf02b8fd3b950039aa1848) mas mantendo o mesmo nome do recurso (a customização dele no brasil.gov.portal será via overrides e não z3c.jbot) e nesse tempo todo ele não foi alterado (sofreu alteração mas motivado por jslint e não funcionalidade).

Caso ao longo do desenvolvimento do 2.x os desenvolvedores achem que a customização também é o ideal, basta darem cherry-pick no commit. Caso achem que a customização não é o ideal, não tem problema pois estará na branch 1.5.x causando 0 de impacto no desenvolvimento.

**Comment by hvelarde** [comment]
o pacote não é mais dependência do IDG v2 então não vamos atualizar.
