### ISSUE TITLE
Carrossel Multimídia retorna link http sendo bloqueado quando usado com certificado SSL

### ISSUE THREAD

**Issue by JonatasFAlves** [plonegovbr/brasil.gov.portal#449]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?

![portal1](https://user-images.githubusercontent.com/21189314/35223366-e667c5b2-ff5f-11e7-855d-ce84ced5f3ba.png)

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? (IMPORTANTE: Pacotes apresentados [no manual de funcionalidades avançadas](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/manual-de-funcionalidades-avancadas-para-portais-plone_dez2014.pdf), mesmo que estejam no prefixo brasil.gov.\*, são considerados plugins adicionais). Caso sua resposta seja sim, forneça o nome e as versões utilizadas.

- [x] Sim
Nome e versões dos plugins:
- gov.br: Página Destaque 1.0b1 
- brasil.gov.portlets: Instalação do Pacote 1.0rc2 

- [ ] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [x] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [ ] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
- Adicionar e utilizar o tile Carrossel Multimídia
- Adicionar certificado SSL ao portal

### Qual é o retorno esperado? O que você vê ao contrário do esperado?
Sem o certificado SSL o tile funciona normalmente, porém quando adicionado, o https bloqueia o link fornecido pelo tile, exibindo uma tela escura em vez do vídeo. 

![image](https://user-images.githubusercontent.com/21189314/35223970-1ce8b34c-ff62-11e7-8e25-bd925553074d.png)

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.

" Bloqueado carregamento de conteúdo ativo mesclado 'http://youtube.com/linkdoembededvideo' "

![image](https://user-images.githubusercontent.com/21189314/35224077-8d192994-ff62-11e7-847f-bf0114cfd8d0.png)

### Por favor forneça informações adicionais que possam complementar o seu relato.
O tile Carrossel Multimídia retorna no iframe um link http (mesmo quando o link passado é originalmente https) e por isso ele é bloqueado.

**Comment by hvelarde** [comment]
você está utilizando uma versão do IDG que não é mais suportada; favor atualizar e testar novamente.

**Comment by hvelarde** [comment]
fechando por falta de feedback; esse tile foi descontinuado no IDG v2..

caso o problema acontecer na versão mais recente do IDG v1 pode reabrir.
