### ISSUE TITLE
Erro ao alterar o mês no Calendar Tile

### ISSUE THREAD

**Issue by jpsthome** [plonegovbr/brasil.gov.portal#450]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?
Portal Padrão 1.5.1
Plone 4.3.15 (4317)
CMF 2.2.10
Zope 2.13.26
Python 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
PIL 3.3.0 (Pillow)

No Linux (Ubuntu 16.04)

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? (IMPORTANTE: Pacotes apresentados [no manual de funcionalidades avançadas](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/manual-de-funcionalidades-avancadas-para-portais-plone_dez2014.pdf), mesmo que estejam no prefixo brasil.gov.\*, são considerados plugins adicionais). Caso sua resposta seja sim, forneça o nome e as versões utilizadas.

- [ ] Sim
Nome e versões dos plugins:

- [x] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [x] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [ ] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
Criar um portal novo, tendo como base a versão 1.5.1 (último release) do portal padrão e adicionar o Calendar Tile nas configurações de capa (@@cover-settings). Feito isso adicionar isso em alguma capa qualquer e realizar o logoff do portal. 

O erro acontece no momento que você tenta trocar de mês no calendar tile sem estar logado no sistema.

### Qual é o retorno esperado? O que você vê ao contrário do esperado?
O retorno esperado é que troque de mês igual funciona quando você está logado no site.

Acaba retornando o seguinte erro: "error: Not Found"

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.
Não gera nenhum erro nos logs do Plone, mas gera o seguinte erro no console:

++resource++plone.app.jquery.js:2 GET http://localhost:8080/@@updatetile?tile-id=ea708b3c-0e82-4064-923d-8d8793cdea49&month%3Aint=3&year%3Aint=2018 404 (Not Found)
send @ ++resource++plone.app.jquery.js:2
ajax @ ++resource++plone.app.jquery.js:2
(anonymous) @ main.js:28
dispatch @ ++resource++plone.app.jquery.js:2
u @ ++resource++plone.app.jquery.js:2

### Por favor forneça informações adicionais que possam complementar o seu relato.

O erro acontece tanto no Chrome quanto no Firefox. Fiz o teste em um portal criado só para ver se ia funcionar e o erro aconteceu sem ser feito nenhuma alteração no portal padrão.

**Comment by idgserpro** [comment]
Saberia me informar se esse erro ocorre numa instalação do Plone padrão mas apenas com o https://github.com/collective/collective.cover instalado? Pra sabermos se esse erro é alguma coisa do IDG interferindo na capa ou se é um problema da capa.

Teste com as versões: Products.CMFPlone = 4.3.15 e collective.cover = 1.6b5, pois são as pinagens de https://github.com/plonegovbr/portalpadrao.release/blob/master/1.5.1/versions.cfg

**Comment by claytonc** [comment]
@idgserpro 

https://github.com/plone/Products.CMFPlone/issues/2215

**Comment by idgserpro** [comment]
@claytonc 

mas aqui o @jpsthome está falando da tile de calendário e não do portlet. Isso também ocorre na tile? É o mesmo problema?

**Comment by jpsthome** [comment]
@claytonc 

O meu tile está na raiz do site e não ta indo, no caso, ta em uma capa que está localizada na raiz.

Também testei na instalação padrão do Plone e funciona normalmente. A configuração ta assim:

Versão
Plone 4.3.15 (4317)
CMF 2.2.10
Zope 2.13.26
Python 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
PIL 4.1.0 (Pillow)

No caso eu baixei o [Unified Installer](https://plone.org/download/releases/4.3.15) e instalei com os arquivos da pasta buildout_templates e base_skeleton.

**Comment by claytonc** [comment]
@idgserpro 

Pensei que estava relacionado, pois ocorre "Not Found" também.
Mas nos testes que fiz com 1.6b5 [1], vi que o path não esta sendo passado corretamente:

Anônimo: http://localhost:8080/@@updatetile?tile-id=ea708b3c- ...
Autenticado: http://localhost:8080/Plone/capa/@@updatetile?tile-id=ea708b3c- ...

[1] https://github.com/plonegovbr/portalpadrao.release/blob/master/1.5.1/versions.cfg

**Comment by hvelarde** [comment]
deve estar relacionado pois acho que o tile usa o mesmo código do portlet.

CC @rodfersou

**Comment by claytonc** [comment]
@hvelarde 

O calendário esta funcionando, testando copiando e colando as urls dos links "próximo" e "anterior" navegador.
O que esta ocorrendo é que o JS não esta utilizando como referência a url do "base" que esta no html como anônimo.

Se clicar nos links como anônimo:

- http://localhost:8080/Plone => http://localhost:8080/@@updatetile...
- http://localhost:8080/Plone/ => http://localhost:8080/Plone/@@updatetile...
- http://localhost:8080/Plone/capa => http://localhost:8080/Plone/@@updatetile...
- http://localhost:8080/Plone/capa/ => http://localhost:8080/Plone/capa/@@updatetile... - esse funciona

Se clicar nos links como autenticado:

- http://localhost:8080/Plone => http://localhost:8080/Plone/capa/@@updatetile...
- http://127.0.0.1:8080/Plone5/capa = > http://localhost:8080/Plone/capa/@@updatetile...

**Comment by jpsthome** [comment]
@claytonc 

Realmente, fiz esses testes que você comentou e funcionou com o http://localhost:8080/Plone/capa/....
Alguém saberia como resolver esse problema do JS?

**Comment by hvelarde** [comment]
esse problema ainda acontece no IDG v1.5.2?

**Comment by jpsthome** [comment]
Sim, acabei de testar aqui no meu portal, que atualizei pro IDG v.1.5.2 e em um portal criado do zero baixando da branch 1.5.2 do git de vocês, nos 2 casos não funcionou.

**Comment by jpsthome** [comment]
Testei agora novamente e aparentemente ta funcionando normal (não fiz nenhuma alteração).

**Comment by hvelarde** [comment]
pode ter sido um problema de caching; sugiro atualizar para 1.5.3 que é a versão mais recente do branch.

**Comment by idgserpro** [comment]
@jpsthome para evitar esse tipo de problema, a comunidade (no caso @hvelarde e @rodfersou) estão trabalhando para modernizar os recursos javascript do collective.cover. Você pode acompanhar esse processo em https://github.com/collective/collective.cover/issues/819.
