### ISSUE TITLE
Documentar mudanças na versão 2.0

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#451]
Os seguintes assuntos devem ser documentados:

- [ ] remoção do HAProxy da configuração de produção
- [ ] adição do tipo de conteúdo Infographic
- [ ] preparar upgrade step para migrar tiles padrão que estavam com overrides (https://github.com/plonegovbr/brasil.gov.tiles/pull/205, https://github.com/plonegovbr/brasil.gov.tiles/pull/206, https://github.com/plonegovbr/brasil.gov.tiles/pull/207, https://github.com/plonegovbr/brasil.gov.tiles/pull/208, https://github.com/plonegovbr/brasil.gov.tiles/pull/209, https://github.com/plonegovbr/brasil.gov.tiles/pull/210)

**Comment by idgserpro** [comment]
Existem outras modificações sutis que acredito ser útil uma discussão.

Por exemplo, no novo tema, temos a informação "Todo o conteúdo deste site está publicado sob a licença creative commons cc by nd 3.0 brasil". Acredito que esse tipo de informação deveria ser renderizada via uma flag no painel de controle (como discutido em https://github.com/plonegovbr/brasil.gov.portal/issues/174#issuecomment-65297385) ao invés de ser renderizado por padrão.

**Comment by idgserpro** [comment]
Com https://github.com/plonegovbr/brasil.gov.tiles/pull/209 e https://github.com/plonegovbr/brasil.gov.tiles/pull/206 sendo finalizados, o recurso "Variação de Título" não existirá mais nesses tiles e deveria ser ao menos informado no changelog do release.

**Comment by hvelarde** [comment]
podem por favor colocar mais informação sobre esse recurso? o que ele faz?

**Comment by idgserpro** [comment]
Não existe muita coisa na documentação (ver página 200 e 205 em http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/gestao-manual-portal-modelo-governo-federal-dez2014.pdf), mas basicamente é atribuir estilo diferenciados ao título de tile definido como "Normal", "Grande" e "Gigante". Isso inclusive chegou a ser "quebrado" quando atualizamos a versão do collective.cover e consertado em https://github.com/plonegovbr/brasil.gov.portal/pull/417.

Às vezes no novo layout esse recurso nem faz sentido mais não, mas acho justo comentar que ele não existe mais pra quem utiliza esse recurso ainda.

**Comment by idgserpro** [comment]
Devido a https://github.com/plonegovbr/brasil.gov.tiles/commit/f6202fec1ad8added4e0e176ac677652a796364f, como os upgradeSteps foram removidos no commit acima, quem tem um IDG instalado antes de 1.5.x, deverá atualizar primeiro para 1.5.x antes de atualizar para 2.x.

**Comment by idgserpro** [comment]
Com a mudança de layout, todos os manuais (como http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/gestao-manual-portal-modelo-governo-federal-dez2014.pdf) estarão com referências a um padrão mais antigo. Estudar o impacto na usabilidade.

**Comment by idgserpro** [comment]
Com a mudança de layout, não existirão mais portlets.

Isso precisa ser informado claramente na documentação. Informar também a possibilidade de ter a listagem dos portlets atribuídos através de https://github.com/plonegovbr/portal.buildout/commit/12f074109c5d918c53d0689c787514cd4feeb5b6, explicitando que para obter isso é necessária a ação de um integrador/implementador com acesso ao filesystem da instância.

**Comment by idgserpro** [comment]
Com a mudança do layout, não existe mais a viewlet de destaques. (Ref: https://github.com/plonegovbr/brasil.gov.portal/pull/497)

Informar ao usuário que visualmente ela foi removida, mas os itens cadastrados na pasta de destaques não foram removidos. Dessa forma, ele deve, manualmente, decidir o que fazer com os itens que ele planejava manter em destaque.

**Comment by idgserpro** [comment]
No 2.0 oficial (sem ser rc, beta e etc), compilar informações como a presente em https://listas.interlegis.gov.br/pipermail/plonegov-br/2018-September/004845.html.

**Comment by idgserpro** [comment]
Poderia revisar essa issue @hvelarde? Acho que ela pode ser fechada.
