### ISSUE TITLE
Portlet de calendário estendido. Problema de quebra de layout

### ISSUE THREAD

**Issue by FernandoNasicimento** [plonegovbr/brasil.gov.portal#465]
Segue abaixo um erro de quebra de layout do portlet de calendário estendido.
![image](https://user-images.githubusercontent.com/37597689/37718023-88e79312-2d00-11e8-9ce7-1215e0dfcf07.png)

Outro ponto verificado: Portlet não avança e nem retrocede entre as datas

![image](https://user-images.githubusercontent.com/37597689/37717798-0bcf34e8-2d00-11e8-8106-d53e46d458a4.png)

**Comment by FernandoNasicimento** [comment]
Verificado erro de data compromisso após criar uma agenda diária, na versão do IDG 1.5.1. 



![image](https://user-images.githubusercontent.com/37597689/37719220-497ce2ec-2d03-11e8-90fe-c2bc4a62c263.png)


Aonde está escrito Long_date_agenda, deviria está a data do compromisso na agenda

**Comment by idgserpro** [comment]
Fernando, obrigado por reportar os erros acima.

Esses erros dizem respeito ao brasil.gov.agenda. Poderia reabri-los por lá (https://github.com/plonegovbr/brasil.gov.agenda/issues/new), falando qual versão do IDG você está usando? Lembrando que o que você postou aqui diz respeito a dois problemas diferentes, portanto https://github.com/plonegovbr/brasil.gov.portal/issues/465#issue-307285625 vira um relato e https://github.com/plonegovbr/brasil.gov.portal/issues/465#issuecomment-374980137 vira outro.
