### ISSUE TITLE
Rever os templates de issue e pull request

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#473]
Na minha opinião os templates são muito complexos e incluem muita informação desnecessária além de confundir o uso de funcionalidades de GitHub como check boxes (o ohjetivo dos check boxes é criar listas de tarefas e não seleções múltiplas, https://blog.github.com/2013-01-09-task-lists-in-gfm-issues-pulls-comments/).

Entendo a motivação, mas acho que neste caso o remédio é pior que a doença.

**Comment by rodfersou** [comment]
Concordo, um simples comentário com checklist ja resolveria.. ao criar a tarefa ou pull request teria uma lista de itens para lembrar de executar, caso necessário.

**Comment by idgserpro** [comment]
Eu acho que a gente que já é mais experiente com a manutenção desses pacotes sabe a hora de usar ou não a verbosidade dessas templates sem comprometer muito o relato (pois muitas vezes a gente mesmo cadastra um relato e já vai resolver), mas não sei se seria o caso de remover para os demais usuários. Quero até _adicionar_ mais depois que [vi que tem gente usando o docker](https://github.com/plonegovbr/brasil.gov.portal/issues/475#issuecomment-392884944), rs. Gostaria de ouvir a opinião dos demais [mencionados pelo @hvelarde](https://github.com/plonegovbr/brasil.gov.portal/issues/473#issuecomment-388897060).

> além de confundir o uso de funcionalidades de GitHub como check boxes

Já nesse ponto eu concordo. O que sugere no lugar?

**Comment by hvelarde** [comment]
sugiro em primeiro lugar remover os checkboxes e deixar isso como um espaço aberto para as pessoas responderem.

sugiro também sugerir remover qualquer parte do texto não utilizada.

**Comment by idgserpro** [comment]
Vocês são mantenedores de vários pacotes inclusive fora do namespace plonegovbr, o que decidirem pra mim está ok. A questão de remoção de checkboxes por exemplo é unânime.
