### ISSUE TITLE
Release 1.5.2 de brasil.gov.portal

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#478]
- [x]  Gerar release de brasil.gov.facetada e editar o versions.cfg 1.x.
- [x]  Gerar release de brasil.gov.tiles 1.x e editar o versions.cfg 1.x.
- [x]  Gerar release de brasil.gov.agenda 1.x e editar o versions.cfg 1.x.
- [x]  Gerar release de brasil.gov.portal 1.x e editar o versions.cfg 1.x.
- [x]  Seguir o processo de release em https://github.com/plonegovbr/portalpadrao.release#ações-para-um-novo-release, ver https://github.com/plonegovbr/portalpadrao.release/issues/30

**Comment by idgserpro** [comment]
@hvelarde já mesclei o último item do brasil.gov.portal, podemos prosseguir com as ações no primeiro comentário desse relato e lançarmos o release 1.5.2.

@claytonc pode nos ajudar com o https://github.com/plonegovbr/portalpadrao.release/issues/29? Senão essa atualização da documentação do docker precisará ser feita em outro release, precisamos do release 1.5.2 com as correções efetuadas.

**Comment by hvelarde** [comment]
@idgserpro vamos fazer começo da próxima semana, por favor; estou resolvendo outro pepinos hoje.

**Comment by idgserpro** [comment]
Tudo bem. Favor gerar os releases individuais mas não gerar ainda no portalpadrao.release para que possamos testar antes do release em definitivo.

**Comment by idgserpro** [comment]
Estou avaliando 2 possíveis erros, https://github.com/plonegovbr/brasil.gov.agenda/issues/82#issuecomment-396230266 e outro não mapeado, favor ainda não gerar os releases dos demais.

**Comment by idgserpro** [comment]
PRs criados e atualizados no primeiro comentário dessa issue.

**Comment by idgserpro** [comment]
PRs dos erros encontrados em https://github.com/plonegovbr/brasil.gov.portal/issues/478#issuecomment-396275550 mesclados. @hvelarde Favor gerar os releases individuais mas não gerar ainda no portalpadrao.release para que possamos testar antes do release em definitivo.

**Comment by hvelarde** [comment]
@idgserpro os releases solicitados estão prontos; fica com vocês o processo de documentar o upgrade e criar os releases no portal.buildout e no portalpadrao.release; eu preciso fazer outras coisas agora.

**Comment by idgserpro** [comment]
Acompanhar em https://github.com/plonegovbr/portalpadrao.release/issues/30
