### ISSUE TITLE
Quebra de layout com Topo expansível

### ISSUE THREAD

**Issue by almeidajeff** [plonegovbr/brasil.gov.portal#543]
**Qual versão do produto você está usando e em qual sistema operacional?**
Portal Padrão 2.1.1b1
Plone 4.3.18 (4320)
CMF 2.2.10
Zope 2.13.28
Python 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
PIL 3.3.3 (Pillow)

**Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão?**

- brasil.gov.temas 2.0b4
- brasil.gov.tiles 2.0b3
- brasil.gov.agenda 2.0a7
- brasil.gov.barra 3.0.5

**Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?**
Sim

**Está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release e https://github.com/plonegovbr/brasil.gov.portal#requisitos?**
Sim

**Quais são os passos para reproduzir o problema?**
Atualizar o brasil.gov.portal para tag 2.1b1

**Qual é o retorno esperado? O que você vê ao contrário do esperado?**
Aplicar o topo expansível, mas a imagem informada na view @@portal-settings não é renderizada

**A aplicação forneceu algum erro no console ou na interface?**
Não

**Por favor forneça informações adicionais que possam complementar o seu relato:**
Como deveria ser o layout com o topo expansível marcado ? Gostaria de ajudar a ajustar essa funcionalidade.

Atualmente esta ficando desta forma

![topo_expansivel](https://user-images.githubusercontent.com/1029920/46825315-b82cbd00-cd69-11e8-958f-be758098b740.png)

**Comment by hvelarde** [comment]
corrigido em https://github.com/plonegovbr/brasil.gov.temas/pull/228.

**Comment by almeidajeff** [comment]
Nice, good job !
