### ISSUE TITLE
TypeError no ZServer ao iniciar uma instância

### ISSUE THREAD

**Issue by monicakrs** [plonegovbr/brasil.gov.portal#551]
Prezados, segui as instruções de instalação no site https://identidade-digital-de-governo-plone.readthedocs.io/en/latest/producao/

Executei os comandos para realizar o download
git clone https://github.com/plonegovbr/portal.buildout.git
git checkout tags/2.1rc1

O sistema operacional é Centos 6.9

O buildout.cfg está assim:
`[buildout]
extends =
    production.cfg

[hosts]
supervisor = 0.0.0.0
instance = 0.0.0.0
zeoserver = 0.0.0.0

[ports]
supervisor = 9001
instance = 8080
zeoserver = 8100

[users]
zope = admin
os = plone

[supervisor-settings]
user = admin
password = 4dm1n${users:zope}

`

A aplicação está funcionando, porém o seguinte erro aparece no log e fica repetindo infinitamente.

**2018-10-30T10:15:44 ERROR ZServer Server Error: <type 'exceptions.TypeError'>, cannot concatenate 'str' and 'NoneType' objects: file: /opt/portal.buildout/eggs/Zope2-2.13.28-py2.7.egg/ZServer/HTTPServer.py line: 190**

**Comment by hvelarde** [comment]
Mônica, por favor cole o traceback **completo** para poder lhe ajudar.

por outro lado, você está utilizando uma versão de CentOS diferente da indicada na documentação; você tem que indicar se seguiu todos os passos igual que documentado.

**Comment by monicakrs** [comment]
Hector,

eu irei mudar para o CentOS 7 e instalarei novamente.

Mônica


Em qua, 31 de out de 2018 às 17:01, Héctor Velarde <notifications@github.com>
escreveu:

**Comment by idgserpro** [comment]
@monicakrs a [linha que deu erro](https://github.com/zopefoundation/Zope/blob/2.13.28/src/ZServer/HTTPServer.py#L190) está tentando obter a versão do protocolo HTTP. Talvez o seu servidor de aplicação esteja removendo a versão do protocolo quando passa a requisição para o Zope.

Se for isso, favor postar aqui a configuração que você alterou para que possamos documentar.

**Comment by monicakrs** [comment]
Eu debuguei e o request.version vem como None. Não sei porque a versão está
sendo removida.

Eu fiz a instalação 2 vezes. Uma vez seguindo os passos do ambiente de
produção(
https://identidade-digital-de-governo-plone.readthedocs.io/en/latest/producao/)
e a segunda vez seguindo os passos de desenvolvimento(
https://identidade-digital-de-governo-plone.readthedocs.io/en/latest/desenvolvimento/).
Pela de produção o site apareceu e o erro só apareceu no log (iniciei o
servidor com bin/supervisord), já a desenvolvimento deu erro no site( o
erro aparece após comando bin/instance fg e após o Zope estar pronto).
Infelizmente não copiei as saídas dos comandos.

Na instalação de produção a única configuração que fiz diferente é que no
buildout.cfg, em vez de 127.0.0.1 no supervisor, instance e zeoserver eu
coloquei 0.0.0.0. Fiz isso porque nesse servidor já havia um outro portal
padrão antigo que usava essa configuração.

supervisor = 127.0.0.1instance = 127.0.0.1zeoserver = 127.0.0.1



Em qui, 1 de nov de 2018 às 09:35, idgserpro <notifications@github.com>
escreveu:

**Comment by idgserpro** [comment]
@monicakrs você esta acessando o portal por um servidor de aplicação (Apache, nginx)? deve ser alguma configuração desse servidor que está removendo a versão.

**Comment by monicakrs** [comment]
Não estava utilizando nem Apache  nem nginx. Estava fazendo em um ambiente de testes. O erro fica se repetindo no log infinitamente.

**Comment by idgserpro** [comment]
@monicakrs então deve ser alguma coisa relacionada ao CentOS. Você tentou no CentOS 7? Aqui eu utilizo Ubuntu e não ocorre esse erro.

**Comment by monicakrs** [comment]
Tentei sim. No CentOS 7 não ocorre o erro.

**Comment by idgserpro** [comment]
Maravilha! Então vou fechar esse relato uma vez que o recomendado na documentação é o CentOS 7:

https://github.com/plonegovbr/portal.buildout/blob/master/docs/base.rst#pacotes-do-sistema
