### ISSUE TITLE
Erro ao acessar a aba Layout em qualquer página

### ISSUE THREAD

**Issue by GMBermeo** [plonegovbr/brasil.gov.portal#556]
Segue abaixo:

Desculpe, mas parece haver um erro…
Aqui está a mensagem de erro completa:

Visualizar traceback como texto

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module collective.cover.browser.layout, line 82, in __call__
Module collective.cover.browser.layout, line 78, in render
Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 98, in __call__
Module z3c.pt.pagetemplate, line 163, in render
Module chameleon.zpt.template, line 261, in render
Module chameleon.template, line 171, in render
Module 809427e7b95c52a3ee65464ab20b381d, line 892, in render
Module bcf1ca98d56d2264630d1e706eb5ec24, line 1417, in render_master
Module bcf1ca98d56d2264630d1e706eb5ec24, line 613, in render_content
Module 809427e7b95c52a3ee65464ab20b381d, line 415, in __fill_main
Module five.pt.expressions, line 161, in __call__
Module collective.cover.browser.layout, line 290, in __call__
Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 98, in __call__
Module z3c.pt.pagetemplate, line 163, in render
Module chameleon.zpt.template, line 261, in render
Module chameleon.template, line 191, in render
Module chameleon.template, line 171, in render
Module 20ac22e68ef6c94230d16ed6729afa2e, line 128, in render
Module collective.cover.browser.layout, line 274, in get_tile_metadata
Module zope.component._api, line 169, in getUtility
ComponentLookupError: (<InterfaceClass plone.tiles.interfaces.ITileType>, u'spacer') - Expression: "context/@@tile_list" - Filename: ... 2.7.egg/collective/cover/browser/templates/layoutedit.pt - Location: (line 42: col 48) - Source: ... tal:replace="structure context/@@tile_list"></div> ^^^^^^^^^^^^^^^^^^^ - Expression: "python:view.get_tile_metadata(tile['tile_type'])" - Filename: ... py2.7.egg/collective/cover/browser/templates/tilelist.pt - Location: (line 13: col 33) - Source: ... metadata python:view.get_tile_metadata(tile['tile_type'])"> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Arguments: repeat: {...} (0) context: <ImplicitAcquisitionWrapper capa-da-home at 0x7f58fe307320> views: <ViewMapper - at 0x7f58fc55ff90> modules: <TraversableModuleImporter - at 0x7f590adebd90> args: <tuple - at 0x7f5912bd6050> nothing: <NoneType - at 0x5593fff68560> target_language: pt_BR default: <object - at 0x7f5912af2580> request: <instance - at 0x7f58fdfa5878> wrapped_repeat: {...} (1) loop: {...} (1) template: <ViewPageTemplateFile - at 0x7f58fc671050> tile: {...} (1) translate: <function translate at 0x7f58fc53f938> options: {...} (0) view: <TileList tile_list at 0x7f58fc545950>

**Comment by idgserpro** [comment]
@GMBermeo qual é a versão do IDG que você está utilizando? Esse erro ocorreu após alguma atualização?

**Comment by GMBermeo** [comment]
@idgserpro é a versão 2.1rc1 (plone 4.2.18-4320), passei 1 semana sem acessar, quando voltei agora percebi que a página layout não estava funcionando mais, não sei se houve atualização.

**Comment by hvelarde** [comment]
@GMBermeo esse tile `spacer` é um componente do [brasil.gov.paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/tree/1.2/src/brasil/gov/paginadestaque/tiles); esse complemento não foi contemplado na atualização a 2.0 e nãoe stá suportado; acho que tu vai ter que desinstalar ele.

**Comment by idgserpro** [comment]
> esse tile spacer é um componente do brasil.gov.paginadestaque; esse complemento não foi contemplado na atualização a 2.0 e nãoe stá suportado

@hvelarde acho melhor isso ficar claro no Readme do brasil.gov.paginadestaque.

Ver também https://github.com/plonegovbr/brasil.gov.paginadestaque/issues/20#issuecomment-432289596
