### ISSUE TITLE
Erro no botao Layout de capa após atualização (fio-separador)

### ISSUE THREAD

**Issue by brownst** [plonegovbr/brasil.gov.portal#564]
O erro ocorreu depois de ter atualizado do site da versão 1.03 para a 1.5.3 e posteriormente para a 2.1.

**Qual versão do produto você está usando e em qual sistema operacional?**
```
Linux CentOS 7.5
Portal Padrão 2.1
Plone 4.3.18 (4320)
CMF 2.2.10
Zope 2.13.28
Python 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
PIL 3.3.3 (Pillow)
```

**Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão?**
Não

**Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?**
Sim

**Quais são os passos para reproduzir o problema?**
Acessar qualquer capa e clicar no botão Layout

**A aplicação forneceu algum erro no console ou na interface?**
```
2018-12-06T18:22:41 ERROR Zope.SiteErrorLog 1544127761.870.832196840907 http://dch-plone1.cgu.dmz:8020/dados_ouvidoria/Ouvidoria/home/layoutedit
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.cover.browser.layout, line 81, in __call__
  Module collective.cover.browser.layout, line 42, in setup
  Module collective.cover.vocabularies, line 125, in __call__
  Module zope.schema.vocabulary, line 65, in __init__
ValueError: term values must be unique: 'fio-separador'
------
2018-12-06T18:22:42 DEBUG plone.dexterity.utils getAdditionalSchemata with context <Cover at /dados_ouvidoria/Ouvidoria/home> and portal_type None
------
2018-12-06T18:22:42 DEBUG plone.dexterity.utils Behavior assignable found for context.
------
2018-12-06T18:22:42 DEBUG chameleon.loader cache miss: 602faf1fb29ef11bcfe40a251d763fb3.py
------
2018-12-06T18:22:42 DEBUG chameleon.loader cache miss: 602faf1fb29ef11bcfe40a251d763fb3.py
```

**Comment by brownst** [comment]
Obs. já executei o clean catalog, usando o egg: collective.catalogcleanup, mas sem sucesso.
https://pypi.org/project/collective.catalogcleanup

**Comment by hvelarde** [comment]
sugiro ir no painel de controle do registro, procurar pelo record `collective.cover.controlpanel.ICoverSettings.styles`, e conferir se o item `fio-separador` está presente mais de uma vez.

caso afirmativo, remover o item duplicado e tentar de novo.

**Comment by brownst** [comment]
Deu certo.
