### ISSUE TITLE
/@@updateSharingInfo  <body data-base-url=

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#565]
**Qual versão do produto você está usando e em qual sistema operacional?**

    Portal Padrão 1.5.3

    Plone 4.3.18 (4320)

    CMF 2.2.10

    Zope 2.13.28

    Python 2.7.15

**Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão?**

Não

**Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?**

Sim

**Está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release e https://github.com/plonegovbr/brasil.gov.portal#requisitos?**

Sim

**Quais são os passos para reproduzir o problema?**

Acessar o formulário de compartilhamento de qualquer objeto, menos a raiz do Plone Site.

**Qual é o retorno esperado? O que você vê ao contrário do esperado?**

Devido ao tema diazo não manter o atributo "data-base-url" na tag "body", o javascript "/skins/plone_ecmascript/kss-bbb.js" está fazendo a requisição da view "/@@updateSharingInfo"
na url raiz do Plone Site, e não na url do objeto que estavamos acessando.

Dessa forma está alterando o compartilhamento da raiz do Plone Site e não do objeto que pretendia-se compartilhar.

**A aplicação forneceu algum erro no console ou na interface?**

O compartilhamento para um usuário ou grupo aparece como herdado da raiz do site e não como definido no próprio objeto.

**Por favor forneça informações adicionais que possam complementar o seu relato:**

Necessário que o tema diazo mantenha o atributo "data-base-url" da tag <body>.

Como solução paliativa o script "/skins/plone_ecmascript/kss-bbb.js" pode ser customizado com o código que era utilizado na versão 4.3.15 do Plone: 
https://github.com/plone/Products.CMFPlone/blob/4.3.15/Products/CMFPlone/skins/plone_ecmascript/kss-bbb.js ou seguir o que está definido em https://community.plone.org/t/sharing-issue-on-plone-4-3-17-18/7842/12

**Comment by agnogueira** [comment]
@idgserpro pode revisar se o https://github.com/plonegovbr/brasil.gov.temas/pull/249 resolve para você?

**Comment by idgserpro** [comment]
@agnogueira infelizmente por questões internas não conseguiremos testar/revisar esse PR em janeiro. Se estiver com urgência para essa correção, recomendamos o @rodfersou ou o @hvelarde

**Comment by idgserpro** [comment]
Corrigido em plonegovbr/brasil.gov.temas#249

**Comment by idgserpro** [comment]
Reabrindo pois ainda falta aplicar correção na branch 1.x

**Comment by idgserpro** [comment]
Corrigido nos pullrequests:
plonegovbr/brasil.gov.temas#249
plonegovbr/brasil.gov.temas#254
