### ISSUE TITLE
Problema ao definir o compartilhamento de um item

### ISSUE THREAD

**Issue by agnogueira** [plonegovbr/brasil.gov.portal#566]
Problema encontrado em uma instalação nova do Portal Padrão na versão 2.1.1.

Ao tentar definir uma regra de compartilhamento em uma pasta específica, a regra definida é aplicada diretamente na raiz do portal, e não na pasta desejada.

Passo a Passo:
1. Vá até uma pasta do portal;
2. Clique na aba "Compartilhamento";
3. Defina uma regra de compartilhamento para esta pasta, como por exemplo permitir que um usuário ou grupo possa adicionar conteúdo a esta pasta;
4. Aparentemente neste momento tudo correu normalmente:
![tela-1](https://user-images.githubusercontent.com/1030139/51341682-08a66b80-1a79-11e9-817f-a69f2f3cfe60.png)
5. Mas se clicarmos novamente na aba "Compartilhamento", vemos que a regra definida, está aplicada na raiz do portal:
![tela-2](https://user-images.githubusercontent.com/1030139/51341742-2e337500-1a79-11e9-9786-0a448f45d1d0.png)
6. Dessa maneira ao clicar na aba "Compartilhamento" na raiz do Portal, vemos que a regra foi definida globalmente:
![tela-3](https://user-images.githubusercontent.com/1030139/51341787-4c00da00-1a79-11e9-99d3-566293c2e9f9.png)

O Comportamento correto, seria que as definições fossem aplicadas apenas a patas onde a tregra foi criada.

**Comment by agnogueira** [comment]
@idgserpro  e @hvelarde: isto ocorre para vocês tambem? Alguem mais consegue testar?
Alguma ideia do que esteja causando?

**Comment by idgserpro** [comment]
https://github.com/plonegovbr/brasil.gov.portal/issues/565

**Comment by agnogueira** [comment]
Fechando essa issue, deixando apenas a original #565

**Comment by monicakrs** [comment]
Estou com esse mesmo problema. O que devo fazer para corrigir?

**Versão do portal**
Portal Padrão 2.1.1
Plone 4.3.18 (4320)
CMF 2.2.10
Zope 2.13.28
Python 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
PIL 3.3.3 (Pillow)

**Comment by idgserpro** [comment]
@monicakrs foi gerado o [relase 2.0.3 do brasil.gov.temas](https://pypi.org/project/brasil.gov.temas/2.0.3/) que corrige esse erro. Ainda não foi gerado um versão do IDG que utiliza essa versão do tema.
