### ISSUE TITLE
Integração com hub.docker está falhando no portal.buildout

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#600]
Integração com hub.docker está falhando no portal.buildout. Ver pelo histórico de commits:

https://github.com/plonegovbr/portal.buildout/commits/master

**Comment by idgserpro** [comment]
@caduvieira você sabe porque está falhando? Essa integração já funcionou alguma vez?

**Comment by idgserpro** [comment]
Pessoal, enquanto esse problema não é resolvido, acho melhor desativar a integração com o hub.docker, para evitar que a build fique falhando. O que acham?

@caduvieira ?

**Comment by idgserpro** [comment]
@caduvieira enquando essa issue não é resolvida, eu desabilitei a integração com o  hub.docker no  `portal.buildout`

**Comment by ililminati** [comment]
Bom dia,

Pessoal, não sei se este é o local adequando, mas, gostaria de saber de vocês, se há algum material que aborde como pode ser feita a implantação do Plone com IDG utilizando Docker. Tenho a intenção de usar o Plone IDG na UFCG, porém, nativamente nossos servidores não dão suporte aos requisitos do Plone, por está razão, precisaria fazer este serviço usando o Docker. Obrigado desde já.

**Comment by caduvieira** [comment]
Não é possível mais fazer builds automáticos no plano gratuito do docker hub.

**Comment by idgserpro** [comment]
@caduvieira eu removi a configuração do webhook do docker no `portal.buildout`.
