### ISSUE TITLE
Acesso ao site portalpadrao.gov.br

### ISSUE THREAD

**Issue by thalesmota** [plonegovbr/brasil.gov.portal#607]
Estou tentando acessar os manuais da IDG 2.0 no [Portal Padrão](http://www.portalpadrao.gov.br/manuais) para implantação e uso correto do [brasil.gov.portal 2.1.1](https://github.com/plonegovbr/brasil.gov.portal/tree/2.1.1), porém estou sendo redirecionado para outro site da @idgserpro, o https://dsgov.estaleiro.serpro.gov.br/.

Estou precisando desses manuais, assim como outras instituições, para dar andamento a implantação da IDG 2.0 e uso correto dos elementos. Assim sendo, gostaria de saber se existe outra lugar que contenha esses manuais de diretrizes e as outras instruções do uso da IDG 2.0.

**Comment by idgserpro** [comment]
@thalesmota acho que o único manual que existe ainda sobre o IDG 2.0 é o de instalação:

https://github.com/plonegovbr/portal.buildout/tree/master/docs

**Comment by thalesmota** [comment]
@idgserpro, não existe nenhum backup ou acesso em outros lugares?

Estou precisando urgente dos documentos com as diretrizes da IDG 2.0. Estamos finalizando a implantação da IDG 2.0 aqui na universidade, e esses manuais indicam como devemos usar corretamente os componentes da IDG 2.0. 

Sem eles, qual será a base de consulta de como usar os componentes da IDG, dimensões corretas das imagens, fontes utilizadas, boas práticas de uso dos grids, uso do cabeçarios, e vários outros direcionamentos?

Lembro que acessávamos esses manuais em portalpadrao.gov.br/manuais. Sem eles, é um tiro no escuro usar a IDG 2.0. É como não ter nenhuma orientação.

**Comment by idgserpro** [comment]
@thalesmota lembro que esses manuais ficam no site da SECOM:

https://www.gov.br/secom/pt-br

Você pode tentar com alguém de lá. Não sei de outro lugar onde tinham esses manuais.

**Comment by claytonc** [comment]
@thalesmota @idgserpro 

Até um tempo atrás era possível obter os manuais pelos portais:

- http://www.portalpadrao.gov.br/manuais - que agora é redirecionando para http://dsgov.estaleiro.serpro.gov.br/
- https://www.gov.br/pt-br/ - onde os manuais foram privados 

Alguém do serpro não poderia obter esses manuais e adicioná-los aqui no github?

Os endereços antigos dos manuais são esses:

- Diretrizes - http://www.portalpadrao.gov.br/manuais/diretrizes/manual-de-diretrizes-1.pdf
- Guia de Estilo - http://www.portalpadrao.gov.br/manuais/guia-de-estilo/guia-de-estilo-2-0-1.pdf
- Gestão de Conteúdo - http://www.portalpadrao.gov.br/manuais/gestao-de-conteudo/manual-gestao_rev.pdf
- Barra de Identidade - http://www.portalpadrao.gov.br/manuais/barra-de-identidade-visual/manual-da-barra-de-identidade-visual-1.pdf
- Manual de uso de Redes Sociais - http://www.portalpadrao.gov.br/manuais/manual-de-uso-de-redes-sociais/manual-de-uso-de-redes-sociais-pagina-a-pagina-1.pdf

**Comment by thalesmota** [comment]
@claytonc, são exatamente esses manuais que estou procurando. Infelizmente eles só existiam em [http://www.portalpadrao.gov.br/manuais ](http://www.portalpadrao.gov.br/manuais )

@idgserpro, a Secom nunca teve em seu site os manuais da IDG 2.0. No site da Secom só tinha os manuais da IDG 1.0, e que ainda estão disponíveis em: [http://antigo.secom.gov.br/orientacoes-gerais#c1=Manuais&reversed=on&c12=effective&b_start=0](http://antigo.secom.gov.br/orientacoes-gerais#c1=Manuais&reversed=on&c12=effective&b_start=0).

Reforçando, também acredito que alguém do serpro poderia obter esses manuais e adicioná-los aqui no github, contribuindo assim para o uso correto da IDG 2.0 e permanecia do projeto.

**Comment by idgserpro** [comment]
@thalesmota @claytonc 

Eu não lembrava que no site da Secom só tinham manuais do IDG 1.0. Só lembrava que tinham manuais lá.

Não foi o Serpro que criou esses manuais. Inclusive já abrimos issue para atualizar o manual:

https://github.com/plonegovbr/brasil.gov.portal/issues/580

As cópias que temos desses manuais estão corrômpidas. Por isso sugiro que procurem junto a Secom. Talvez pelo fale conosco. Eles eram os responsáveis por esses manuais. E talvez o @hvelarde possa ajudar. Ele foi um dos devenvolvedores do IDG 2.0.

**Comment by hvelarde** [comment]
bom dia, eu não tenho copia desses manuais; até onde lembro eles eram preparados pela empresa de marketing digital que levava o projeto.

**Comment by hvelarde** [comment]
achei uns manuais num site da presidencia: https://gestaoconteudo.presidencia.gov.br/gestao_portalpadrao/manuais/

o certificado do site está errado e marca como não seguro no browser, mas os manuais que vocês estão procurando parece que estão ai.
