### ISSUE TITLE
Como Implantar o Plone IDG com Docker

### ISSUE THREAD

**Issue by ililminati** [plonegovbr/brasil.gov.portal#611]
Bom dia,

Pessoal, não sei se este é o local adequando, mas, gostaria de saber de vocês, se há algum material que aborde como pode ser feita a implantação do Plone com IDG utilizando Docker. Tenho a intenção de usar o Plone IDG na UFCG, porém, nativamente nossos servidores não dão suporte aos requisitos do Plone, por esta razão, precisaria fazer esta implantação usando o Docker. Obrigado desde já.

**Comment by idgserpro** [comment]
Existe uma documentação de instalação com docker mas a imagem deve esta bem desatualizada:

https://github.com/plonegovbr/portal.buildout/blob/master/docs/desenvolvimento.rst#instala%C3%A7%C3%A3o-com-docker

A configuração do docker fica em:

https://github.com/plonegovbr/portal.buildout/tree/master/docker

**Comment by caduvieira** [comment]
@ililminati algo que você pode tentar fazer é usar o Plone Docker oficial https://hub.docker.com/_/plone e adicionar o plonegovbr como addon.

**Comment by caduvieira** [comment]
Você pode tentar usar o Dockerfile:
Dockerfile:


```
FROM plone:4.3.18-alpine

ADD --chown=plone:plone https://raw.githubusercontent.com/plonegovbr/portalpadrao.release/master/2.1.1/versions.cfg /plone/instance/
RUN sed -i '/six = 1.10.0/c\six = 1.12.0' /plone/instance/versions.cfg && sed -i '3iimportlib-metadata = 2.1.1' /plone/instance/versions.cfg \
    && sed -i '3izipp = 1.2.0' /plone/instance/versions.cfg
```

Esses Seds são para corrigir alguns problemas de versões como o https://github.com/plonegovbr/brasil.gov.portal/issues/606 mas não testei para ver se está ok.

Faz o build
`docker build -t plonegovbr:2.1.1 .`

depois executa
`docker run -p 8080:8080 -e ADDONS="brasil.gov.portal" -e VERSIONS="brasil.gov.portal=2.1.1" plonegovbr:2.1.1`

Quando terminar acessa o localhost:8080

Mais sobre o docker/plone tem no https://docs.plone.org/manage/docker/docs/usage/basic.html

Só te lembrando que isso aí de cima é mais para teste e que não leva em conta coisas como o zeoserver, backups e nem o balanceamento de carga.

**Comment by ililminati** [comment]
Primeiro obrigado pelas respostas. Então que dizer que vocês não recomendam usar o Docker em ambiente de produção?

**Comment by caduvieira** [comment]
> Primeiro obrigado pelas respostas. Então que dizer que vocês não recomendam usar o Docker em ambiente de produção?

Recomendo sim. O Docker já é considerado tecnologia estável e pronta para produção. Agora usar esse dockerfile acima que coloquei como exemplo não recomendo não. Inclusive ele vai baixar todos os pacotes sempre que rodar. Não sei dizer o que o idgserpro acha. 

Se você está dizendo sobre o:

> "Só te lembrando que isso aí de cima é mais para teste e que não leva em conta coisas como o zeoserver, backups e nem o balanceamento de carga."

É exatamente isso que eu quis dizer. Esse arquivo Dockerfile é só um exemplo e não trata de volumes, backups e balanceamento de carga. Em um ambiente de produção é recomendado pensar nessas coisas.

Para usar a imagem docker oficial recomendo que você veja a documentação da mesma tanto https://hub.docker.com/_/plone como https://docs.plone.org/manage/docker/docs/usage/basic.html
