### ISSUE TITLE
Corrigir o registro da font-face bold no css

### ISSUE THREAD

**Issue by rennan** [plonegovbr/brasil.gov.portal#76]
Está faltando registrar na url o caminho completo do arquivo.

https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/static/css/main.css#L75-L79

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by rennan** [comment]
@hvelarde pode fechar.
