### ISSUE TITLE
Revisar tradução do pacote

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.portal#9]
O pacote possui alguns pontos como por exemplo https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/browser/busca/templates/search.pt#L31 que não possui tradução adequada.

Seria necessário revisar a tradução do pacote para este e outros pacotes que estão com conteúdo fixo, para dar a possibilidade de tradução do site.

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by idgserpro** [comment]
Favor manter aberto. Ainda há algumas questões pendentes e algumas delas serão resolvidas via pull request.

**Comment by idgserpro** [comment]
Corrigido em:

https://github.com/plonegovbr/brasil.gov.portal/issues/177
https://github.com/plonegovbr/brasil.gov.portal/pull/13
https://github.com/plonegovbr/brasil.gov.portal/pull/192
