### ISSUE TITLE
Corrigir o "Link to Collection"

### ISSUE THREAD

**Issue by taniaa** [plonegovbr/brasil.gov.portal#95]
No produto Doormat, utilizado no rodape do Portal Padrao, precisa desabilitar o Link to Collection disponivel na Section de um DoormatColumn.

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by taniaa** [comment]
Ainda está lá. Olha o print.
![captura de tela 2015-03-06 as 00 04 11](https://cloud.githubusercontent.com/assets/1102067/6519551/66f82664-c394-11e4-858c-9c1eec50c43b.png)

**Comment by idgserpro** [comment]
Em versões Products.Doormat < 0.8, [o pacote não diferenciava se o Link era Archetypes ou Dexterity](https://github.com/collective/Products.Doormat/blob/758b648fcd0fdc63dd2e64c1efc6a7c168091300/Products/Doormat/browser/views.py#L74), pegando apenas Archetypes. Assim, a url vinha como um [método](https://github.com/plone/Products.ATContentTypes/blob/c094c822e53f08db433a7a7c9100b0fee8f651a2/Products/ATContentTypes/content/link.py#L75):

    <bound method Link.getRemoteUrl of <Link at /Plone/rodape/coluna-1/assuntos/editoria-a>>
    <type 'instancemethod'>

Que renderizaca beleza na template, mas como usávamos no código Python, dava o erro

    File "/home/user/Desktop/minimalidg114/src/brasil/gov/portal/browser/content/doormat.py", line 38, in getDoormatData
        if '${navigation_root_url}' in link_url:
    TypeError: argument of type 'instancemethod' is not iterable

Por isso, [testávamos se o link era str/unicode e, se não fosse, invocávamos o __call__](https://github.com/plonegovbr/brasil.gov.portal/blob/1048aa279831371ba720ff6893f4337e73a58212/src/brasil/gov/portal/browser/content/doormat.py#L38).

Já em Products.Doormat > 0.8, ele passa a diferenciar entre Archetypes e Dexterity e passa a pegar um field já que era Dexterity, [remoteUrl](https://github.com/plone/plone.app.contenttypes/blob/7fca19b05d70dddac4b8004170c4c1a12498d6ae/plone/app/contenttypes/schema/link.xml), ao invés de um método, e tudo funciona, não precisando mais desse `if`.

Assim, para finalizarmos esse relato precisamos apenas de remover a linha que dá exceção hoje, em https://github.com/plonegovbr/brasil.gov.portal/blob/1048aa279831371ba720ff6893f4337e73a58212/src/brasil/gov/portal/browser/content/doormat.py#L38 e, após https://github.com/collective/Products.Doormat/issues/9 ser atendido e um novo release de Products.Doormat for lançado, removermos hoje toda a customização presente em Doormat. Junto dessa remoção dessa linha é importante colocar um `FIXME` e `BBB` no mesmo arquivo indicando que toda a customização pode ser removida quando o relato do Doormat for atendido.

Outro relato para remover essa customização foi feito em  https://github.com/plonegovbr/brasil.gov.portal/issues/295

**Comment by idgserpro** [comment]
Corrigido em https://github.com/plonegovbr/brasil.gov.portal/pull/302
